Improve markup
openmpf/openmpf pull request #1255
Opened 2021-02-03 07:59 UTC by jrobble

2021-02-11 18:11 UTC, brosenberg42 requested changes
I pushed a branch, br-review-markup, that contains many of the trivial changes I suggested.

> Reviewed 37 of 37 files at r1.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1255#-:-MTHFtUk1mQUbXlSWskX:b-mkifyv)* status: all files reviewed, 17 unresolved discussions (waiting on @jrobble)

___
*[trunk/markup/src/main/java/org/mitre/mpf/markup/MarkupRequestConsumer.java, line 99 at r1](https://reviewable.io/reviews/openmpf/openmpf/1255#-MTBUVuN5gyrfFRKjPAL:-MTBUVuN5gyrfFRKjPAM:b-dq6wrq) ([raw file](https://github.com/openmpf/openmpf/blob/1f4ac5aa10c81380e5f452ab21ee02de57893a7d/trunk/markup/src/main/java/org/mitre/mpf/markup/MarkupRequestConsumer.java#L99)):*
> ```Java
>         writer.setDestinationMedium(URI.create(markupRequest.getDestinationUri()));
> 
>         Map mediaMetadata = new HashMap<String, String>();
> ```

This line causes the non-generic version of Map to be used. It should either be:
`var mediaMetadata = new HashMap<String, String>();`
or
`Map<String, String> mediaMetadata = new HashMap<>()`
___
*[trunk/markup/src/main/java/org/mitre/mpf/markup/MarkupRequestConsumer.java, line 100 at r1](https://reviewable.io/reviews/openmpf/openmpf/1255#-MTBV9XD6dRci_uTPCSH:-MTBV9XD6dRci_uTPCSI:b87ugpl) ([raw file](https://github.com/openmpf/openmpf/blob/1f4ac5aa10c81380e5f452ab21ee02de57893a7d/trunk/markup/src/main/java/org/mitre/mpf/markup/MarkupRequestConsumer.java#L100)):*
> ```Java
> 
>         Map mediaMetadata = new HashMap<String, String>();
>         markupRequest.getMediaMetadataList().stream().forEach(e -> mediaMetadata.put(e.getKey(), e.getValue()) );
> ```

This is not how you create a map with streams. This should be: 
```java
var mediaMetadata = markupRequest.getMediaMetadataList()
        .stream()
        .collect(toMap(Markup.MetadataMap::getKey, Markup.MetadataMap::getValue))
```
___
*[trunk/video-overlay/src/main/cpp/BoundingBoxImageHandle.h, line 30 at r1](https://reviewable.io/reviews/openmpf/openmpf/1255#-MTBZHWkEW8y3Pjav--_:-MTBZHWkEW8y3Pjav--a:bitvbuj) ([raw file](https://github.com/openmpf/openmpf/blob/1f4ac5aa10c81380e5f452ab21ee02de57893a7d/trunk/video-overlay/src/main/cpp/BoundingBoxImageHandle.h#L30)):*
> ```objc
> #define MPF_BOUNDINGBOXIMAGEHANDLE_H
> 
> #include <MPFVideoCapture.h>
> ```

This is missing:
```
#include <string>

#include <opencv2/core.hpp>
```
___
*[trunk/video-overlay/src/main/cpp/BoundingBoxImageHandle.h, line 36 at r1](https://reviewable.io/reviews/openmpf/openmpf/1255#-MTBZMKJ4E6Vbdd4llai:-MTBZMKKBKVAFc8VJWPO:bmbm93s) ([raw file](https://github.com/openmpf/openmpf/blob/1f4ac5aa10c81380e5f452ab21ee02de57893a7d/trunk/video-overlay/src/main/cpp/BoundingBoxImageHandle.h#L36)):*
> ```objc
>     BoundingBoxImageHandle(std::string sourcePath, std::string destinationPath);
> 
>     cv::Size GetFrameSize();
> ```

This should be declared a const method.
___
*[trunk/video-overlay/src/main/cpp/BoundingBoxImageHandle.cpp, line 32 at r1](https://reviewable.io/reviews/openmpf/openmpf/1255#-MSmm3ow4HODUUhzMwIa:-MSmm3ow4HODUUhzMwIb:bbi8ahf) ([raw file](https://github.com/openmpf/openmpf/blob/1f4ac5aa10c81380e5f452ab21ee02de57893a7d/trunk/video-overlay/src/main/cpp/BoundingBoxImageHandle.cpp#L32)):*
> ```cpp
> BoundingBoxImageHandle::BoundingBoxImageHandle(std::string sourcePath, std::string destinationPath) :
>         sourcePath_(sourcePath),
>         destinationPath_(destinationPath),
> ```

These two strings should be `std::move()`ed in to their member variables.
___
*[trunk/video-overlay/src/main/cpp/BoundingBoxImageHandle.cpp, line 35 at r1](https://reviewable.io/reviews/openmpf/openmpf/1255#-MSmlfua3DV-wp-9W2fF:-MSmlfub5BjCft_IFiHj:bo2p7fu) ([raw file](https://github.com/openmpf/openmpf/blob/1f4ac5aa10c81380e5f452ab21ee02de57893a7d/trunk/video-overlay/src/main/cpp/BoundingBoxImageHandle.cpp#L35)):*
> ```cpp
>         videoCapture_(sourcePath_) {
>     if (!videoCapture_.IsOpened()) {
>         throw std::runtime_error("Unable to open source image: " + sourcePath_);
> ```

This is already checked in the MPFVideoCapture's constructor.
___
*[trunk/video-overlay/src/main/cpp/BoundingBoxVideoHandle.h, line 30 at r1](https://reviewable.io/reviews/openmpf/openmpf/1255#-MSms8SV9kbPNnmUNIGj:-MSms8SW7eikIv7Af73_:b-a9i3w7) ([raw file](https://github.com/openmpf/openmpf/blob/1f4ac5aa10c81380e5f452ab21ee02de57893a7d/trunk/video-overlay/src/main/cpp/BoundingBoxVideoHandle.h#L30)):*
> ```objc
> #define MPF_BOUNDINGBOXVIDEOHANDLE_H
> 
> #include <MPFVideoCapture.h>
> ```

This and its .cpp file are missing a few includes. It is bad to rely on transitive includes, except for when you have `somefile.cpp` it is okay to depend on includes from `somefile.h`.
___
*[trunk/video-overlay/src/main/cpp/BoundingBoxVideoHandle.h, line 38 at r1](https://reviewable.io/reviews/openmpf/openmpf/1255#-MSmzpRWBEQ9AcVawA1P:-MSmzpRWBEQ9AcVawA1Q:b-bwo0an) ([raw file](https://github.com/openmpf/openmpf/blob/1f4ac5aa10c81380e5f452ab21ee02de57893a7d/trunk/video-overlay/src/main/cpp/BoundingBoxVideoHandle.h#L38)):*
> ```objc
>     ~BoundingBoxVideoHandle();
> 
>     cv::Size GetFrameSize();
> ```

This method and few others here and in BoundingBoxImageHandle can be made const.
___
*[trunk/video-overlay/src/main/cpp/BoundingBoxVideoHandle.cpp, line 34 at r1](https://reviewable.io/reviews/openmpf/openmpf/1255#-MSmxEX6077uiKgohm6r:-MSmxEX6077uiKgohm6s:bnbzear) ([raw file](https://github.com/openmpf/openmpf/blob/1f4ac5aa10c81380e5f452ab21ee02de57893a7d/trunk/video-overlay/src/main/cpp/BoundingBoxVideoHandle.cpp#L34)):*
> ```cpp
> BoundingBoxVideoHandle::BoundingBoxVideoHandle(std::string sourcePath, std::string destinationPath, int crf,
>                                                int framePadding) :
>         destinationPath_(destinationPath), videoCapture_(sourcePath) {
> ```

`destinationPath_(destinationPath)` should be `destinationPath_(std::move(destinationPath))` because of  https://clang.llvm.org/extra/clang-tidy/checks/modernize-pass-by-value.html .  `std::string sourcePath` should be `const std::string& sourcePath` because `MPFVideoCapture`'s constructor parameter is a `const std::string&`.
___
*[trunk/video-overlay/src/main/cpp/BoundingBoxVideoHandle.cpp, line 75 at r1](https://reviewable.io/reviews/openmpf/openmpf/1255#-MTGkJJd39Sl1Wi4AmpD:-MTGkJJe11pwC-CPd7mI:bwaz2om) ([raw file](https://github.com/openmpf/openmpf/blob/1f4ac5aa10c81380e5f452ab21ee02de57893a7d/trunk/video-overlay/src/main/cpp/BoundingBoxVideoHandle.cpp#L75)):*
> ```cpp
> void BoundingBoxVideoHandle::HandleMarkedFrame(const cv::Mat& frame) {
>     size_t sizeInBytes = frame.step[0] * frame.rows; // https://stackoverflow.com/a/26441073
>     fwrite(frame.data, sizeof(unsigned char), sizeInBytes, pipe_);
> ```

We should properly handle non-continuous `cv::Mat`s. Cropping off the left or right side of an image will result in the matrix being non-continuous because cropping doesn't copy the matrix, it creates a submatrix pointing in to the original un-cropped frame. This will cause ffmpeg to be passed data with sections it was supposed to skip. Right now, the only reason this isn't an issue is that you make an unnecessary clone on this line: `Mat transformFrame = frame.clone();`. I think we should copy in the data row by row. This shouldn't affect performance since we can avoid a clone and I'm pretty sure the bottle neck is ffmpeg encoding, not copying the frames in to the pipe. I tested removing the clone and changing the lines to use `frame` instead of `transformFrame`. This resulted in a garbled video. After I made the change below, it produced the correct video.

```c++
for (int row = 0; row < frame.rows; ++row) {
    fwrite(frame.ptr(row), frame.elemSize(), frame.cols, pipe_);
}
```
I read the stack overflow link and `frame.elemSize()` is the correct thing to use in the code above. `frame.step[0]` is the width of the frame before cropping. A single row is always continuous so the stack overflow comment does not apply. `frame.elemSize()` is always 3 whic [...]

2021-02-22 22:23 UTC, jrobble reviewed
Thanks. Good catches. I'm have more updates planned for this PR.

> Reviewed 24 of 37 files at r1, 13 of 13 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1255#-:-MUAP2n10Pq-73Xow8YI:b-xl4ooh)* status: all files reviewed, 17 unresolved discussions (waiting on @brosenberg42 and @clnowacki)

___
*[trunk/markup/src/main/java/org/mitre/mpf/markup/MarkupRequestConsumer.java, line 99 at r1](https://reviewable.io/reviews/openmpf/openmpf/1255#-MTBUVuN5gyrfFRKjPAL:-MUAezP_6T77QwQ4ZafF:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/1f4ac5aa10c81380e5f452ab21ee02de57893a7d/trunk/markup/src/main/java/org/mitre/mpf/markup/MarkupRequestConsumer.java#L99)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

This line causes the non-generic version of Map to be used. It should either be:
`var mediaMetadata = new HashMap<String, String>();`
or
`Map<String, String> mediaMetadata = new HashMap<>()`
</blockquote></details>

Done.
___
*[trunk/markup/src/main/java/org/mitre/mpf/markup/MarkupRequestConsumer.java, line 100 at r1](https://reviewable.io/reviews/openmpf/openmpf/1255#-MTBV9XD6dRci_uTPCSH:-MUAf7czECbJwG7NcGO9:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/1f4ac5aa10c81380e5f452ab21ee02de57893a7d/trunk/markup/src/main/java/org/mitre/mpf/markup/MarkupRequestConsumer.java#L100)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

This is not how you create a map with streams. This should be: 
```java
var mediaMetadata = markupRequest.getMediaMetadataList()
        .stream()
        .collect(toMap(Markup.MetadataMap::getKey, Markup.MetadataMap::getValue))
```
</blockquote></details>

Done.
___
*[trunk/video-overlay/src/main/cpp/BoundingBoxImageHandle.h, line 30 at r1](https://reviewable.io/reviews/openmpf/openmpf/1255#-MTBZHWkEW8y3Pjav--_:-MUAfcB4CIOHhV9oKbvH:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/1f4ac5aa10c81380e5f452ab21ee02de57893a7d/trunk/video-overlay/src/main/cpp/BoundingBoxImageHandle.h#L30)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

This is missing:
```
#include <string>

#include <opencv2/core.hpp>
```
</blockquote></details>

Done.
___
*[trunk/video-overlay/src/main/cpp/BoundingBoxImageHandle.h, line 36 at r1](https://reviewable.io/reviews/openmpf/openmpf/1255#-MTBZMKJ4E6Vbdd4llai:-MUAfdCL87V6K36WESZg:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/1f4ac5aa10c81380e5f452ab21ee02de57893a7d/trunk/video-overlay/src/main/cpp/BoundingBoxImageHandle.h#L36)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

This should be declared a const method.
</blockquote></details>

Done.
___
*[trunk/video-overlay/src/main/cpp/BoundingBoxImageHandle.cpp, line 32 at r1](https://reviewable.io/reviews/openmpf/openmpf/1255#-MSmm3ow4HODUUhzMwIa:-MUAfeRU8B5ISWYnZo_F:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/1f4ac5aa10c81380e5f452ab21ee02de57893a7d/trunk/video-overlay/src/main/cpp/BoundingBoxImageHandle.cpp#L32)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

These two strings should be `std::move()`ed in to their member variables.
</blockquote></details>

Done.
___
*[trunk/video-overlay/src/main/cpp/BoundingBoxImageHandle.cpp, line 35 at r1](https://reviewable.io/reviews/openmpf/openmpf/1255#-MSmlfua3DV-wp-9W2fF:-MUAffuT6PSFtxC4AG_D:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/1f4ac5aa10c81380e5f452ab21ee02de57893a7d/trunk/video-overlay/src/main/cpp/BoundingBoxImageHandle.cpp#L35)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

This is already checked in the MPFVideoCapture's constructor.
</blockquote></details>

Done.
___
*[trunk/video-overlay/src/main/cpp/BoundingBoxVideoHandle.h, line 30 at r1](https://reviewable.io/reviews/openmpf/openmpf/1255#-MSms8SV9kbPNnmUNIGj:-MUAfhW47sK8kAp38Xwk:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/1f4ac5aa10c81380e5f452ab21ee02de57893a7d/trunk/video-overlay/src/main/cpp/BoundingBoxVideoHandle.h#L30)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

This and its .cpp file are missing a few includes. It is bad to rely on transitive includes, except for when you have `somefile.cpp` it is okay to depend on includes from `somefile.h`.
</blockquote></details>

Done.
___
*[trunk/video-overlay/src/main/cpp/BoundingBoxVideoHandle.h, line 38 at r1](https://reviewable.io/reviews/openmpf/openmpf/1255#-MSmzpRWBEQ9AcVawA1P:-MUAfiUp3BQQ1D5UCySq:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/1f4ac5aa10c81380e5f452ab21ee02de57893a7d/trunk/video-overlay/src/main/cpp/BoundingBoxVideoHandle.h#L38)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

This method and few others here and in BoundingBoxImageHandle can be made const.
</blockquote></details>

Done.
___
*[trunk/video-overlay/src/main/cpp/BoundingBoxVideoHandle.cpp, line 34 at r1](https://reviewable.io/reviews/openmpf/openmpf/1255#-MSmxEX6077uiKgohm6r:-MUAflxHCwTBMF9kVuTR:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/1f4ac5aa10c81380e5f452ab21ee02de57893a7d/trunk/video-overlay/src/main/cpp/BoundingBoxVideoHandle.cpp#L34)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

`destinationPath_(destinationPath)` should be `destinationPath_(std::move(destinationPath))` because of  https://clang.llvm.org/extra/clang-tidy/checks/modernize-pass-by-value.html .  `std::string sourcePath` should be `const std::string& sourcePath` because `MPFVideoCapture`'s constructor parameter is a `const std::string&`.
</blockquote></details>

Done.
___
*[trunk/video-overlay/src/main/cpp/BoundingBoxVideoHandle.cpp, line 75 at r1](https://reviewable.io/reviews/openmpf/openmpf/1255#-MTGkJJd39Sl1Wi4AmpD:-MUAiJnH9aT57yCq2O9n:b-74vy1h) ([raw file](https://github.com/openmpf/openmpf/blob/1f4ac5aa10c81380e5f452ab21ee02de57893a7d/trunk/video-overlay/src/main/cpp/BoundingBoxVideoHandle.cpp#L75)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

We should properly handle non-continuous `cv::Mat`s. Cropping off the left or right side of an image will result in the matrix being non-continuous because cropping doesn't copy the matrix, it creates a submatrix pointing in to the original un-cropped frame. This will cause ffmpeg to be passed data with sections it was supposed to skip. Right now, the only reason this isn't an issue is that you make an unnecessary clone on this line: `Mat transformFrame = frame.clone();`. I think we should copy in the data row by row. This shouldn't affect performance since we can avoid a clone and I'm pretty sure the bottle neck is ffmpeg encoding, not copying the frames in to the pipe. I tested removing the clone and changing the lines to use `frame` instead of `transformFrame`. This resulted in a garbled video. After I made the change below, it produced the correct video.

```c++
for (int row = 0; row < frame.rows; ++row) {
    fwrite(frame.ptr(row), frame.elemSize(), frame.cols, pipe_);
}
```
I read the stack overflow link and `frame.elemSize()` is the correct thing to use in the code above. `frame.step[0]` is the width of the frame before cropping. A single row is always continuous so the stack overflow comment does not apply. `frame.elemSize()` is always 3 which is required because of `-pixel_format bgr24`.

</blockquote></details>

Good catch. I updated the PR to do it your way.
___
*[trunk/video-overlay/src/main/cpp/BoundingBoxVideoHandle.cpp, line 88 at r1](https://reviewable.io/reviews/openmpf/openmpf/1255#-MSbxQzm5DrvZ_qX3wXF:-MUAkKS2ESzrTbkvTfe9:bxaed7x) ([raw file](https://github.com/openmpf/openmpf/blob/1f4ac5aa10c81380e5f452ab21ee02de57893a7d/trunk/video-overlay/src/main/cpp/BoundingBoxVideoHandle.cpp#L88)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockq [...]

2021-02-27 11:40 UTC, jrobble reviewed
> Reviewed 19 of 19 files at r4.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1255)* status: all files reviewed, 19 unresolved discussions (waiting on @brosenberg42 and @clnowacki)

___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/markup/MarkupSplitter.java, line 354 at r4](https://reviewable.io/reviews/openmpf/openmpf/1255#-MUYH1so2Zmhj9LIZ5nT:-MUYH1so2Zmhj9LIZ5nU:b-hrz1l6) ([raw file](https://github.com/openmpf/openmpf/blob/8f4c4c45bd78009784470971f8676667972cd3fb/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/markup/MarkupSplitter.java#L354)):*
> ```Java
>         String label = "";
>         if (textPart != null) {
>             label += String.format("%.10s", textPart).strip();
> ```

I decided to omit the "..." at the end of long labels to save space.
___
*[trunk/workflow-manager/src/main/resources/workflow-properties.json, line 35 at r4](https://reviewable.io/reviews/openmpf/openmpf/1255#-MUYHJXx4E3lQQHYM7_-:-MUYHJXx4E3lQQHYM7_0:b-ut13k8) ([raw file](https://github.com/openmpf/openmpf/blob/8f4c4c45bd78009784470971f8676667972cd3fb/trunk/workflow-manager/src/main/resources/workflow-properties.json#L35)):*
> ```JSON
>         "type": "BOOLEAN",
>         "propertiesKey": "mpf.output.objects.last.task.only",
>         "mediaTypes": ["VIDEO", "IMAGE", "AUDIO", "UNKNOWN"]
> ```

Resolves https://github.com/openmpf/openmpf/issues/1257.
___
*[trunk/workflow-manager/src/main/resources/properties/mpf.properties, line 302 at r1](https://reviewable.io/reviews/openmpf/openmpf/1255#-MTCabsl3SJ_XaJyGYNQ:-MUYGg-J2BBPmsMJG9LW:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/1f4ac5aa10c81380e5f452ab21ee02de57893a7d/trunk/workflow-manager/src/main/resources/properties/mpf.properties#L302)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

I'm pretty sure we are eventually going to have to make these settable through job properties, but this is fine for now. 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-15 15:06 UTC, brosenberg42 requested changes
> Reviewed 6 of 13 files at r2, 8 of 19 files at r4, 16 of 16 files at r5.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1255)* status: all files reviewed, 26 unresolved discussions (waiting on @jrobble)

___
*[trunk/video-overlay/src/main/cpp/BoundingBoxVideoHandle.cpp, line 36 at r5](https://reviewable.io/reviews/openmpf/openmpf/1255#-MVWig9P65LXidRA_jTo:-MVWig9P65LXidRA_jTp:b3ogpdp) ([raw file](https://github.com/openmpf/openmpf/blob/f5392eb02631fe52099b51b7f6e994ac8467ee33/trunk/video-overlay/src/main/cpp/BoundingBoxVideoHandle.cpp#L36)):*
> ```cpp
> 
> 
> BoundingBoxVideoHandle::BoundingBoxVideoHandle(const std::string &sourcePath, std::string destinationPath,
> ```

`sourcePath` is unused.
___
*[trunk/video-overlay/src/main/cpp/BoundingBoxVideoHandle.cpp, line 37 at r5](https://reviewable.io/reviews/openmpf/openmpf/1255#-MVWjpTJBu033TniWE9A:-MVWjpTKALcSt0Eg_BFo:b-xj0yfi) ([raw file](https://github.com/openmpf/openmpf/blob/f5392eb02631fe52099b51b7f6e994ac8467ee33/trunk/video-overlay/src/main/cpp/BoundingBoxVideoHandle.cpp#L37)):*
> ```cpp
> 
> BoundingBoxVideoHandle::BoundingBoxVideoHandle(const std::string &sourcePath, std::string destinationPath,
>                                                std::string &encoder, int vp9Crf, bool border,
> ```

`encoder` should be const
___
*[trunk/video-overlay/src/main/cpp/BoundingBoxVideoHandle.cpp, line 40 at r5](https://reviewable.io/reviews/openmpf/openmpf/1255#-MVWhSGx0tOhVKeo02EJ:-MVWhSGy4owg3SMfHf8m:b-7d3q0b) ([raw file](https://github.com/openmpf/openmpf/blob/f5392eb02631fe52099b51b7f6e994ac8467ee33/trunk/video-overlay/src/main/cpp/BoundingBoxVideoHandle.cpp#L40)):*
> ```cpp
>                                                const ResolutionConfig &resCfg,
>                                                MPF::COMPONENT::MPFVideoCapture &videoCapture) :
>         destinationPath_(std::move(destinationPath)), videoCapture_(std::move(videoCapture)) {
> ```

Moving a parameter that was passed by reference is dangerous because the caller has no idea that the function moved the object and that it is no longer valid. `MPFVideoCapture` should be passed by value and moved in at the call site. So
this:
```cpp
BoundingBoxVideoHandle boundingBoxVideoHandle(sourceVideoPath, destinationVideoPath, encoder, vp9Crf, border,
                                              resCfg, videoCapture)
```
should be changed to:
```cpp
BoundingBoxVideoHandle boundingBoxVideoHandle(sourceVideoPath, destinationVideoPath, encoder, vp9Crf, border,
                                              resCfg, std::move(videoCapture))
```
___
*[trunk/video-overlay/src/main/cpp/BoundingBoxVideoHandle.cpp, line 57 at r5](https://reviewable.io/reviews/openmpf/openmpf/1255#-MVY4xrh-zRt8gXzeVq6:-MVY4xrh-zRt8gXzeVq7:b-whjg86) ([raw file](https://github.com/openmpf/openmpf/blob/f5392eb02631fe52099b51b7f6e994ac8467ee33/trunk/video-overlay/src/main/cpp/BoundingBoxVideoHandle.cpp#L57)):*
> ```cpp
>         " -f rawvideo" +
>         " -i -" +
>         " -pix_fmt yuv420p"; // https://trac.ffmpeg.org/ticket/5276
> ```

A very brief explanation with the link comments would be helpful since the link eventually not work.
___
*[trunk/video-overlay/src/main/cpp/BoundingBoxVideoHandle.cpp, line 59 at r5](https://reviewable.io/reviews/openmpf/openmpf/1255#-MVq0SbW-QI7bVbaIzNg:-MVq0SbW-QI7bVbaIzNh:blbx055) ([raw file](https://github.com/openmpf/openmpf/blob/f5392eb02631fe52099b51b7f6e994ac8467ee33/trunk/video-overlay/src/main/cpp/BoundingBoxVideoHandle.cpp#L59)):*
> ```cpp
>         " -pix_fmt yuv420p"; // https://trac.ffmpeg.org/ticket/5276
> 
>     if (std::string("vp9") == encoder) { // .webm
> ```

This should just be `if ("vp9" == encoder) { ` There is a `==` overload for `const char*` and `std::string`.
___
*[trunk/video-overlay/src/main/cpp/BoundingBoxWriter.cpp, line 60 at r5](https://reviewable.io/reviews/openmpf/openmpf/1255#-MVaie2y-3seBC_9Eq91:-MVWld31-af9NtyrX3wq:b-ft9bvi) ([raw file](https://github.com/openmpf/openmpf/blob/f5392eb02631fe52099b51b7f6e994ac8467ee33/trunk/video-overlay/src/main/cpp/BoundingBoxWriter.cpp#L60)):*
> ```cpp
> 
> // https://unicode.org/emoji/charts/full-emoji-list.html
> const std::string fastForwardEmoji = "\U000023E9";
> ```

These declaration all trigger https://clang.llvm.org/extra/clang-tidy/checks/cert-err58-cpp.html . These should all be declared like `constexpr const char * fastForwardEmoji = "\U000023E9";`
___
*[trunk/video-overlay/src/main/cpp/BoundingBoxWriter.cpp, line 67 at r5](https://reviewable.io/reviews/openmpf/openmpf/1255#-MVWnSMjAnVPk-yzICCD:-MVWnSMjAnVPk-yzICCE:bpwzp2a) ([raw file](https://github.com/openmpf/openmpf/blob/f5392eb02631fe52099b51b7f6e994ac8467ee33/trunk/video-overlay/src/main/cpp/BoundingBoxWriter.cpp#L67)):*
> ```cpp
> const std::string starEmoji        = "\U00002B50";
> 
> auto ft = cv::freetype::createFreeType2(); // for emojis
> ```

This shouldn't be a global variable and it should have a more descriptive name
___
*[trunk/video-overlay/src/main/cpp/BoundingBoxWriter.cpp, line 397 at r5](https://reviewable.io/reviews/openmpf/openmpf/1255#-MVb_C72-TJirbDnRvMh:-MVb_C72-TJirbDnRvMi:b405uq3) ([raw file](https://github.com/openmpf/openmpf/blob/f5392eb02631fe52099b51b7f6e994ac8467ee33/trunk/video-overlay/src/main/cpp/BoundingBoxWriter.cpp#L397)):*
> ```cpp
> 
> 
> const ResolutionConfig getResolutionConfig(int width, int height) {
> ```

Returning a const value is the same as just returning a value so it shouldn't be used when returning by value. https://clang.llvm.org/extra/clang-tidy/checks/readability-const-return-type.html
___
*[trunk/video-overlay/src/main/cpp/BoundingBoxWriter.cpp, line 398 at r5](https://reviewable.io/reviews/openmpf/openmpf/1255#-MVWttAg-N0ekQp21TGP:-MVWttAg-N0ekQp21TGQ:b7ceq0o) ([raw file](https://github.com/openmpf/openmpf/blob/f5392eb02631fe52099b51b7f6e994ac8467ee33/trunk/video-overlay/src/main/cpp/BoundingBoxWriter.cpp#L398)):*
> ```cpp
> 
> const ResolutionConfig getResolutionConfig(int width, int height) {
>     ft->loadFontData("/usr/share/fonts/google-noto-emoji/NotoEmoji-Regular.ttf", 0);
> ```

We should handle the case where the font doesn't exist. Currently, this is the error you get: `"Error writing bounding box(es). OpenCV(4.5.0) /apps/source/opencv4/opencv_contrib-4.5.0/modules/freetype/src/freetype.cpp:175: error: (-215:Assertion failed) !FT_New_Face( mLibrary, fontFileName.c_str(), idx, &(mFace) ) in function 'loadFontData'\n"`
___
*[trunk/video-overlay/src/main/cpp/BoundingBoxWriter.cpp, line 467 at r5](https://reviewable.io/reviews/openmpf/openmpf/1255#-MVWp2YcE6YQpSCMFaGZ:-MVWp2YcE6YQpSCMFaG_:b-4n2ytm) ([raw file](https://github.com/openmpf/openmpf/blob/f5392eb02631fe52099b51b7f6e994ac8467ee33/trunk/video-overlay/src/main/cpp/BoundingBoxWriter.cpp#L467)):*
> ```cpp
> 
> void drawBoundingBox(int x, int y, int width, int height, double boxRotation, bool boxFlip, double mediaRotation,
>                      bool mediaFlip, int red, int green, int blue, double alpha, BoundingBoxSource source,
> ```

`source` is unused
___
*[trunk/video-overlay/src/main/cpp/BoundingBoxWriter.cpp, line 518 at r5](https://reviewable.io/reviews/openmpf/openmpf/1255#-MVabDjY-piIAQswB6hX:-MVabDjY-piIAQswB6hY:b-qoeeni) ([raw file](https://github.com/openmpf/openmpf/blob/f5392eb02631fe52099b51b7f6e994ac8467ee33/trunk/video-overlay/src/main/cpp/BoundingBoxWriter.cpp#L518)):*
> ```cpp
> }
> 
> void drawLine(const Point2d &start, const Point2d &end, const Scalar &color, bool dashed,
> ```

`dashed` is always false.
___
*[trunk/video-overlay/src/main/cpp/BoundingBoxWriter.cpp, line 599 at r5](https://reviewable.io/reviews/openmpf/openmpf/1255#-MVat0cH8GgcCd2Y-Oo2:-MVat0cH8GgcCd2Y-Oo3:b-6ihf8e) ([raw file](https://github.com/openmpf/openmpf/blob/f5392eb02631fe52099b51b7f6e994ac8467ee33/trunk/video-overlay/src/main/cpp/BoundingBoxWriter.cpp#L599)):*
> ```cpp
>     int labelRectTopRightY = pt.y - textLabelSize.height - (2 * resCfg.labelPadding);
> 
>     int lab [...]

2021-03-22 21:32 UTC, jrobble reviewed
> Reviewed 12 of 16 files at r5, 5 of 5 files at r6.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1255)* status: all files reviewed, 25 unresolved discussions (waiting on @brosenberg42)

___
*[trunk/video-overlay/src/main/cpp/BoundingBoxVideoHandle.cpp, line 36 at r5](https://reviewable.io/reviews/openmpf/openmpf/1255#-MVWig9P65LXidRA_jTo:-MVwzSSK73A-IpvFgJmA:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/f5392eb02631fe52099b51b7f6e994ac8467ee33/trunk/video-overlay/src/main/cpp/BoundingBoxVideoHandle.cpp#L36)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

`sourcePath` is unused.
</blockquote></details>

Done.
___
*[trunk/video-overlay/src/main/cpp/BoundingBoxVideoHandle.cpp, line 37 at r5](https://reviewable.io/reviews/openmpf/openmpf/1255#-MVWjpTJBu033TniWE9A:-MVwzSkRCnD1i5MO8JiF:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/f5392eb02631fe52099b51b7f6e994ac8467ee33/trunk/video-overlay/src/main/cpp/BoundingBoxVideoHandle.cpp#L37)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

`encoder` should be const
</blockquote></details>

Done.
___
*[trunk/video-overlay/src/main/cpp/BoundingBoxVideoHandle.cpp, line 40 at r5](https://reviewable.io/reviews/openmpf/openmpf/1255#-MVWhSGx0tOhVKeo02EJ:-MW03rqS7wJX6Q751FuZ:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/f5392eb02631fe52099b51b7f6e994ac8467ee33/trunk/video-overlay/src/main/cpp/BoundingBoxVideoHandle.cpp#L40)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

Moving a parameter that was passed by reference is dangerous because the caller has no idea that the function moved the object and that it is no longer valid. `MPFVideoCapture` should be passed by value and moved in at the call site. So
this:
```cpp
BoundingBoxVideoHandle boundingBoxVideoHandle(sourceVideoPath, destinationVideoPath, encoder, vp9Crf, border,
                                              resCfg, videoCapture)
```
should be changed to:
```cpp
BoundingBoxVideoHandle boundingBoxVideoHandle(sourceVideoPath, destinationVideoPath, encoder, vp9Crf, border,
                                              resCfg, std::move(videoCapture))
```
</blockquote></details>

Done.
___
*[trunk/video-overlay/src/main/cpp/BoundingBoxVideoHandle.cpp, line 57 at r5](https://reviewable.io/reviews/openmpf/openmpf/1255#-MVY4xrh-zRt8gXzeVq6:-MW0rWkH5Ka2Lx2HopyG:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/f5392eb02631fe52099b51b7f6e994ac8467ee33/trunk/video-overlay/src/main/cpp/BoundingBoxVideoHandle.cpp#L57)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

A very brief explanation with the link comments would be helpful since the link eventually not work.
</blockquote></details>

Done.
___
*[trunk/video-overlay/src/main/cpp/BoundingBoxVideoHandle.cpp, line 59 at r5](https://reviewable.io/reviews/openmpf/openmpf/1255#-MVq0SbW-QI7bVbaIzNg:-MW0rY527EWCjPJmsNmF:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/f5392eb02631fe52099b51b7f6e994ac8467ee33/trunk/video-overlay/src/main/cpp/BoundingBoxVideoHandle.cpp#L59)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

This should just be `if ("vp9" == encoder) { ` There is a `==` overload for `const char*` and `std::string`.
</blockquote></details>

Done.
___
*[trunk/video-overlay/src/main/cpp/BoundingBoxWriter.cpp, line 60 at r5](https://reviewable.io/reviews/openmpf/openmpf/1255#-MVaie2y-3seBC_9Eq91:-MW11zP04SzVO2gn9hZl:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/f5392eb02631fe52099b51b7f6e994ac8467ee33/trunk/video-overlay/src/main/cpp/BoundingBoxWriter.cpp#L60)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

These declaration all trigger https://clang.llvm.org/extra/clang-tidy/checks/cert-err58-cpp.html . These should all be declared like `constexpr const char * fastForwardEmoji = "\U000023E9";`
</blockquote></details>

Done.
___
*[trunk/video-overlay/src/main/cpp/BoundingBoxWriter.cpp, line 67 at r5](https://reviewable.io/reviews/openmpf/openmpf/1255#-MVWnSMjAnVPk-yzICCD:-MWQi4Ks7VmVJvVku3zk:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/f5392eb02631fe52099b51b7f6e994ac8467ee33/trunk/video-overlay/src/main/cpp/BoundingBoxWriter.cpp#L67)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

This shouldn't be a global variable and it should have a more descriptive name
</blockquote></details>

Done.
___
*[trunk/video-overlay/src/main/cpp/BoundingBoxWriter.cpp, line 397 at r5](https://reviewable.io/reviews/openmpf/openmpf/1255#-MVb_C72-TJirbDnRvMh:-MW1C9AC50rPt78ieWI3:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/f5392eb02631fe52099b51b7f6e994ac8467ee33/trunk/video-overlay/src/main/cpp/BoundingBoxWriter.cpp#L397)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

Returning a const value is the same as just returning a value so it shouldn't be used when returning by value. https://clang.llvm.org/extra/clang-tidy/checks/readability-const-return-type.html
</blockquote></details>

Done.
___
*[trunk/video-overlay/src/main/cpp/BoundingBoxWriter.cpp, line 398 at r5](https://reviewable.io/reviews/openmpf/openmpf/1255#-MVWttAg-N0ekQp21TGP:-MWQ2D7l6FhgQB0Lg5p4:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/f5392eb02631fe52099b51b7f6e994ac8467ee33/trunk/video-overlay/src/main/cpp/BoundingBoxWriter.cpp#L398)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

We should handle the case where the font doesn't exist. Currently, this is the error you get: `"Error writing bounding box(es). OpenCV(4.5.0) /apps/source/opencv4/opencv_contrib-4.5.0/modules/freetype/src/freetype.cpp:175: error: (-215:Assertion failed) !FT_New_Face( mLibrary, fontFileName.c_str(), idx, &(mFace) ) in function 'loadFontData'\n"`
</blockquote></details>

Done.
___
*[trunk/video-overlay/src/main/cpp/BoundingBoxWriter.cpp, line 467 at r5](https://reviewable.io/reviews/openmpf/openmpf/1255#-MVWp2YcE6YQpSCMFaGZ:-MWPqcf--giOP55S4DOe:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/f5392eb02631fe52099b51b7f6e994ac8467ee33/trunk/video-overlay/src/main/cpp/BoundingBoxWriter.cpp#L467)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

`source` is unused
</blockquote></details>

Done.
___
*[trunk/video-overlay/src/main/cpp/BoundingBoxWriter.cpp, line 518 at r5](https://reviewable.io/reviews/openmpf/openmpf/1255#-MVabDjY-piIAQswB6hX:-MWPsntt8-jRvtlx0zap:b-d46dup) ([raw file](https://github.com/openmpf/openmpf/blob/f5392eb02631fe52099b51b7f6e994ac8467ee33/trunk/video-overlay/src/main/cpp/BoundingBoxWriter.cpp#L518)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

`dashed` is always false.
</blockquote></details>

Removed parameter. Commented out dashed line code for potential future use.
___
*[trunk/video-overlay/src/main/cpp/BoundingBoxWriter.cpp, line 599 at r5](https://reviewable.io/reviews/openmpf/openmpf/1255#-MVat0cH8GgcCd2Y-Oo2:-MWPthPkBwC1h-XYB1RW:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/f5392eb02631fe52099b51b7f6e994ac8467ee33/trunk/video-overlay/src/main/cpp/BoundingBoxWriter.cpp#L599)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

You are subtracting something you just added. This appears to be equivalent to `int labelRectWidth = resCfg.labelIndent + emojiLabelSize.width + textLabelSize.width + resCfg.labelPadding;` and `labelRectTopRightX` is not used anywhere else.
</blockquote></details>

Done.
___
*[trunk/video-overlay/src/main/cpp/BoundingBoxWriter.cpp, line 600 at r5](https://reviewable.io/reviews/openmpf/openmpf/1255#-MVatUUjCurHkunkKF_I:-MWPth9y1oERn2zgllsH:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/f5392eb02631fe52099b51b7f6e994ac8467ee33/trunk/video-overla [...]

2021-03-22 21:53 UTC, jrobble reviewed
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1255)* status: all files reviewed, 25 unresolved discussions (waiting on @brosenberg42)



<!-- Sent from Reviewable.io -->

2021-03-23 13:40 UTC, brosenberg42 approved these changes
> Reviewed 4 of 5 files at r6.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1255)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jrobble)



<!-- Sent from Reviewable.io -->

2021-03-23 13:40 UTC, brosenberg42 approved these changes
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1255)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jrobble)



<!-- Sent from Reviewable.io -->

2021-03-23 15:28 UTC, jrobble reviewed
> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1255)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jrobble)



<!-- Sent from Reviewable.io -->

2021-03-23 20:40 UTC, merged