Feature/ties db
openmpf/openmpf pull request #1343
Opened 2021-06-07 16:57 UTC by brosenberg42

**Issues:**

- https://github.com/openmpf/openmpf/issues/1158
- TiesDB

2021-06-16 03:59 UTC, jrobble commented
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/TiesDbService.java, line 69 at r2](https://reviewable.io/reviews/openmpf/openmpf/1343#-McBNKU54ojL3-DgjA3y:-McBNKU54ojL3-DgjA3z:b-jyo1k7) ([raw file](https://github.com/openmpf/openmpf/blob/f2a07f63186a14790af8d9232af1ebc0ca87607a/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/TiesDbService.java#L69)):*
Please add a comment to this file linking to https://github.com/Noblis/ties-lib and explaining what an `assertion` is in this context since that terminology is overloaded and rather confusing.

> Refer to https://github.com/Noblis/ties-lib for more information on the Triage Import Export Schema (TIES). For each piece of media, we create one or more TIES "supplementalDescription (Data Object)" entries in the database, one for each analytic (algorithm) run on the media. In general, a "supplementalDescription" is a kind of TIES "assertion", which is used to represent metadata about the media object. In our case it represents the detection and track information in the OpenMPF JSON output object.


<!-- Sent from Reviewable.io -->

2021-06-16 04:04 UTC, jrobble commented
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessorImpl.java, line 192 at r2](https://reviewable.io/reviews/openmpf/openmpf/1343#-McHymK2DlBp_gsoH6iI:-McHymK2DlBp_gsoH6iJ:bpiu6r8) ([raw file](https://github.com/openmpf/openmpf/blob/f2a07f63186a14790af8d9232af1ebc0ca87607a/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessorImpl.java#L192)):*
> ```Java
>                                 outputSha,
>                                 err))
>                         .thenCompose(resp -> tiesDbService.addAssertions(
> ```

As discussed, first try to create entries in TiesDb. Log a warning message upon failure. Then try the job callback. Again, log a warning message upon failure. No warnings are added to job, and therefore the JSON output object does not change if there is an issue.


<!-- Sent from Reviewable.io -->

2021-06-18 01:44 UTC, jrobble commented
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessorImpl.java, line 192 at r2](https://reviewable.io/reviews/openmpf/openmpf/1343#-McHymK2DlBp_gsoH6iI:-McQkd_UBvin3WIUyApr:bbyj94s) ([raw file](https://github.com/openmpf/openmpf/blob/f2a07f63186a14790af8d9232af1ebc0ca87607a/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessorImpl.java#L192)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

As discussed, first try to create entries in TiesDb. Log a warning message upon failure. Then try the job callback. Again, log a warning message upon failure. No warnings are added to job, and therefore the JSON output object does not change if there is an issue.
</blockquote></details>

I noticed that the POST attempts to job callback and the POST attempts to TiesDb are interleaved when the endpoints can't be reached and was able to get the job callback POST to occur first.

Previously we discussed avoiding a potential race condition by POSTing to TiesDb first, so we should ensure things happen sequentially here.


<!-- Sent from Reviewable.io -->

2021-06-18 02:56 UTC, jrobble commented
*[a discussion](https://reviewable.io/reviews/openmpf/openmpf/1343#-McRic25ACJmghG-q1rd:-McRic26ETpQY40fuHbc:b-ab6ut5) (no related file):*
I saw the results of MARKUPCV posted to the database. I guess that's fine since we're posting markup to the object store.

---

In a multi-stage pipeline with task merging, I saw this kind of POST:

```json
{
  "dataObject": {
    "trackCount": 0,
    "sha256OutputHash": "31a57d4a6e0d5de6d9d4091ebd27dbd74a987e5833c279bda5bdefafdf58cc82",
    "outputType": "NO TRACKS",
    "jobStatus": "COMPLETE",
    "systemVersion": "6.2",
    "jobId": 1117,
    "processDate": "2021-06-17T22:46:09.868-04:00",
    "systemHostname": "openmpf-master",
    "algorithm": "DNNCV",
    "outputUri": "file:///home/mpf/git/openmpf-projects/openmpf/trunk/install/share/output-objects/1117/detection.json"
  },
  "assertionId": "15db03289364a2252b96ff05adf7700cc50db3bd71ab5d6bbba4dd2a520f0c36",
  "informationType": "OpenMPF_NO TRACKS",
  "securityTag": "UNCLASSIFIED",
  "system": "OpenMPF"
}
```

These seem strange:

```
"outputType": "NO TRACKS",
"informationType": "OpenMPF_NO TRACKS",
```

I'm not sure if that's desirable. We should ask the end user.

This only happens for "NO TRACKS". It doesn't happen for "TRACKS MERGED" or "TRACKS SUPPRESSED".

---


<!-- Sent from Reviewable.io -->

2021-06-18 17:25 UTC, brosenberg42 reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1343)* status: 0 of 24 files reviewed, 3 unresolved discussions (waiting on @jrobble)

*[a discussion](https://reviewable.io/reviews/openmpf/openmpf/1343#-McRic25ACJmghG-q1rd:-McV8kPZ4T5bY36vrqyQ:b-896fix) (no related file):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I saw the results of MARKUPCV posted to the database. I guess that's fine since we're posting markup to the object store.

---

In a multi-stage pipeline with task merging, I saw this kind of POST:

```json
{
  "dataObject": {
    "trackCount": 0,
    "sha256OutputHash": "31a57d4a6e0d5de6d9d4091ebd27dbd74a987e5833c279bda5bdefafdf58cc82",
    "outputType": "NO TRACKS",
    "jobStatus": "COMPLETE",
    "systemVersion": "6.2",
    "jobId": 1117,
    "processDate": "2021-06-17T22:46:09.868-04:00",
    "systemHostname": "openmpf-master",
    "algorithm": "DNNCV",
    "outputUri": "file:///home/mpf/git/openmpf-projects/openmpf/trunk/install/share/output-objects/1117/detection.json"
  },
  "assertionId": "15db03289364a2252b96ff05adf7700cc50db3bd71ab5d6bbba4dd2a520f0c36",
  "informationType": "OpenMPF_NO TRACKS",
  "securityTag": "UNCLASSIFIED",
  "system": "OpenMPF"
}
```

These seem strange:

```
"outputType": "NO TRACKS",
"informationType": "OpenMPF_NO TRACKS",
```

I'm not sure if that's desirable. We should ask the end user.

This only happens for "NO TRACKS". It doesn't happen for "TRACKS MERGED" or "TRACKS SUPPRESSED".
</blockquote></details>

Done.

---
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessorImpl.java, line 192 at r2](https://reviewable.io/reviews/openmpf/openmpf/1343#-McHymK2DlBp_gsoH6iI:-McV8oVb5eqnMOZJlNrN:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/f2a07f63186a14790af8d9232af1ebc0ca87607a/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessorImpl.java#L192)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I noticed that the POST attempts to job callback and the POST attempts to TiesDb are interleaved when the endpoints can't be reached and was able to get the job callback POST to occur first.

Previously we discussed avoiding a potential race condition by POSTing to TiesDb first, so we should ensure things happen sequentially here.
</blockquote></details>

Done.
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/TiesDbService.java, line 69 at r2](https://reviewable.io/reviews/openmpf/openmpf/1343#-McBNKU54ojL3-DgjA3y:-McV8rqy38RSKdCAkL9-:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/f2a07f63186a14790af8d9232af1ebc0ca87607a/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/TiesDbService.java#L69)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please add a comment to this file linking to https://github.com/Noblis/ties-lib and explaining what an `assertion` is in this context since that terminology is overloaded and rather confusing.

> Refer to https://github.com/Noblis/ties-lib for more information on the Triage Import Export Schema (TIES). For each piece of media, we create one or more TIES "supplementalDescription (Data Object)" entries in the database, one for each analytic (algorithm) run on the media. In general, a "supplementalDescription" is a kind of TIES "assertion", which is used to represent metadata about the media object. In our case it represents the detection and track information in the OpenMPF JSON output object.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-18 21:39 UTC, jrobble requested changes
> Reviewed 17 of 19 files at r1, 1 of 1 files at r2, 5 of 5 files at r3, 6 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1343)* status: all files reviewed, 8 unresolved discussions (waiting on @brosenberg42)

*[a discussion](https://reviewable.io/reviews/openmpf/openmpf/1343#-McW1Kuk9LgTOQKLIxRJ:-McBZcl_8vQUBTP2lqWr:b-rfde9m) (no related file):*
Looking at the log output, I can't tell the difference between POST attempts for the different analytics:

```
2021-06-18 17:19:59,716 INFO [pool-5-thread-6] o.m.m.w.u.CallbackUtils - Starting POST callback to "http://localhost:8888/api/db/supplementals?sha256Hash=30068ed408eecb21f29c57b8b76954d0a3dc8b0703cfb7be8bca8214692be3f5".
2021-06-18 17:19:59,717 ERROR [pool-4-thread-1] o.m.m.w.u.CallbackUtils - Failed to issue POST callback to 'http://localhost:8888/api/db/supplementals?sha256Hash=30068ed408eecb21f29c57b8b76954d0a3dc8b0703cfb7be8bca8214692be3f5'. There are 1 attempts remaining and the next attempt will begin in 30000 ms.
```
```
2021-06-18 17:19:59,718 INFO [pool-5-thread-6] o.m.m.w.u.CallbackUtils - Starting POST callback to "http://localhost:8888/api/db/supplementals?sha256Hash=30068ed408eecb21f29c57b8b76954d0a3dc8b0703cfb7be8bca8214692be3f5".
2021-06-18 17:19:59,718 ERROR [pool-4-thread-1] o.m.m.w.u.CallbackUtils - Failed to issue POST callback to 'http://localhost:8888/api/db/supplementals?sha256Hash=30068ed408eecb21f29c57b8b76954d0a3dc8b0703cfb7be8bca8214692be3f5'. There are 1 attempts remaining and the next attempt will begin in 30000 ms.
```

Basically, anything that posts to the same media would have the same log line. Eventually, having job ids in these lines will help. I'm wondering if we want to consider differentiating between them more by adding the algorithm name to the log line.

I'm just thinking about the case where one succeeds and the other doesn't. How will the user know which is which? Maybe we should just ask them if they care or not. 

---
*[a discussion](https://reviewable.io/reviews/openmpf/openmpf/1343#-McRic25ACJmghG-q1rd:-McVyw5nD7HOkJVB0PfH:boanhwt) (no related file):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

MARKUP part works as intended.

---
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessorImpl.java, line 312 at r3](https://reviewable.io/reviews/openmpf/openmpf/1343#-McQl-IJ76e2tFf_q1iU:-McQl-IJ76e2tFf_q1iV:b-lmldw1) ([raw file](https://github.com/openmpf/openmpf/blob/b9aa3b207538deed79403d53186fa8b4a967651e/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessorImpl.java#L312)):*
> ```Java
> 
>         log.warn(String.format(
>                     "[Job %s] Sending HTTP %s callback to %s failed due to: %s",
> ```

Consider quoting the URL like you do in other log messages.
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/DetectionResponseProcessor.java, line 185 at r4](https://reviewable.io/reviews/openmpf/openmpf/1343#-McVmHCdDt29_l-ePeeq:-McVmHCdDt29_l-ePeer:b-v5rfyo) ([raw file](https://github.com/openmpf/openmpf/blob/319dd2350ac4f356c531e0c69f1d9e6e3518f7b7/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/DetectionResponseProcessor.java#L185)):*
> ```Java
>         }
> 
>         if (!tracksAdded) {
> ```

I'm getting a NullPointerException:

```
java.lang.NullPointerException: null
        at java.util.Objects.requireNonNull(Objects.java:221) ~[?:?]
        at java.util.ImmutableCollections$MapN.<init>(ImmutableCollections.java:827) ~[?:?]
        at java.util.Map.of(Map.java:1568) ~[?:?]
        at org.mitre.mpf.wfm.service.TiesDbService.addActionAssertion(TiesDbService.java:164) ~[classes/:?]
        at org.mitre.mpf.wfm.service.TiesDbService.addAssertions(TiesDbService.java:131) ~[classes/:?]
        at org.mitre.mpf.wfm.camel.JobCompleteProcessorImpl.wfmProcess(JobCompleteProcessorImpl.java:183) ~[classes/:?]
        at org.mitre.mpf.wfm.camel.WfmProcessor.process(WfmProcessor.java:58) ~[classes/:?]
```

When I run this job:

```json
{
  "callbackMethod": "POST",
  "callbackURL": "http://localhost:7777",
  "jobProperties": {
    "TIES_DB_URL" : "http://localhost:8888",
    "CUDA_DEVICE_ID" : "-1",
    "FEED_FORWARD_EXCLUDE_BEHAVIOR" : "DROP",
    "OUTPUT_MERGE_WITH_PREVIOUS_TASK" : "FALSE"
  },
  "media": [
    {
      "mediaUri": "file:///home/mpf/git/openmpf-projects/openmpf/trunk/install/share/remote-media/lp-ferrari-texas-shortened.mp4",
      "metadata": {},
      "properties": {}
    }
  ],
  "pipelineName": "OCV YOLO PERSON VEHICLE COLOR WITH SS MOTION PIPELINE",
  "priority": 0
}
```

It's related to this code:
```
                    String trackType;
                    if (tracks.isEmpty()) {
                        trackType = inProgressBatchJobs.getNoTracksType(
                                jobId, media.getId(), taskIndex, actionIndex);
                    }
```

`trackType` is null for the OCV YOLO stage. A "noTracks" entry doesn't exist for it. While that stage did return tracks from the component, they were later discarded by the WFM:

```
2021-06-18 16:48:54,124 WARN [Camel (camelContext) thread #13 - JmsConsumer[MPF.COMPLETED_DETECTIONS]] o.m.m.w.c.o.d.MovingTrackLabelProcessor - Job 1126, task 1, action 0 originally had 12 tracks. MOVING_TRACKS_ONLY was true so 12 tracks were dropped because they were not in motion.
```

In retrospect, there are a variety of ways the WFM can discard tracks:
- detection confidence too low
- track not moving
- track not long enough
- TBD: zero-sized detection

Long story short, you shouldn't count tracks in the `DetectionResponseProcessor`.

Maybe a simple solution is just to rename `_noTracksEntries` to `_trackTypes` and create an entry regardless of the number of tracks in the `DetectionResponseProcessor`.
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/TiesDbService.java, line 69 at r2](https://reviewable.io/reviews/openmpf/openmpf/1343#-McBNKU54ojL3-DgjA3y:-McQkKNP3VZceCKqjRPp:bb6ywmx) ([raw file](https://github.com/openmpf/openmpf/blob/f2a07f63186a14790af8d9232af1ebc0ca87607a/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/TiesDbService.java#L69)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please add a comment to this file linking to https://github.com/Noblis/ties-lib and explaining what an `assertion` is in this context since that terminology is overloaded and rather confusing.

> Refer to https://github.com/Noblis/ties-lib for more information on the Triage Import Export Schema (TIES). For each piece of media, we create one or more TIES "supplementalDescription (Data Object)" entries in the database, one for each analytic (algorithm) run on the media. In general, a "supplementalDescription" is a kind of TIES "assertion", which is used to represent metadata about the media object. In our case it represents the detection and track information in the OpenMPF JSON output object.
</blockquote></details>

LGTM
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/TiesDbService.java, line 210 at r2](https://reviewable.io/reviews/openmpf/openmpf/1343#-McBRF-49ybSViByEpMy:-McBPz6_-_l-sPwV8ZWz:b-47vln6) ([raw file](https://github.com/openmpf/openmpf/blob/f2a07f63186a14790af8d9232af1ebc0ca87607a/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/TiesDbService.java#L210)):*
> ```Java
>     private static String getHostName() {
>         return Objects.requireNonNullElseGet(
>                 System.getenv("NODE_HOSTNAME"),
> ```

You mentioned updating `SWARM.md` in openmpf-docker to inform users that in a Swarm deployment `NODE_HOSTNAME` can be set to `{{.Node.Hostname}}`.
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/TiesDbService.java, line 276 at r3](https://reviewable.io/reviews/openmpf/openmpf/1343#-McQihzS5Wqj_PE4VsRU:-McQihzS5Wqj_PE4Vs [...]

2021-06-21 15:18 UTC, brosenberg42 reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1343)* status: 19 of 26 files reviewed, 6 unresolved discussions (waiting on @brosenberg42 and @jrobble)

*[a discussion](https://reviewable.io/reviews/openmpf/openmpf/1343#-McW1Kuk9LgTOQKLIxRJ:-Mcj8i_Y-ddjxhSrOocN:b-896fix) (no related file):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Looking at the log output, I can't tell the difference between POST attempts for the different analytics:

```
2021-06-18 17:19:59,716 INFO [pool-5-thread-6] o.m.m.w.u.CallbackUtils - Starting POST callback to "http://localhost:8888/api/db/supplementals?sha256Hash=30068ed408eecb21f29c57b8b76954d0a3dc8b0703cfb7be8bca8214692be3f5".
2021-06-18 17:19:59,717 ERROR [pool-4-thread-1] o.m.m.w.u.CallbackUtils - Failed to issue POST callback to 'http://localhost:8888/api/db/supplementals?sha256Hash=30068ed408eecb21f29c57b8b76954d0a3dc8b0703cfb7be8bca8214692be3f5'. There are 1 attempts remaining and the next attempt will begin in 30000 ms.
```
```
2021-06-18 17:19:59,718 INFO [pool-5-thread-6] o.m.m.w.u.CallbackUtils - Starting POST callback to "http://localhost:8888/api/db/supplementals?sha256Hash=30068ed408eecb21f29c57b8b76954d0a3dc8b0703cfb7be8bca8214692be3f5".
2021-06-18 17:19:59,718 ERROR [pool-4-thread-1] o.m.m.w.u.CallbackUtils - Failed to issue POST callback to 'http://localhost:8888/api/db/supplementals?sha256Hash=30068ed408eecb21f29c57b8b76954d0a3dc8b0703cfb7be8bca8214692be3f5'. There are 1 attempts remaining and the next attempt will begin in 30000 ms.
```

Basically, anything that posts to the same media would have the same log line. Eventually, having job ids in these lines will help. I'm wondering if we want to consider differentiating between them more by adding the algorithm name to the log line.

I'm just thinking about the case where one succeeds and the other doesn't. How will the user know which is which? Maybe we should just ask them if they care or not. 
</blockquote></details>

Done.

---
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/DetectionResponseProcessor.java, line 185 at r4](https://reviewable.io/reviews/openmpf/openmpf/1343#-McVmHCdDt29_l-ePeeq:-Mcj1pfv1iA0yD-hwO-E:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/319dd2350ac4f356c531e0c69f1d9e6e3518f7b7/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/DetectionResponseProcessor.java#L185)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I'm getting a NullPointerException:

```
java.lang.NullPointerException: null
        at java.util.Objects.requireNonNull(Objects.java:221) ~[?:?]
        at java.util.ImmutableCollections$MapN.<init>(ImmutableCollections.java:827) ~[?:?]
        at java.util.Map.of(Map.java:1568) ~[?:?]
        at org.mitre.mpf.wfm.service.TiesDbService.addActionAssertion(TiesDbService.java:164) ~[classes/:?]
        at org.mitre.mpf.wfm.service.TiesDbService.addAssertions(TiesDbService.java:131) ~[classes/:?]
        at org.mitre.mpf.wfm.camel.JobCompleteProcessorImpl.wfmProcess(JobCompleteProcessorImpl.java:183) ~[classes/:?]
        at org.mitre.mpf.wfm.camel.WfmProcessor.process(WfmProcessor.java:58) ~[classes/:?]
```

When I run this job:

```json
{
  "callbackMethod": "POST",
  "callbackURL": "http://localhost:7777",
  "jobProperties": {
    "TIES_DB_URL" : "http://localhost:8888",
    "CUDA_DEVICE_ID" : "-1",
    "FEED_FORWARD_EXCLUDE_BEHAVIOR" : "DROP",
    "OUTPUT_MERGE_WITH_PREVIOUS_TASK" : "FALSE"
  },
  "media": [
    {
      "mediaUri": "file:///home/mpf/git/openmpf-projects/openmpf/trunk/install/share/remote-media/lp-ferrari-texas-shortened.mp4",
      "metadata": {},
      "properties": {}
    }
  ],
  "pipelineName": "OCV YOLO PERSON VEHICLE COLOR WITH SS MOTION PIPELINE",
  "priority": 0
}
```

It's related to this code:
```
                    String trackType;
                    if (tracks.isEmpty()) {
                        trackType = inProgressBatchJobs.getNoTracksType(
                                jobId, media.getId(), taskIndex, actionIndex);
                    }
```

`trackType` is null for the OCV YOLO stage. A "noTracks" entry doesn't exist for it. While that stage did return tracks from the component, they were later discarded by the WFM:

```
2021-06-18 16:48:54,124 WARN [Camel (camelContext) thread #13 - JmsConsumer[MPF.COMPLETED_DETECTIONS]] o.m.m.w.c.o.d.MovingTrackLabelProcessor - Job 1126, task 1, action 0 originally had 12 tracks. MOVING_TRACKS_ONLY was true so 12 tracks were dropped because they were not in motion.
```

In retrospect, there are a variety of ways the WFM can discard tracks:
- detection confidence too low
- track not moving
- track not long enough
- TBD: zero-sized detection

Long story short, you shouldn't count tracks in the `DetectionResponseProcessor`.

Maybe a simple solution is just to rename `_noTracksEntries` to `_trackTypes` and create an entry regardless of the number of tracks in the `DetectionResponseProcessor`.



</blockquote></details>

Done.
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/TiesDbService.java, line 210 at r2](https://reviewable.io/reviews/openmpf/openmpf/1343#-McBRF-49ybSViByEpMy:-Mcj8hMN3b7K7KiAYxC0:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/f2a07f63186a14790af8d9232af1ebc0ca87607a/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/TiesDbService.java#L210)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

You mentioned updating `SWARM.md` in openmpf-docker to inform users that in a Swarm deployment `NODE_HOSTNAME` can be set to `{{.Node.Hostname}}`.
</blockquote></details>

Done.
___
*[trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/service/TestTiesDbService.java, line 153 at r3](https://reviewable.io/reviews/openmpf/openmpf/1343#-McQtob-6geUq8bydxOM:-Mciy9cN9SMykFD-3CIj:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/b9aa3b207538deed79403d53186fa8b4a967651e/trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/service/TestTiesDbService.java#L153)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I see that you're intentionally not returning a "TIES_DB_URL" value for media2 action2. That wasn't clear until I started debugging. Please leave a comment explaining that. It was a little confusing how you're only verifying three`executeRequest()` calls since that is not a typical use case.
</blockquote></details>

Done.
___
*[trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/service/TestTiesDbService.java, line 256 at r3](https://reviewable.io/reviews/openmpf/openmpf/1343#-McQudgREVlTgai9pM3F:-MciyHgt1Y2fVlGaVUKP:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/b9aa3b207538deed79403d53186fa8b4a967651e/trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/service/TestTiesDbService.java#L256)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

For clarity, please state that a warning message is logged for the bad action, but otherwise the job completes successfully.
</blockquote></details>

Done.
___
*[trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/service/TestTiesDbService.java, line 339 at r3](https://reviewable.io/reviews/openmpf/openmpf/1343#-McQvzP72Blba03LQ0uO:-MciyK1G0Uz2cyGHlu_Y:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/b9aa3b207538deed79403d53186fa8b4a967651e/trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/service/TestTiesDbService.java#L339)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

For clarity, please state that a warning message is logged for the bad action, but otherwise the job completes successfully.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-22 19:49 UTC, jrobble commented
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/DetectionResponseProcessor.java, line 185 at r4](https://reviewable.io/reviews/openmpf/openmpf/1343#-McVmHCdDt29_l-ePeeq:-McpDbiA-2T-Zzi04edY:biuiz2i) ([raw file](https://github.com/openmpf/openmpf/blob/319dd2350ac4f356c531e0c69f1d9e6e3518f7b7/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/DetectionResponseProcessor.java#L185)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I ran the same job posted above and encountered another NPE. 

This time the issue is related to the final OCV DNN task. Since all of the OCV YOLO tracks were dropped, no sub-job request messages were generated for the final task, so the `DetectionResponseProcessor` was never invoked for that task, which results in never calling `recordTrackType()` for that task. Later, in `TiesDbService`, the track type is null here:

```
        var dataObject = Map.of(
                "algorithm", action.getAlgorithm(),
                "outputType", trackCountEntry.getTrackType(),
```

That results in the NPE.


<!-- Sent from Reviewable.io -->

2021-06-22 20:30 UTC, jrobble requested changes
> Reviewed 7 of 7 files at r5.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1343)* status: all files reviewed, 2 unresolved discussions (waiting on @brosenberg42)

___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/DetectionResponseProcessor.java, line 185 at r4](https://reviewable.io/reviews/openmpf/openmpf/1343#-McVmHCdDt29_l-ePeeq:-McpPbP49BMylMCAE7VT:b-nm5gqx) ([raw file](https://github.com/openmpf/openmpf/blob/319dd2350ac4f356c531e0c69f1d9e6e3518f7b7/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/DetectionResponseProcessor.java#L185)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I ran the same job posted above and encountered another NPE. 

This time the issue is related to the final OCV DNN task. Since all of the OCV YOLO tracks were dropped, no sub-job request messages were generated for the final task, so the `DetectionResponseProcessor` was never invoked for that task, which results in never calling `recordTrackType()` for that task. Later, in `TiesDbService`, the track type is null here:

```
        var dataObject = Map.of(
                "algorithm", action.getAlgorithm(),
                "outputType", trackCountEntry.getTrackType(),
```

That results in the NPE.
</blockquote></details>

FYI. It turns out we send a markup request even if there's no markup work to be performed, so we don't get an NPE because of that.
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/TiesDbService.java, line 264 at r5](https://reviewable.io/reviews/openmpf/openmpf/1343#-McpN-lO8dy1hqIpvDBz:-McpN-lO8dy1hqIpvDC-:bw4k2gj) ([raw file](https://github.com/openmpf/openmpf/blob/40a8a4b05532770cb05b93fdeebb9f040f3705fe/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/TiesDbService.java#L264)):*
> ```Java
>         }
>         var warningMessage = String.format(
>                 "[Job %s] Sending HTTP POST to TiesDb (%s) for %s failed due to: %s",
> ```

In the starter line we mention the action name:

```
2021-06-22 16:16:26,576 INFO [Camel (camelContext) thread #39 - JmsConsumer[MPF.JOB_ROUTER]] o.m.m.w.s.TiesDbService - [Job 1165] Posting assertion to TiesDb for the CUSTOM SUBSENSE MOTION DETECTION PREPROCESSOR LENIENT ACTION action.
```

In the failure line we mention the algorithm name. I think we should be consistent and use the action name for both.


<!-- Sent from Reviewable.io -->

2021-06-23 19:47 UTC, brosenberg42 reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1343)* status: 18 of 28 files reviewed, 2 unresolved discussions (waiting on @brosenberg42 and @jrobble)

___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/TiesDbService.java, line 264 at r5](https://reviewable.io/reviews/openmpf/openmpf/1343#-McpN-lO8dy1hqIpvDBz:-McuPQvk0VA0Xhww1WZu:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/40a8a4b05532770cb05b93fdeebb9f040f3705fe/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/TiesDbService.java#L264)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

In the starter line we mention the action name:

```
2021-06-22 16:16:26,576 INFO [Camel (camelContext) thread #39 - JmsConsumer[MPF.JOB_ROUTER]] o.m.m.w.s.TiesDbService - [Job 1165] Posting assertion to TiesDb for the CUSTOM SUBSENSE MOTION DETECTION PREPROCESSOR LENIENT ACTION action.
```

In the failure line we mention the algorithm name. I think we should be consistent and use the action name for both.

</blockquote></details>

Done.
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/DetectionResponseProcessor.java, line 185 at r4](https://reviewable.io/reviews/openmpf/openmpf/1343#-McVmHCdDt29_l-ePeeq:-McuPLyo-IzXmdy64ZyU:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/319dd2350ac4f356c531e0c69f1d9e6e3518f7b7/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/DetectionResponseProcessor.java#L185)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

FYI. It turns out we send a markup request even if there's no markup work to be performed, so we don't get an NPE because of that.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-24 22:22 UTC, jrobble requested changes
> Reviewed 10 of 10 files at r6.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1343)* status: all files reviewed, 3 unresolved discussions (waiting on @brosenberg42)

*[a discussion](https://reviewable.io/reviews/openmpf/openmpf/1343#-Md-5O9F8WR3ptJWCeeG:-Md-5O9F8WR3ptJWCeeH:b-8aguyr) (no related file):*
I ran this job:

```
{
  "callbackMethod": "POST",
  "callbackURL": "http://localhost:7777",
  "jobProperties": {
    "TIES_DB_URL" : "http://localhost:8888",
  },
  "media": [
    {
      "mediaUri": "file:///home/mpf/git/openmpf-projects/openmpf/trunk/install/share/remote-media/eng.png",
    }
  ],
  "pipelineName": "TESSERACT TEXT PIPELINE",
  "priority": 0
}
```

And that generated this POST:

```
{
  "informationType": "OpenMPF_TEXT",
  "assertionId": "3225baa964bfe21b323d09e208128409794335b2fab176fa707d72ab1cd8e11b",
  "dataObject": {
    "systemHostname": "openmpf-master",
    "sha256OutputHash": "82b0195a83bdb3ab6322d78ca7d09d710005bebc50d180cc039abe0fb057a27d",
    "outputType": "TEXT",
    "algorithm": "KEYWORDTAGGING",
    "processDate": "2021-06-24T18:12:26.309-04:00",
    "pipeline": "TESSERACT TEXT PIPELINE",
    "outputUri": "file:///home/mpf/git/openmpf-projects/openmpf/trunk/install/share/output-objects/1185/detection.json",
    "jobStatus": "COMPLETE",
    "jobId": 1185,
    "systemVersion": "6.2",
    "trackCount": 1
  },
  "system": "OpenMPF",
  "securityTag": "UNCLASSIFIED"
}
```

However, the JSON output object shows:

```
            "TRACKS MERGED": [
               {
                  "source": "+#CUSTOM TESSERACT IMAGE OCR (WITH AUTO-ORIENTATION) ACTION",
                  "algorithm": "TESSERACTOCR"
               }
            ],
            "TEXT": [
               {
                  "source": "+#CUSTOM TESSERACT IMAGE OCR (WITH AUTO-ORIENTATION) ACTION#CUSTOM OCR KEYWORD TAGGING (WITH FF REGION) ACTION",
                  "algorithm": "TESSERACTOCR",
                  "tracks": [
                     {
                        "id": "e96f48dd8905bd6253125d66dd865225edd3ccc00c14c7b2542be939f86ce002",
                        "startOffsetFrame": 0,
                        "stopOffsetFrame": 1,
                        "startOffsetTime": 0,
                        "stopOffsetTime": 0,
```

I believe that the user wants `TESSERACTOCR` in the POST, not `KEYWORDTAGGING`, because we're performing task merging. We got lucky here that the final stage generates `TEXT` and that just so happens to be the same as the prior stage it was merged with.

---
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/TiesDbService.java, line 131 at r6](https://reviewable.io/reviews/openmpf/openmpf/1343#-MczwS787abNmMz3kwus:-MczwS790gJE78h4EozH:b-21notp) ([raw file](https://github.com/openmpf/openmpf/blob/681ef29fa308b72515098120bfc0463c91c52e43/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/TiesDbService.java#L131)):*
> ```Java
>             String tiesDbUrl) {
> 
>         var dataObject = Map.ofEntries(
> ```

Lol. I see that we hit the 10 entry limit.
___
*[trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/service/TestTiesDbService.java, line 171 at r6](https://reviewable.io/reviews/openmpf/openmpf/1343#-MczqSiJ9WouLj4WGqqP:-MczqSiJ9WouLj4WGqqQ:bgesfhp) ([raw file](https://github.com/openmpf/openmpf/blob/681ef29fa308b72515098120bfc0463c91c52e43/trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/service/TestTiesDbService.java#L171)):*
> ```Java
>         result.join();
> 
>         // Only action1 is configured to use TiesDb.
> ```

Action 2 for media 1 also uses TiesDb. Please update this comment.


<!-- Sent from Reviewable.io -->

2021-06-25 13:32 UTC, brosenberg42 reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1343)* status: 26 of 28 files reviewed, 1 unresolved discussion (waiting on @jrobble)

*[a discussion](https://reviewable.io/reviews/openmpf/openmpf/1343#-Md-5O9F8WR3ptJWCeeG:-Md2MrQp8TU31IcuYF5L:b-896fix) (no related file):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I ran this job:

```
{
  "callbackMethod": "POST",
  "callbackURL": "http://localhost:7777",
  "jobProperties": {
    "TIES_DB_URL" : "http://localhost:8888",
  },
  "media": [
    {
      "mediaUri": "file:///home/mpf/git/openmpf-projects/openmpf/trunk/install/share/remote-media/eng.png",
    }
  ],
  "pipelineName": "TESSERACT TEXT PIPELINE",
  "priority": 0
}
```

And that generated this POST:

```
{
  "informationType": "OpenMPF_TEXT",
  "assertionId": "3225baa964bfe21b323d09e208128409794335b2fab176fa707d72ab1cd8e11b",
  "dataObject": {
    "systemHostname": "openmpf-master",
    "sha256OutputHash": "82b0195a83bdb3ab6322d78ca7d09d710005bebc50d180cc039abe0fb057a27d",
    "outputType": "TEXT",
    "algorithm": "KEYWORDTAGGING",
    "processDate": "2021-06-24T18:12:26.309-04:00",
    "pipeline": "TESSERACT TEXT PIPELINE",
    "outputUri": "file:///home/mpf/git/openmpf-projects/openmpf/trunk/install/share/output-objects/1185/detection.json",
    "jobStatus": "COMPLETE",
    "jobId": 1185,
    "systemVersion": "6.2",
    "trackCount": 1
  },
  "system": "OpenMPF",
  "securityTag": "UNCLASSIFIED"
}
```

However, the JSON output object shows:

```
            "TRACKS MERGED": [
               {
                  "source": "+#CUSTOM TESSERACT IMAGE OCR (WITH AUTO-ORIENTATION) ACTION",
                  "algorithm": "TESSERACTOCR"
               }
            ],
            "TEXT": [
               {
                  "source": "+#CUSTOM TESSERACT IMAGE OCR (WITH AUTO-ORIENTATION) ACTION#CUSTOM OCR KEYWORD TAGGING (WITH FF REGION) ACTION",
                  "algorithm": "TESSERACTOCR",
                  "tracks": [
                     {
                        "id": "e96f48dd8905bd6253125d66dd865225edd3ccc00c14c7b2542be939f86ce002",
                        "startOffsetFrame": 0,
                        "stopOffsetFrame": 1,
                        "startOffsetTime": 0,
                        "stopOffsetTime": 0,
```

I believe that the user wants `TESSERACTOCR` in the POST, not `KEYWORDTAGGING`, because we're performing task merging. We got lucky here that the final stage generates `TEXT` and that just so happens to be the same as the prior stage it was merged with.
</blockquote></details>

Done.

---


<!-- Sent from Reviewable.io -->

2021-06-25 16:53 UTC, jrobble requested changes
> Reviewed 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1343)* status: all files reviewed, 1 unresolved discussion (waiting on @brosenberg42)

*[a discussion](https://reviewable.io/reviews/openmpf/openmpf/1343#-Md33La-9lcG18PgwkhI:-Md33La-9lcG18PgwkhJ:b-nphzi0) (no related file):*
I just ran this job:

```
{
  "callbackMethod": "POST",
  "callbackURL": "http://localhost:7777",
  "jobProperties": {
    "TIES_DB_URL" : "http://localhost:8888",
    "CUDA_DEVICE_ID" : "-1",
    "OUTPUT_LAST_TASK_ONLY" : "TRUE"
  },
  "media": [
    {
      "mediaUri": "file:///home/mpf/git/openmpf-projects/openmpf/trunk/install/share/remote-media/lp-ferrari-texas-shortened.mp4",
      "metadata": {},
      "properties": {}
    }
  ],
  "pipelineName": "OCV YOLO PERSON VEHICLE COLOR WITH SS MOTION PIPELINE",
  "priority": 0
}
```

Remember that the non-moving tracks will be dropped during the OCV YOLO stage, so no sub-job requests get sent to the final stage. This results in the following JSON output object:

```
         "output": {
            "NO TRACKS": [
               {
                  "source": "+#CUSTOM SUBSENSE MOTION DETECTION PREPROCESSOR LENIENT ACTION#CUSTOM OCV YOLO 416 PERSON VEHICLE DETECTION (WITH AUTO-ORIENTATION) ACTION",
                  "algorithm": "OCVYOLO"
               },
               {
                  "source": "+#CUSTOM SUBSENSE MOTION DETECTION PREPROCESSOR LENIENT ACTION#CUSTOM OCV YOLO 416 PERSON VEHICLE DETECTION (WITH AUTO-ORIENTATION) ACTION#CUSTOM TENSORFLOW VEHICLE COLOR DETECTION (WITH FF REGION) ACTION",
                  "algorithm": "DNNCV"
               }
            ],
            "TRACKS SUPPRESSED": [
               {
                  "source": "+#CUSTOM SUBSENSE MOTION DETECTION PREPROCESSOR LENIENT ACTION",
                  "algorithm": "SUBSENSE"
               }
            ]
         }
```

No posts are made to TiesDb in this case. I don't think that's what the user wants. In general, I think they still want us to post NO_TRACKS regardless if sub-jobs are created for a stage or not.

---


<!-- Sent from Reviewable.io -->

2021-06-30 17:27 UTC, jrobble commented
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/TiesDbService.java, line 129 at r8](https://reviewable.io/reviews/openmpf/openmpf/1343#-MdSMEP9-8fu29jtS_Qb:-MdSMEP9-8fu29jtS_Qc:bwhcgwh) ([raw file](https://github.com/openmpf/openmpf/blob/f1381f857fa802d6028cb853dc8624dddb3abe55/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/TiesDbService.java#L129)):*
> ```Java
>                         jobPart.getTaskIndex(),
>                         jobPart.getActionIndex());
>                 var algoAndDetectionType = getAlgoAndTypeToUse(
> ```

The last task in the merge chain might have no tracks, and should be "NO TRACKS", but you're getting the track type from the first task in the merge chain, which might have tracks.

I ran this job:


```
{
  "algorithmProperties" : {
    "OCVYOLO" : {
      "CLASS_WHITELIST_FILE" : ""
    },
    "DNNCV" : {
      "CLASS_WHITELIST_FILE" : "/home/mpf/Desktop/TMP/dummy-whitelist.txt"
    }
  },
  "jobProperties": {
    "TIES_DB_URL" : "http://localhost:8888",
    "CUDA_DEVICE_ID" : "-1",
    "FEED_FORWARD_EXCLUDE_BEHAVIOR" : "DROP",
    "MOVING_TRACKS_ONLY" : "FALSE"
  },
  "media": [
    {
      "mediaUri": "file:///home/mpf/git/openmpf-projects/openmpf/trunk/install/share/remote-media/pp_03.mp4",
      "metadata": {},
      "properties": {}
    }
  ],
  "pipelineName": "OCV YOLO PERSON VEHICLE COLOR WITH SS MOTION PIPELINE",
  "priority": 0
}
```

`dummy-whitelist.txt` just contains the word "dummy".

I saw this POST:

```
{
  "assertionId": "770fb63cee456b4bd5388bd56dd38a2256032354f03cdde5272e37410ca3aa0f",
  "dataObject": {
    "outputUri": "file:///home/mpf/git/openmpf-projects/openmpf/trunk/install/share/output-objects/1260/detection.json",
    "jobStatus": "COMPLETE",
    "jobId": 1260,
    "systemVersion": "6.2",
    "trackCount": 0,
    "systemHostname": "openmpf-master",
    "sha256OutputHash": "482f3050d3a7a1f867d9df016c34a2c4c1ba819239f20d995ad570267018ff00",
    "outputType": "CLASS",
    "algorithm": "OCVYOLO",
    "processDate": "2021-06-30T13:15:24.429-04:00",
    "pipeline": "OCV YOLO PERSON VEHICLE COLOR WITH SS MOTION PIPELINE"
  },
  "system": "OpenMPF",
  "securityTag": "UNCLASSIFIED",
  "informationType": "OpenMPF CLASS"
}
```

Notice that `trackCount=0` while `outputType=CLASS`.

The JSON shows:

```
            "NO TRACKS": [
               {
                  "source": "+#CUSTOM SUBSENSE MOTION DETECTION PREPROCESSOR LENIENT ACTION#CUSTOM OCV YOLO 416 PERSON VEHICLE DETECTION (WITH AUTO-ORIENTATION) ACTION#CUSTOM TENSORFLOW VEHICLE COLOR DETECTION (WITH FF REGION) ACTION",
                  "algorithm": "DNNCV"
               }
            ],
            "TRACKS MERGED": [
               {
                  "source": "+#CUSTOM SUBSENSE MOTION DETECTION PREPROCESSOR LENIENT ACTION#CUSTOM OCV YOLO 416 PERSON VEHICLE DETECTION (WITH AUTO-ORIENTATION) ACTION",
                  "algorithm": "OCVYOLO"
               }
            ],
            "MOTION": [
               {
                  "source": "+#CUSTOM SUBSENSE MOTION DETECTION PREPROCESSOR LENIENT ACTION",
                  "algorithm": "SUBSENSE",
                  "tracks": [ ... ]
```


<!-- Sent from Reviewable.io -->

2021-06-30 20:32 UTC, jrobble requested changes
> Reviewed 6 of 6 files at r8.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1343)* status: all files reviewed, 3 unresolved discussions (waiting on @brosenberg42)

*[a discussion](https://reviewable.io/reviews/openmpf/openmpf/1343#-MdTbTB023nk0DE-H80K:-MdTbTB12qKonTpXbryH:bvjhcyy) (no related file):*
As discussed elsewhere, this is the current behavior:

```
            "NO TRACKS": [
               {
                  "source": "+#CUSTOM SUBSENSE MOTION DETECTION PREPROCESSOR LENIENT ACTION#CUSTOM OCV YOLO 416 PERSON VEHICLE DETECTION (WITH AUTO-ORIENTATION) ACTION#CUSTOM TENSORFLOW VEHICLE COLOR DETECTION (WITH FF REGION) ACTION",
                  "algorithm": "DNNCV"
               }
            ],
            "TRACKS MERGED": [
               {
                  "source": "+#CUSTOM SUBSENSE MOTION DETECTION PREPROCESSOR LENIENT ACTION#CUSTOM OCV YOLO 416 PERSON VEHICLE DETECTION (WITH AUTO-ORIENTATION) ACTION",
                  "algorithm": "OCVYOLO"
               }
            ],
            "MOTION": [
               {
                  "source": "+#CUSTOM SUBSENSE MOTION DETECTION PREPROCESSOR LENIENT ACTION",
                  "algorithm": "SUBSENSE",
                  "tracks": [ ... ]
               }
            ],
```

Please change the first part to OCVYOLO:

```
            "NO TRACKS": [
               {
                  "source": "+#CUSTOM SUBSENSE MOTION DETECTION PREPROCESSOR LENIENT ACTION#CUSTOM OCV YOLO 416 PERSON VEHICLE DETECTION (WITH AUTO-ORIENTATION) ACTION#CUSTOM TENSORFLOW VEHICLE COLOR DETECTION (WITH FF REGION) ACTION",
                  "algorithm": "OCVYOLO"
               }
            ],
```

---
___
*[trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/service/TestTiesDbService.java, line 228 at r8](https://reviewable.io/reviews/openmpf/openmpf/1343#-MdTa2pQ4-nzw2_JKSyZ:-MdTa2pT0jcZ2bvyBz2-:baheceb) ([raw file](https://github.com/openmpf/openmpf/blob/f1381f857fa802d6028cb853dc8624dddb3abe55/trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/service/TestTiesDbService.java#L228)):*
> ```Java
> 
>     @Test
>     public void testTaskMerging() {
> ```

Good tests. Consider:

- A test that runs a 3-stage pipeline. The first task is not merged but the last task is merged into the middle one. (You currently have a test where the second task is merged with the first and the last is not merged.)

- A test for [this case](https://github.com/openmpf/openmpf/pull/1343#issuecomment-871594092) where one of the preceding tasks in the chain has tracks but the last one doesn't.

- A test like the one above, but the preceding tasks in the chain have no tracks.


<!-- Sent from Reviewable.io -->

2021-07-02 17:18 UTC, brosenberg42 reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1343)* status: 25 of 28 files reviewed, 3 unresolved discussions (waiting on @jrobble)

*[a discussion](https://reviewable.io/reviews/openmpf/openmpf/1343#-MdTbTB023nk0DE-H80K:-MdcDg2SAf9bPybDKony:b-896fix) (no related file):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

As discussed elsewhere, this is the current behavior:

```
            "NO TRACKS": [
               {
                  "source": "+#CUSTOM SUBSENSE MOTION DETECTION PREPROCESSOR LENIENT ACTION#CUSTOM OCV YOLO 416 PERSON VEHICLE DETECTION (WITH AUTO-ORIENTATION) ACTION#CUSTOM TENSORFLOW VEHICLE COLOR DETECTION (WITH FF REGION) ACTION",
                  "algorithm": "DNNCV"
               }
            ],
            "TRACKS MERGED": [
               {
                  "source": "+#CUSTOM SUBSENSE MOTION DETECTION PREPROCESSOR LENIENT ACTION#CUSTOM OCV YOLO 416 PERSON VEHICLE DETECTION (WITH AUTO-ORIENTATION) ACTION",
                  "algorithm": "OCVYOLO"
               }
            ],
            "MOTION": [
               {
                  "source": "+#CUSTOM SUBSENSE MOTION DETECTION PREPROCESSOR LENIENT ACTION",
                  "algorithm": "SUBSENSE",
                  "tracks": [ ... ]
               }
            ],
```

Please change the first part to OCVYOLO:

```
            "NO TRACKS": [
               {
                  "source": "+#CUSTOM SUBSENSE MOTION DETECTION PREPROCESSOR LENIENT ACTION#CUSTOM OCV YOLO 416 PERSON VEHICLE DETECTION (WITH AUTO-ORIENTATION) ACTION#CUSTOM TENSORFLOW VEHICLE COLOR DETECTION (WITH FF REGION) ACTION",
                  "algorithm": "OCVYOLO"
               }
            ],
```
</blockquote></details>

Done.

---
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/TiesDbService.java, line 129 at r8](https://reviewable.io/reviews/openmpf/openmpf/1343#-MdSMEP9-8fu29jtS_Qb:-MdcDdXV4yfRSYB34w9n:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/f1381f857fa802d6028cb853dc8624dddb3abe55/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/TiesDbService.java#L129)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

The last task in the merge chain might have no tracks, and should be "NO TRACKS", but you're getting the track type from the first task in the merge chain, which might have tracks.

I ran this job:


```
{
  "algorithmProperties" : {
    "OCVYOLO" : {
      "CLASS_WHITELIST_FILE" : ""
    },
    "DNNCV" : {
      "CLASS_WHITELIST_FILE" : "/home/mpf/Desktop/TMP/dummy-whitelist.txt"
    }
  },
  "jobProperties": {
    "TIES_DB_URL" : "http://localhost:8888",
    "CUDA_DEVICE_ID" : "-1",
    "FEED_FORWARD_EXCLUDE_BEHAVIOR" : "DROP",
    "MOVING_TRACKS_ONLY" : "FALSE"
  },
  "media": [
    {
      "mediaUri": "file:///home/mpf/git/openmpf-projects/openmpf/trunk/install/share/remote-media/pp_03.mp4",
      "metadata": {},
      "properties": {}
    }
  ],
  "pipelineName": "OCV YOLO PERSON VEHICLE COLOR WITH SS MOTION PIPELINE",
  "priority": 0
}
```

`dummy-whitelist.txt` just contains the word "dummy".

I saw this POST:

```
{
  "assertionId": "770fb63cee456b4bd5388bd56dd38a2256032354f03cdde5272e37410ca3aa0f",
  "dataObject": {
    "outputUri": "file:///home/mpf/git/openmpf-projects/openmpf/trunk/install/share/output-objects/1260/detection.json",
    "jobStatus": "COMPLETE",
    "jobId": 1260,
    "systemVersion": "6.2",
    "trackCount": 0,
    "systemHostname": "openmpf-master",
    "sha256OutputHash": "482f3050d3a7a1f867d9df016c34a2c4c1ba819239f20d995ad570267018ff00",
    "outputType": "CLASS",
    "algorithm": "OCVYOLO",
    "processDate": "2021-06-30T13:15:24.429-04:00",
    "pipeline": "OCV YOLO PERSON VEHICLE COLOR WITH SS MOTION PIPELINE"
  },
  "system": "OpenMPF",
  "securityTag": "UNCLASSIFIED",
  "informationType": "OpenMPF CLASS"
}
```

Notice that `trackCount=0` while `outputType=CLASS`.

The JSON shows:

```
            "NO TRACKS": [
               {
                  "source": "+#CUSTOM SUBSENSE MOTION DETECTION PREPROCESSOR LENIENT ACTION#CUSTOM OCV YOLO 416 PERSON VEHICLE DETECTION (WITH AUTO-ORIENTATION) ACTION#CUSTOM TENSORFLOW VEHICLE COLOR DETECTION (WITH FF REGION) ACTION",
                  "algorithm": "DNNCV"
               }
            ],
            "TRACKS MERGED": [
               {
                  "source": "+#CUSTOM SUBSENSE MOTION DETECTION PREPROCESSOR LENIENT ACTION#CUSTOM OCV YOLO 416 PERSON VEHICLE DETECTION (WITH AUTO-ORIENTATION) ACTION",
                  "algorithm": "OCVYOLO"
               }
            ],
            "MOTION": [
               {
                  "source": "+#CUSTOM SUBSENSE MOTION DETECTION PREPROCESSOR LENIENT ACTION",
                  "algorithm": "SUBSENSE",
                  "tracks": [ ... ]
```

</blockquote></details>

Done.
___
*[trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/service/TestTiesDbService.java, line 228 at r8](https://reviewable.io/reviews/openmpf/openmpf/1343#-MdTa2pQ4-nzw2_JKSyZ:-MdcDeFqA43hqMMWZwBJ:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/f1381f857fa802d6028cb853dc8624dddb3abe55/trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/service/TestTiesDbService.java#L228)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Good tests. Consider:

- A test that runs a 3-stage pipeline. The first task is not merged but the last task is merged into the middle one. (You currently have a test where the second task is merged with the first and the last is not merged.)

- A test for [this case](https://github.com/openmpf/openmpf/pull/1343#issuecomment-871594092) where one of the preceding tasks in the chain has tracks but the last one doesn't.

- A test like the one above, but the preceding tasks in the chain have no tracks.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-02 19:11 UTC, jrobble approved these changes
> Reviewed 3 of 3 files at r9.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1343)* status: all files reviewed, 1 unresolved discussion (waiting on @brosenberg42)

___
*[trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/service/TestTiesDbService.java, line 238 at r9](https://reviewable.io/reviews/openmpf/openmpf/1343#-Mdca4SA5KvGwtanIfGn:-Mdca4SA5KvGwtanIfGo:b2a0lzk) ([raw file](https://github.com/openmpf/openmpf/blob/fe3b1c9f434948ce71542bbea30b95f9d46170be/trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/service/TestTiesDbService.java#L238)):*
> ```Java
> 
>     @Test
>     public void testTaskMergingFirstTaskNoTracks() {
> ```

I can't think of a real-life example where it's possible for the first task to generate no tracks and the second to generate tracks because of how we generate segments, but it's fine to have the test anyway.

I probably wasn't clear in my other comment. I was thinking of something like:

```
    @Test
    public void testTaskMergingNoTracks() {
        testTwoStageTrackMerging("NO TRACKS", 0, 0);
    }
```

Consider adding that test. It passes.


<!-- Sent from Reviewable.io -->

2021-07-06 13:53 UTC, merged