Improve job status reporting
openmpf/openmpf pull request #1364
Opened 2021-07-06 17:57 UTC by brosenberg42

**Issues:**
- https://github.com/openmpf/openmpf/issues/1151
- https://github.com/openmpf/openmpf/issues/1349

2021-07-12 21:14 UTC, jrobble requested changes
> Reviewed 29 of 29 files at r1.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1364)* status: all files reviewed, 11 unresolved discussions (waiting on @brosenberg42)

*[a discussion](https://reviewable.io/reviews/openmpf/openmpf/1364#-Me6EeW_7zV4rW6Dk8ew:-Me6EeW_7zV4rW6Dk8ex:b-m4o3k3) (no related file):*
A job will appear as `COMPLETE` while TiesDb post / callback attempts are still going on in the background. Attempting to resubmit a job in this state will result in an exception and UI popup with the message:

> Failed to resubmit the job with id '1285'. Job with id 1285 already exists.

This is confusing to an end user, who doesn't know what's going on in the background. Once this happens the UI will stay as `RESUBMITTING` until the UI is refreshed.

I think we need some indication in the UI that there is still something going on. Minimally, disable the Resubmit button, but that alone might be a little confusing. Maybe change the tooltip / hint popover to say "Callbacks in progress" or something.

---

Also, the job will stay in `RESUBMITTING` if the media doesn't exist when you try to resubmit.

---
*[a discussion](https://reviewable.io/reviews/openmpf/openmpf/1364#-Me7vpJM9kw5JYnSquiJ:-Me7vpJN-16gh8zdonVH:b-yxb2oq) (no related file):*
In `DefaultJobErrorHandler.java` we have:

```
log.warn("An error was encountered while processing Job #{}. The Job will be marked as {}.", jobId, BatchJobStatusType.ERROR, throwable);
```

First, I think that should be `log.error()`. Second, where is the job status actually set to `ERROR` in response to this? I only see it set to `ERROR` in two places, and it's not clear that they are related to that message.

---
*[a discussion](https://reviewable.io/reviews/openmpf/openmpf/1364#-Me81918-c4kH1K67Y5a:-Me81918-c4kH1K67Y5b:banhpvt) (no related file):*
I put together this state machine diagram:

![Job Status State Machine.png](https://files.reviewableusercontent.io/images/reviewable/1039601/0fJrd1aYEviqGSh6Vf05Iing/Job%20Status%20State%20Machine.png)

Primarily, my concern is that we might accidentally transition to an improper state, like `COMPLETE` or `CANCELLED` to `IN_PROGRESS_WARNINGS` (see other comment). My secondary concern is that even if there aren't many situations where this can happen now, we should protect ourselves from it happening in the future as the WFM gets more complex.

I think we should centralize the logic that validates the transitions between states. I like `JobStatusCalculator.completionStatus()`. I would feel more confident if we had something like that for non-terminal states. Maybe something like:

```
BatchJobStatusType  JobStatusCalculator.validateNextStatus(BatchJobStatusType initialStatus, BatchJobStatusType nextStatus)
```

- If status transition is invalid then log an error and return the initial status.
- This isn't intended to hide bugs in the code. For example, if trying to go from `COMPLETE` to `IN_PROGRESS_WARNINGS` we could return `COMPLETE_WITH_WARNINGS`, but that bug should really be handled in `InProgressBatchJobService.addWarning()` instead. We should treat situations like this as an invalid status transition and log an error.
- In many cases we can't transition out of a terminal status to something else, so return the initial terminal status. For example, if we're in an `ERROR` state we should never go to `COMPLETE_WITH_ERRORS`. Similarly, `CANCELLED` should never change to anything else, except `ERROR`. Everything should be allowed to transition to `ERROR`.

In most cases this should just be a safety net. I'm not asking you to change much of the existing code.

---
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessorImpl.java, line 160 at r1](https://reviewable.io/reviews/openmpf/openmpf/1364#-MeRWKZz9w6iX9jBeEnK:-MeRWKZz9w6iX9jBeEnL:bnct2ox) ([raw file](https://github.com/openmpf/openmpf/blob/d11895adec3f7727d27a60f71aa6930749a43687/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessorImpl.java#L160)):*
In `WfmSplitter` we have:

```
            log.error(String.format("Failed to complete the split operation for Job %s due to an exception.", jobId),
                      exception);
            inProgressJobs.setJobStatus(jobId, BatchJobStatusType.ERROR);
```

We should be adding an error message with the exception there.

As stated in the task:

> When the job status is `ERROR`, the JSON output object does not have any messages in the errors field. We should ensure that a meaningful error message is added whenever we set the job status to `ERROR`.
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessorImpl.java, line 168 at r1](https://reviewable.io/reviews/openmpf/openmpf/1364#-Me6Df7f43DOJ0c5LQsc:-Me6Df7f43DOJ0c5LQsd:b-drdyld) ([raw file](https://github.com/openmpf/openmpf/blob/d11895adec3f7727d27a60f71aa6930749a43687/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessorImpl.java#L168)):*
> ```Java
>             jobRequest.setJob(jsonUtils.serialize(job));
>             jobRequestDao.persist(jobRequest);
>             jobStatusBroadcaster.broadcast(jobId, 100, BatchJobStatusType.COMPLETE);
> ```

Submitting a Sphinx job with an image will result in first transitioning to `COMPLETE` before `COMPLETE_WITH_ERRORS`. While `COMPLETE` is shown in red, I think we should transition to the actual terminal status,`COMPLETE_WITH_ERRORS`, directly.

While debugging I confirmed that at this point in the code `jobStatus` is already set to `COMPLETE_WITH_ERRORS` so we should just use that. Doing so will ensure that what's in the UI, `inProgressBatchJobs`, and the DB is all the same.

If we do this, I think we can replace `setJobStatusNoBroadcast()` here with `setJobStatus()`:
```
inProgressBatchJobs.setJobStatusNoBroadcast(jobId, jobStatus.getValue());
```

In general, I'm wondering if we really need `setJobStatusNoBroadcast()` to be a separate public method or if we can just add the behavior to `setJobStatus()`.

---

Also, a few lines above we have `jobStatus.setValue(BatchJobStatusType.ERROR)`. We don't want to change the status back to `COMPLETE`.
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/artifactextraction/ArtifactExtractionProcessor.java, line 190 at r1](https://reviewable.io/reviews/openmpf/openmpf/1364#-MeRKgwI-YSrzTLc3JwA:-MeRKgwJ98UnwQeTfF7w:bbq4g70) ([raw file](https://github.com/openmpf/openmpf/blob/d11895adec3f7727d27a60f71aa6930749a43687/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/artifactextraction/ArtifactExtractionProcessor.java#L190)):*
> ```Java
>         var missingFrameString = createMissingFramesString(tracks, request)
>                 .map(err -> "Error extracting artifact(s). " + err)
>                 .orElseGet(() -> "Artifact extraction failed to due " + e);
> ```

I think you mean `failed due to: " + e);`
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/InProgressBatchJobsService.java, line 227 at r1](https://reviewable.io/reviews/openmpf/openmpf/1364#-Me6onKJ9jVL8183LnYg:-Me6onKK0m6fwY8y6LvJ:b-pykofb) ([raw file](https://github.com/openmpf/openmpf/blob/d11895adec3f7727d27a60f71aa6930749a43687/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/InProgressBatchJobsService.java#L227)):*
> ```Java
>         var job = getJobImpl(jobId);
>         job.addWarning(mediaId, IssueSources.toString(source), codeString, message);
>         if (job.getStatus() != BatchJobStatusType.IN_PROGRESS_ERRORS) {
> ```

It's not always appropriate to transition to an `IN_PROGRESS` state here.

Looking at this code:

```
        JobStatusCalculator.checkErrorMessages(jsonOutputObject, jobStatus);

        return storageService.store(jsonOutputObject, jobStatus, outputSha); // this may update the job status
```

That first line can set `jobStatus` to `COMPLETE`. `StorageService.store(JsonOutputObject ...)` can call `addJobWarning() [...]

2021-07-19 16:34 UTC, brosenberg42 reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1364)* status: 20 of 49 files reviewed, 10 unresolved discussions (waiting on @brosenberg42 and @jrobble)

*[a discussion](https://reviewable.io/reviews/openmpf/openmpf/1364#-Me7vpJM9kw5JYnSquiJ:-Me_WyWJ6-yOkBFBtsYe:b-w3c6nz) (no related file):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

In `DefaultJobErrorHandler.java` we have:

```
log.warn("An error was encountered while processing Job #{}. The Job will be marked as {}.", jobId, BatchJobStatusType.ERROR, throwable);
```

First, I think that should be `log.error()`. Second, where is the job status actually set to `ERROR` in response to this? I only see it set to `ERROR` in two places, and it's not clear that they are related to that message.
</blockquote></details>

`DefaultJobErrorHandler` does not appear to be used.

---
*[a discussion](https://reviewable.io/reviews/openmpf/openmpf/1364#-Me81918-c4kH1K67Y5a:-MeaBxX-BMJA3vzf3KIw:bkrcy02) (no related file):*
> I think we should centralize the logic that validates the transitions between states. I like JobStatusCalculator.completionStatus(). I would feel more confident if we had something like that for non-terminal states. Maybe something like: `BatchJobStatusType  JobStatusCalculator.validateNextStatus(BatchJobStatusType initialStatus, BatchJobStatusType nextStatus)`

I think the reason we would need to validate the state transitions is that this is different from how a state machine typically works. Normally, you don't specify an initial state and the next state. You specify the initial state and the event that occurred. The state machine tells you the next state. So I think specifying the initial state as an enum and the event as an instance method on that enum is a better way to handle this.


> Similarly, CANCELLED should never change to anything else, except ERROR. 

I disagree with this part. Once something is cancelled the fact that there was an error is irrelevant. The user already told us they are not interested in the result when they cancelled the job.

---
*[a discussion](https://reviewable.io/reviews/openmpf/openmpf/1364#-Me6EeW_7zV4rW6Dk8ew:-MezaCvr1oAUB2uD1NIg:b-896fix) (no related file):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

A job will appear as `COMPLETE` while TiesDb post / callback attempts are still going on in the background. Attempting to resubmit a job in this state will result in an exception and UI popup with the message:

> Failed to resubmit the job with id '1285'. Job with id 1285 already exists.

This is confusing to an end user, who doesn't know what's going on in the background. Once this happens the UI will stay as `RESUBMITTING` until the UI is refreshed.

I think we need some indication in the UI that there is still something going on. Minimally, disable the Resubmit button, but that alone might be a little confusing. Maybe change the tooltip / hint popover to say "Callbacks in progress" or something.

---

Also, the job will stay in `RESUBMITTING` if the media doesn't exist when you try to resubmit.
</blockquote></details>

Done.

---
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessorImpl.java, line 160 at r1](https://reviewable.io/reviews/openmpf/openmpf/1364#-MeRWKZz9w6iX9jBeEnK:-MeaCny04wgtJrKLUkbj:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/d11895adec3f7727d27a60f71aa6930749a43687/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessorImpl.java#L160)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

In `WfmSplitter` we have:

```
            log.error(String.format("Failed to complete the split operation for Job %s due to an exception.", jobId),
                      exception);
            inProgressJobs.setJobStatus(jobId, BatchJobStatusType.ERROR);
```

We should be adding an error message with the exception there.

As stated in the task:

> When the job status is `ERROR`, the JSON output object does not have any messages in the errors field. We should ensure that a meaningful error message is added whenever we set the job status to `ERROR`.
</blockquote></details>

Done.
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessorImpl.java, line 168 at r1](https://reviewable.io/reviews/openmpf/openmpf/1364#-Me6Df7f43DOJ0c5LQsc:-MeaCdLz834IOkquGOse:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/d11895adec3f7727d27a60f71aa6930749a43687/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessorImpl.java#L168)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Submitting a Sphinx job with an image will result in first transitioning to `COMPLETE` before `COMPLETE_WITH_ERRORS`. While `COMPLETE` is shown in red, I think we should transition to the actual terminal status,`COMPLETE_WITH_ERRORS`, directly.

While debugging I confirmed that at this point in the code `jobStatus` is already set to `COMPLETE_WITH_ERRORS` so we should just use that. Doing so will ensure that what's in the UI, `inProgressBatchJobs`, and the DB is all the same.

If we do this, I think we can replace `setJobStatusNoBroadcast()` here with `setJobStatus()`:
```
inProgressBatchJobs.setJobStatusNoBroadcast(jobId, jobStatus.getValue());
```

In general, I'm wondering if we really need `setJobStatusNoBroadcast()` to be a separate public method or if we can just add the behavior to `setJobStatus()`.

---

Also, a few lines above we have `jobStatus.setValue(BatchJobStatusType.ERROR)`. We don't want to change the status back to `COMPLETE`.
</blockquote></details>

Done.
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/artifactextraction/ArtifactExtractionProcessor.java, line 190 at r1](https://reviewable.io/reviews/openmpf/openmpf/1364#-MeRKgwI-YSrzTLc3JwA:-Me_XHMV7gJGt_WhzwgD:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/d11895adec3f7727d27a60f71aa6930749a43687/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/artifactextraction/ArtifactExtractionProcessor.java#L190)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I think you mean `failed due to: " + e);`
</blockquote></details>

Done.
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/InProgressBatchJobsService.java, line 227 at r1](https://reviewable.io/reviews/openmpf/openmpf/1364#-Me6onKJ9jVL8183LnYg:-MeaChzGCmjD8ohy5atA:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/d11895adec3f7727d27a60f71aa6930749a43687/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/InProgressBatchJobsService.java#L227)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

It's not always appropriate to transition to an `IN_PROGRESS` state here.

Looking at this code:

```
        JobStatusCalculator.checkErrorMessages(jsonOutputObject, jobStatus);

        return storageService.store(jsonOutputObject, jobStatus, outputSha); // this may update the job status
```

That first line can set `jobStatus` to `COMPLETE`. `StorageService.store(JsonOutputObject ...)` can call `addJobWarning()`.

We don't want to transition back to `IN_PROGRESS_WARNINGS`.
</blockquote></details>

Done.
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/access/JobRequestDao.java, line 45 at r1](https://reviewable.io/reviews/openmpf/openmpf/1364#-Me6m3OtEHIgPsGE3OUl:-Me_XPA_-XxVOSE8L9oQ:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/d11895adec3f7727d27a60f71aa6930749a43687/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/access/JobRequestDao.java#L45)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Add `public` to this.
</blockquote></details>

Done.
___
*[trunk/workflow-manager [...]

2021-07-19 17:31 UTC, brosenberg42 reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1364)* status: 20 of 49 files reviewed, 10 unresolved discussions (waiting on @brosenberg42 and @jrobble)

___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/enums/BatchJobStatusType.java, line 72 at r1](https://reviewable.io/reviews/openmpf/openmpf/1364#-Me6kGb5A_-95FoqKcoy:-MezofAa3gvVbB-5W_zh:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/fca53dbea8ee0a4a7df8acc5213b9e87551238d7/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/enums/BatchJobStatusType.java#L72)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

`BUILDING_OUTPUT_OBJECT` is still mentioned in the following files:
- `jobs/layout.html` in the `Status` column legend when you click the `i` icon.
- `REST-API.html`:

> A string that will be one of the following values: UNKNOWN, INITIALIZED (the job has been initialized but not started), JOB_CREATION_ERROR (indicates that a job was received, but a job could not be created from the contents of the request), IN_PROGRESS, BUILDING_OUTPUT_OBJECT, COMPLETE, CANCELLING, CANCELLED, ERROR

The possible statuses in that list need to be updated. It's missing the warning and error variants.

</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-20 19:38 UTC, jrobble requested changes
> Reviewed 29 of 29 files at r2.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1364)* status: all files reviewed, 15 unresolved discussions (waiting on @brosenberg42)

*[a discussion](https://reviewable.io/reviews/openmpf/openmpf/1364#-Me6EeW_7zV4rW6Dk8ew:-Mf-gGiYEWs-zobIlY8b:b-b55vmu) (no related file):*
Your updates address the first part. That works well. There is still this part:

> Also, the job will stay in RESUBMITTING if the media doesn't exist when you try to resubmit.

---

Related, please clear the "End Date" contents in the UI for that job after the user clicks the resubmit button. Currently, it shows the end date for the last run and doesn't get updated until the job is complete. The `[GET] /rest/jobs/id` response also shows the old end date until the job is complete.

---
*[a discussion](https://reviewable.io/reviews/openmpf/openmpf/1364#-Me7vpJM9kw5JYnSquiJ:-Mf-gewUEb0PfmAA8f0X:b-df1dwe) (no related file):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

`DefaultJobErrorHandler` does not appear to be used.
</blockquote></details>

Should we remove it?

---
*[a discussion](https://reviewable.io/reviews/openmpf/openmpf/1364#-Me81918-c4kH1K67Y5a:-Mf-h3B9CQGz79u8-p1M:b-yp6he3) (no related file):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

> I think we should centralize the logic that validates the transitions between states. I like JobStatusCalculator.completionStatus(). I would feel more confident if we had something like that for non-terminal states. Maybe something like: `BatchJobStatusType  JobStatusCalculator.validateNextStatus(BatchJobStatusType initialStatus, BatchJobStatusType nextStatus)`

I think the reason we would need to validate the state transitions is that this is different from how a state machine typically works. Normally, you don't specify an initial state and the next state. You specify the initial state and the event that occurred. The state machine tells you the next state. So I think specifying the initial state as an enum and the event as an instance method on that enum is a better way to handle this.


> Similarly, CANCELLED should never change to anything else, except ERROR. 

I disagree with this part. Once something is cancelled the fact that there was an error is irrelevant. The user already told us they are not interested in the result when they cancelled the job.
</blockquote></details>

I think the user would be interested if the job was unable to be cancelled due to an error. However, looking [here](https://github.com/openmpf/openmpf/blob/master/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/businessrules/impl/JobRequestServiceImpl.java#L372), we only log the exception anyway, so never mind.

---
___
*[trunk/mpf-rest-api/src/main/java/org/mitre/mpf/rest/api/SingleJobInfo.java, line 43 at r2](https://reviewable.io/reviews/openmpf/openmpf/1364#-Mf3d64j5BacNG_qHmTC:-Mf3d64j5BacNG_qHmTD:biyc357) ([raw file](https://github.com/openmpf/openmpf/blob/235303ee39b4179fcdea60ec264a32a24ac885d5/trunk/mpf-rest-api/src/main/java/org/mitre/mpf/rest/api/SingleJobInfo.java#L43)):*
> ```Java
>     private String outputObjectPath;
>     private boolean hasCallbacksInProgress;
>     //terminal if status is JOB_CREATION_ERROR, COMPLETE, CANCELLED, or ERROR.
> ```

Let's just remove this comment.
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessorImpl.java, line 155 at r2](https://reviewable.io/reviews/openmpf/openmpf/1364#-Mf46aKb7OyuYMBsrZ9A:-Mf46aKeB2ehS5FUyJad:be6i4j5) ([raw file](https://github.com/openmpf/openmpf/blob/235303ee39b4179fcdea60ec264a32a24ac885d5/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessorImpl.java#L155)):*
> ```Java
>                 jobRequest.setOutputObjectVersion(propertiesUtil.getOutputObjectVersion());
>             } catch (Exception exception) {
>                 inProgressBatchJobs.addFatalError(
> ```

Log the stack trace.
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessorImpl.java, line 166 at r2](https://reviewable.io/reviews/openmpf/openmpf/1364#-Mf4KjcR-5GoBp2mqaEK:-Mf4KjcR-5GoBp2mqaEL:b-p16lmz) ([raw file](https://github.com/openmpf/openmpf/blob/235303ee39b4179fcdea60ec264a32a24ac885d5/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessorImpl.java#L166)):*
> ```Java
>             jobRequest.setJob(jsonUtils.serialize(job));
>             jobRequestDao.persist(jobRequest);
>             jobStatusBroadcaster.broadcast(jobId, 100, completionStatus);
> ```

Two popups appear on the job status page when a job completes. One is due to this `jobStatusBroadcaster.broadcast(jobId, 100, completionStatus);` call. The other is due to the `-> completeJob(job)` calls below. This is because `completeJob()` results in another broadcast.
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/markup/MarkupResponseProcessor.java, line 102 at r2](https://reviewable.io/reviews/openmpf/openmpf/1364#-Mf4MXHN3RgJYTeB_eyo:-Mf4MXHO2DLBC9d3QFed:b-6j50o9) ([raw file](https://github.com/openmpf/openmpf/blob/235303ee39b4179fcdea60ec264a32a24ac885d5/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/markup/MarkupResponseProcessor.java#L102)):*
> ```Java
>                                       warningMessage, IssueSources.MARKUP);
>         }
>         return null;
> ```

I tested a FACE --> MARKUP pipeline where I stopped the markup service so that the job could only complete the first stage. Then I cancelled the job through the UI. The job ended in `COMPLETE_WITH_ERRORS` with this in the JSON:

```
   "errors": [
      {
         "mediaId": 24,
         "details": [
            {
               "source": "MARKUP",
               "code": "MARKUP",
               "message": "This request was cancelled."
            }
         ]
      }
   ],
```

The job should have ended in `CANCELLED`.
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/mediainspection/MediaInspectionProcessor.java, line 139 at r2](https://reviewable.io/reviews/openmpf/openmpf/1364#-Mf3kb352Sk1-KxxdLx7:-Mf3kb352Sk1-KxxdLx8:bgi38ec) ([raw file](https://github.com/openmpf/openmpf/blob/235303ee39b4179fcdea60ec264a32a24ac885d5/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/mediainspection/MediaInspectionProcessor.java#L139)):*
> ```Java
>                     String errorMessage = "Could not calculate the SHA-256 hash for the file due to IOException: "
>                             + ioe;
>                     _inProgressJobs.addError(jobId, mediaId, IssueCodes.ARTIFACT_EXTRACTION, errorMessage);
> ```

I think we want `MEDIA_INSPECTION` here instead of `ARTIFACT_EXTRACTION`.
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/mediaretrieval/RemoteMediaProcessor.java, line 113 at r2](https://reviewable.io/reviews/openmpf/openmpf/1364#-Mf3guFH1PBz71vlmowc:-Mf3guFH1PBz71vlmowd:b13vpwz) ([raw file](https://github.com/openmpf/openmpf/blob/235303ee39b4179fcdea60ec264a32a24ac885d5/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/mediaretrieval/RemoteMediaProcessor.java#L113)):*
> ```Java
>                 break;
>             default:
>                 log.warn("The UriScheme '{}' was not expected at this time.", media.getUriScheme());
> ```

Since we're adding an error, please change this to `log.error()`.
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/InProgressBatchJobsService.java, line 241 at r2](https://reviewable.io/reviews/openmpf/openmpf/1364#-Mf3hMW_5BpDIB7xnSrO:-Mf3hMWa8MXfGJ-kwV-F:bcskbgi) ([raw file](https://github.com/openmpf/openmpf/blob/235303ee39b4179fcdea60ec264a32a24ac885d5/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/InProgressBatchJobsService.java#L241)):*
> ```Java
> 
> 
>     public synchronized void addJobError(long jobId, IssueCodes code, S [...]

2021-07-21 19:26 UTC, brosenberg42 reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1364)* status: 39 of 51 files reviewed, 14 unresolved discussions (waiting on @brosenberg42 and @jrobble)

*[a discussion](https://reviewable.io/reviews/openmpf/openmpf/1364#-Me7vpJM9kw5JYnSquiJ:-Mf8WCX_4Clj2_5Q2wXr:b-xm1zg5) (no related file):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Should we remove it?
</blockquote></details>

Yes, I wanted to make sure I wasn't missing something.

---
*[a discussion](https://reviewable.io/reviews/openmpf/openmpf/1364#-Me6EeW_7zV4rW6Dk8ew:-Mf9WWLE6tqLRTcMzu9X:b-896fix) (no related file):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Your updates address the first part. That works well. There is still this part:

> Also, the job will stay in RESUBMITTING if the media doesn't exist when you try to resubmit.

---

Related, please clear the "End Date" contents in the UI for that job after the user clicks the resubmit button. Currently, it shows the end date for the last run and doesn't get updated until the job is complete. The `[GET] /rest/jobs/id` response also shows the old end date until the job is complete.
</blockquote></details>

Done.

---
___
*[trunk/mpf-rest-api/src/main/java/org/mitre/mpf/rest/api/SingleJobInfo.java, line 43 at r2](https://reviewable.io/reviews/openmpf/openmpf/1364#-Mf3d64j5BacNG_qHmTC:-Mf8Wbq37McaRw-ckGzD:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/235303ee39b4179fcdea60ec264a32a24ac885d5/trunk/mpf-rest-api/src/main/java/org/mitre/mpf/rest/api/SingleJobInfo.java#L43)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Let's just remove this comment.
</blockquote></details>

Done.
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessorImpl.java, line 155 at r2](https://reviewable.io/reviews/openmpf/openmpf/1364#-Mf46aKb7OyuYMBsrZ9A:-Mf8WrXuDwAU65Ypzr4u:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/235303ee39b4179fcdea60ec264a32a24ac885d5/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessorImpl.java#L155)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Log the stack trace.
</blockquote></details>

Done.
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessorImpl.java, line 166 at r2](https://reviewable.io/reviews/openmpf/openmpf/1364#-Mf4KjcR-5GoBp2mqaEK:-Mf8Wz1c4fyA5dU-SMwU:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/235303ee39b4179fcdea60ec264a32a24ac885d5/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessorImpl.java#L166)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Two popups appear on the job status page when a job completes. One is due to this `jobStatusBroadcaster.broadcast(jobId, 100, completionStatus);` call. The other is due to the `-> completeJob(job)` calls below. This is because `completeJob()` results in another broadcast.
</blockquote></details>

Done.
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/markup/MarkupResponseProcessor.java, line 102 at r2](https://reviewable.io/reviews/openmpf/openmpf/1364#-Mf4MXHN3RgJYTeB_eyo:-Mf99SnX-91MXCot6z_M:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/235303ee39b4179fcdea60ec264a32a24ac885d5/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/markup/MarkupResponseProcessor.java#L102)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I tested a FACE --> MARKUP pipeline where I stopped the markup service so that the job could only complete the first stage. Then I cancelled the job through the UI. The job ended in `COMPLETE_WITH_ERRORS` with this in the JSON:

```
   "errors": [
      {
         "mediaId": 24,
         "details": [
            {
               "source": "MARKUP",
               "code": "MARKUP",
               "message": "This request was cancelled."
            }
         ]
      }
   ],
```

The job should have ended in `CANCELLED`.
</blockquote></details>

Done.
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/mediainspection/MediaInspectionProcessor.java, line 139 at r2](https://reviewable.io/reviews/openmpf/openmpf/1364#-Mf3kb352Sk1-KxxdLx7:-Mf8X6Uj6dpHN8iOuX0y:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/235303ee39b4179fcdea60ec264a32a24ac885d5/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/mediainspection/MediaInspectionProcessor.java#L139)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I think we want `MEDIA_INSPECTION` here instead of `ARTIFACT_EXTRACTION`.
</blockquote></details>

Done.
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/mediaretrieval/RemoteMediaProcessor.java, line 113 at r2](https://reviewable.io/reviews/openmpf/openmpf/1364#-Mf3guFH1PBz71vlmowc:-Mf8XFxoCp_2u_5TEkka:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/235303ee39b4179fcdea60ec264a32a24ac885d5/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/mediaretrieval/RemoteMediaProcessor.java#L113)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Since we're adding an error, please change this to `log.error()`.
</blockquote></details>

Done.
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/InProgressBatchJobsService.java, line 241 at r2](https://reviewable.io/reviews/openmpf/openmpf/1364#-Mf3hMW_5BpDIB7xnSrO:-Mf8YU-m6jLYAteVRBRw:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/235303ee39b4179fcdea60ec264a32a24ac885d5/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/InProgressBatchJobsService.java#L241)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

This can be removed. It's only used by a test to determine that it's never called.

`addJobWarning()` is used, so maybe you want to keep `addJobError()` for consistency and future use, or comment it out for now. Your decision.
</blockquote></details>

Done.
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/InProgressBatchJobsService.java, line 272 at r2](https://reviewable.io/reviews/openmpf/openmpf/1364#-Mf3X-VtC_5oiAhAs2mj:-Mf8XNNsD_O-602p1kkt:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/235303ee39b4179fcdea60ec264a32a24ac885d5/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/InProgressBatchJobsService.java#L272)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please change this to `LOG.error()`.
</blockquote></details>

Done.
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/InProgressBatchJobsService.java, line 301 at r2](https://reviewable.io/reviews/openmpf/openmpf/1364#-Mf49Fey9G5-fSabU5uw:-Mf8VDQl69cKPZ_OyJY6:b-by84t3) ([raw file](https://github.com/openmpf/openmpf/blob/235303ee39b4179fcdea60ec264a32a24ac885d5/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/InProgressBatchJobsService.java#L301)):*
This change was your suggestion:
> In general, I'm wondering if we really need setJobStatusNoBroadcast() to be a separate public method or if we can just add the behavior to setJobStatus().
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/enums/BatchJobStatusType.java, line 72 at r1](https://reviewable.io/reviews/openmpf/openmpf/1364#-Me6kGb5A_-95FoqKcoy:-Mf8fsc32JdCAp4lqG-v:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/fca53dbea8ee0a4a7df8acc5213b9e87551238d7/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/enums/BatchJobStatusType.java#L72)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

The UI has one additional status that is not reflected on the b [...]

2021-07-22 19:56 UTC, jrobble requested changes
> Reviewed 11 of 12 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1364)* status: all files reviewed, 3 unresolved discussions (waiting on @brosenberg42)

___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/WfmSplitter.java, line 88 at r4](https://reviewable.io/reviews/openmpf/openmpf/1364#-MfEJX2A6JiikOeQSWzS:-MfEJX2A6JiikOeQSWzT:bb6mye8) ([raw file](https://github.com/openmpf/openmpf/blob/3f50c80bd96c50558895fef4d9d9d9b82c47fe05/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/WfmSplitter.java#L88)):*
> ```Java
>         catch (Exception exception) {
>             // The split operation failed. The job cannot continue.
>             // Print out the stack trace since no details will be reported in the JSON output.
> ```

Please print out the stack trace for this fatal error too. This is what I get in the logs:

```
2021-07-22 13:43:30,880 INFO [http-nio-8080-exec-3] o.m.m.w.b.i.JobRequestServiceImpl - [Job 1366|*|*] Job has started and is running at priority 0.
2021-07-22 13:43:31,092 ERROR [Camel (camelContext) thread #1 - JmsConsumer[MPF.MEDIA_RETRIEVAL]] o.m.m.w.d.InProgressBatchJobsService - Adding the following error to job 1366: OTHER - Failed to complete the split operation for Job 1366 due to: java.lang.RuntimeException: BAD THING!
2021-07-22 13:43:31,119 INFO [Camel (camelContext) thread #1 - JmsConsumer[MPF.MEDIA_RETRIEVAL]] o.m.m.w.d.InProgressBatchJobsService - Setting status of job 1366 to ERROR
```
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/InProgressBatchJobsService.java, line 301 at r2](https://reviewable.io/reviews/openmpf/openmpf/1364#-Mf49Fey9G5-fSabU5uw:-MfEkC7K7fKHnSSTVXHW:bvflyyj) ([raw file](https://github.com/openmpf/openmpf/blob/235303ee39b4179fcdea60ec264a32a24ac885d5/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/InProgressBatchJobsService.java#L301)):*
I found where you persist and broadcast the terminal job in other places in the code. I'm assuming this check is to prevent duplication of those behaviors. At first glance it seems odd. Please add a comment explaining as much. Something like:

> // Terminal jobs are persisted, and status is broadcast, in other code.
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/InProgressBatchJobsService.java, line 284 at r4](https://reviewable.io/reviews/openmpf/openmpf/1364#-MfEefhDEdesgXmekwRJ:-MfEefhDEdesgXmekwRK:be887hj) ([raw file](https://github.com/openmpf/openmpf/blob/3f50c80bd96c50558895fef4d9d9d9b82c47fe05/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/InProgressBatchJobsService.java#L284)):*
> ```Java
> 
>         if (error.getErrorCode().equals(MpfConstants.REQUEST_CANCELLED)) {
>             cancelJob(error.getJobId());
> ```

I get the "Marking job X as cancelled" twice in the logs:

```
2021-07-22 14:00:54,977 INFO [http-nio-8080-exec-6] o.m.m.w.b.i.JobRequestServiceImpl - [Job 1367:*:*] Cancelling job.
2021-07-22 14:00:54,977 INFO [http-nio-8080-exec-6] o.m.m.w.d.InProgressBatchJobsService - Marking job 1367 as cancelled.
2021-07-22 14:00:54,977 INFO [http-nio-8080-exec-6] o.m.m.w.d.InProgressBatchJobsService - Setting status of job 1367 to CANCELLING
2021-07-22 14:00:55,133 INFO [Camel (camelContext) thread #10 - JmsConsumer[MPF.COMPLETED_MARKUP]] o.m.m.w.d.InProgressBatchJobsService - Marking job 1367 as cancelled.
```

Maybe check `job.isCancelled()` first inside `cancelJob()` before executing the lines of code again. In general, running the same code twice that's in there now isn't much of a concern (unless users are parsing the "Marking job X" line). It might be more of a concern if it's eventually  updated and no longer idempotent.


<!-- Sent from Reviewable.io -->

2021-07-23 16:02 UTC, brosenberg42 reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1364)* status: 49 of 52 files reviewed, 3 unresolved discussions (waiting on @brosenberg42 and @jrobble)

___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/WfmSplitter.java, line 88 at r4](https://reviewable.io/reviews/openmpf/openmpf/1364#-MfEJX2A6JiikOeQSWzS:-MfJ1JMM1xTWFczCzoXp:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/3f50c80bd96c50558895fef4d9d9d9b82c47fe05/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/WfmSplitter.java#L88)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please print out the stack trace for this fatal error too. This is what I get in the logs:

```
2021-07-22 13:43:30,880 INFO [http-nio-8080-exec-3] o.m.m.w.b.i.JobRequestServiceImpl - [Job 1366|*|*] Job has started and is running at priority 0.
2021-07-22 13:43:31,092 ERROR [Camel (camelContext) thread #1 - JmsConsumer[MPF.MEDIA_RETRIEVAL]] o.m.m.w.d.InProgressBatchJobsService - Adding the following error to job 1366: OTHER - Failed to complete the split operation for Job 1366 due to: java.lang.RuntimeException: BAD THING!
2021-07-22 13:43:31,119 INFO [Camel (camelContext) thread #1 - JmsConsumer[MPF.MEDIA_RETRIEVAL]] o.m.m.w.d.InProgressBatchJobsService - Setting status of job 1366 to ERROR
```
</blockquote></details>

Done.
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/InProgressBatchJobsService.java, line 301 at r2](https://reviewable.io/reviews/openmpf/openmpf/1364#-Mf49Fey9G5-fSabU5uw:-MfJ5I0DEe9i8bnjyhNC:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/235303ee39b4179fcdea60ec264a32a24ac885d5/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/InProgressBatchJobsService.java#L301)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I found where you persist and broadcast the terminal job in other places in the code. I'm assuming this check is to prevent duplication of those behaviors. At first glance it seems odd. Please add a comment explaining as much. Something like:

> // Terminal jobs are persisted, and status is broadcast, in other code.
</blockquote></details>

Done.
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/InProgressBatchJobsService.java, line 284 at r4](https://reviewable.io/reviews/openmpf/openmpf/1364#-MfEefhDEdesgXmekwRJ:-MfJ4vTy3aIAdF9ebsmJ:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/3f50c80bd96c50558895fef4d9d9d9b82c47fe05/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/InProgressBatchJobsService.java#L284)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I get the "Marking job X as cancelled" twice in the logs:

```
2021-07-22 14:00:54,977 INFO [http-nio-8080-exec-6] o.m.m.w.b.i.JobRequestServiceImpl - [Job 1367:*:*] Cancelling job.
2021-07-22 14:00:54,977 INFO [http-nio-8080-exec-6] o.m.m.w.d.InProgressBatchJobsService - Marking job 1367 as cancelled.
2021-07-22 14:00:54,977 INFO [http-nio-8080-exec-6] o.m.m.w.d.InProgressBatchJobsService - Setting status of job 1367 to CANCELLING
2021-07-22 14:00:55,133 INFO [Camel (camelContext) thread #10 - JmsConsumer[MPF.COMPLETED_MARKUP]] o.m.m.w.d.InProgressBatchJobsService - Marking job 1367 as cancelled.
```

Maybe check `job.isCancelled()` first inside `cancelJob()` before executing the lines of code again. In general, running the same code twice that's in there now isn't much of a concern (unless users are parsing the "Marking job X" line). It might be more of a concern if it's eventually  updated and no longer idempotent.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-26 18:19 UTC, jrobble approved these changes
> Reviewed 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1364)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @brosenberg42)



<!-- Sent from Reviewable.io -->

2021-07-26 19:01 UTC, jrobble approved these changes
> Reviewed 4 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1364)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @brosenberg42)



<!-- Sent from Reviewable.io -->

2021-07-26 20:14 UTC, merged