Feature: Update WFM to process derivative images.
openmpf/openmpf pull request #1365
Opened 2021-07-07 06:46 UTC by hhuangMITRE

**Issue:**

- https://github.com/openmpf/openmpf/issues/792 < Perform detection on images extracted from PDFs 

**Related PRs:**

2021-09-16 17:28 UTC, brosenberg42 requested changes
I think we need a few system tests for derivative media

> Reviewed 30 of 45 files at r2, 4 of 6 files at r3, 6 of 9 files at r4, 7 of 9 files at r5, 1 of 2 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1365#-:-Mi2M5qKBdGoddU0l6UR:bcns3pl)* status: all files reviewed, 56 unresolved discussions (waiting on @hhuangMITRE and @jrobble)

___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/MarkupController.java, line 213 at r2](https://reviewable.io/reviews/openmpf/openmpf/1365#-Mhtd7rn1UefNJF-_8af:-MiMj65a--m7qqnDzy7h:b2nhswy) ([raw file](https://github.com/openmpf/openmpf/blob/17ae3aeeb51c2908fdac9ec1c1b966a5fe21bd85/trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/MarkupController.java#L213)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

@brosenberg42 , This endpoint is no longer used. Should we remove it? 
</blockquote></details>

Yes
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/MarkupController.java, line 137 at r7](https://reviewable.io/reviews/openmpf/openmpf/1365#-MiMhj3p6FA3LAIrLUKm:-MiMhj3p6FA3LAIrLUKn:b-tmscny) ([raw file](https://github.com/openmpf/openmpf/blob/da2055fa5ac7c350c553faa414c33522c30ebaf0/trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/MarkupController.java#L137)):*
> ```Java
>         JobRequest jobRequest = jobRequestDao.findById(jobId);
>         if (jobRequest == null) {
>             return new MarkupPageListModel(draw, 0, 0, null, List.of());
> ```

I think this should result in a 404.
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/MarkupController.java, line 145 at r7](https://reviewable.io/reviews/openmpf/openmpf/1365#-MiMi8NDAdCEtnZUp5na:-MiMi8NDAdCEtnZUp5nb:b-30cs6t) ([raw file](https://github.com/openmpf/openmpf/blob/da2055fa5ac7c350c553faa414c33522c30ebaf0/trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/MarkupController.java#L145)):*
> ```Java
> 
>         //convert markup objects
>         Map<Long, MarkupResultConvertedModel> markupResultModels = new HashMap();
> ```

Another "Raw use of generic class"
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/MarkupController.java, line 182 at r7](https://reviewable.io/reviews/openmpf/openmpf/1365#-MiMiVY-5DRocMeFXhIB:-MiMiUsy9fNDAaFfffOr:b-30cs6t) ([raw file](https://github.com/openmpf/openmpf/blob/da2055fa5ac7c350c553faa414c33522c30ebaf0/trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/MarkupController.java#L182)):*
> ```Java
> 
>         //handle search
>         List<MarkupResultConvertedModel> markupResultModelsFiltered = new ArrayList();
> ```

Another "Raw use of generic class"
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/MarkupController.java, line 205 at r7](https://reviewable.io/reviews/openmpf/openmpf/1365#-Mj5lyPv4Xz8QByUyjEI:-Mj5htAG378I27e9qSme:b-6n7r2g) ([raw file](https://github.com/openmpf/openmpf/blob/da2055fa5ac7c350c553faa414c33522c30ebaf0/trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/MarkupController.java#L205)):*
> ```Java
>         int end = start + length;
>         end = (end > markupResultModelsFiltered.size()) ? markupResultModelsFiltered.size() : end;
>         start = (start <= end) ? start : end;
> ```

This doesn't make sense. It is basically `start = min(start, start + length, markupResultModelsFiltered.size())`. This will handle paging correctly:
```java
markupResultModelsFiltered
        .stream()
        .sorted(Comparator.comparingLong(MarkupResultConvertedModel::getParentMediaId)
                        .thenComparingLong(MarkupResultConvertedModel::getMediaId))
        .skip(start)
        .limit(length)
        .collect(toList());
```
skip and limit will handle the parameters being out of bounds correctly, either returning an empty list or truncating the list.
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/MarkupController.java, line 331 at r7](https://reviewable.io/reviews/openmpf/openmpf/1365#-MiMjT3LBeqw328Kek4w:-MiMjT3MEaJFmbGMlJR2:bdpc03i) ([raw file](https://github.com/openmpf/openmpf/blob/da2055fa5ac7c350c553faa414c33522c30ebaf0/trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/MarkupController.java#L331)):*
> ```Java
>     }
> 
>     private MarkupResultConvertedModel convertMarkupResultWithContentType(MarkupResult markupResult, Media media) {
> ```

This can be static
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/MarkupController.java, line 345 at r7](https://reviewable.io/reviews/openmpf/openmpf/1365#-MjAP3gGC5eOgkAcKc_e:-MjAP3gGC5eOgkAcKc_f:b-3n7rp1) ([raw file](https://github.com/openmpf/openmpf/blob/da2055fa5ac7c350c553faa414c33522c30ebaf0/trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/MarkupController.java#L345)):*
> ```Java
>             if (path == null || Files.exists(path)) { // if remote markup or available local markup
>                 markupDownloadUrl = "markup/download?id=" + markupResult.getId();
>                 markupImgUrl = markupDownloadUrl;
> ```

Can we get rid of `markupImgUrl` now that it is always the same as `markupDownloadUrl`? Same thing for `sourceImgUrl`.
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/ServerMediaController.java, line 254 at r7](https://reviewable.io/reviews/openmpf/openmpf/1365#-MiMpO88CNSJOL9nJvTt:-MiMpO89Btc8aKuoowEo:b-axyhzj) ([raw file](https://github.com/openmpf/openmpf/blob/da2055fa5ac7c350c553faa414c33522c30ebaf0/trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/ServerMediaController.java#L254)):*
> ```Java
>             }
>         } catch (IOException e) {
>             log.error(sourceUri + " media download failed: " + e.getMessage());
> ```

What is the point of all these catch clauses? It behaves the same way it did previously except it doesn't print out the stack trace. The stack trace is useful in diagnosing the issue. `response.setStatus(404); response.flushBuffer();` is only there because we want a status code other than 500.
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessorImpl.java, line 397 at r7](https://reviewable.io/reviews/openmpf/openmpf/1365#-MiN67kL4q3f9HldUVNI:-MiN67kL4q3f9HldUVNJ:b-jnkm8v) ([raw file](https://github.com/openmpf/openmpf/blob/da2055fa5ac7c350c553faa414c33522c30ebaf0/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessorImpl.java#L397)):*
> ```Java
>                     Action action = job.getPipelineElements().getAction(actionName);
> 
>                     var combinedProperties = new HashMap<>(
> ```

This is wasteful because you are getting all of the properties when you really only need two.
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessorImpl.java, line 452 at r7](https://reviewable.io/reviews/openmpf/openmpf/1365#-MiN6OOt3mqEomk6TQ05:-MiN6OOt3mqEomk6TQ06:bkcegqz) ([raw file](https://github.com/openmpf/openmpf/blob/da2055fa5ac7c350c553faa414c33522c30ebaf0/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessorImpl.java#L452)):*
> ```Java
>                                 action.getAlgorithm(), mediaOutputObject);
>                     }
>                     else if (tasksToMerge.values().contains(taskIndex)) {
> ```

You should use `tasksToMerge.containsValue` here.
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/ResponseProcessor.java, line 42 at r7](https://reviewable.io/reviews/openmpf/openmpf/1365#-Mi2NgaC45cfq_7hX4Zc:-Mi2NgaDA6CWJQl5n9YT:b6fbr9i) ([raw file](https://github.com/openmpf/openmpf/blob/da2055fa5ac7c350c553faa414c33522c30ebaf0/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/ResponseProcessor.java#L42)):*
> ```Java
> 	private static final Logger log = LoggerFactory.getLogger(ResponseProcessor.class);
> 
> 	private static InProgressBa [...]

2021-09-28 07:08 UTC, hhuangMITRE reviewed
> Reviewed 1 of 11 files at r1, 34 of 45 files at r2, 4 of 6 files at r3, 6 of 9 files at r4, 7 of 9 files at r5, 1 of 2 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1365)* status: all files reviewed, 56 unresolved discussions (waiting on @hhuangMITRE and @jrobble)



<!-- Sent from Reviewable.io -->

2022-04-21 20:35 UTC, jrobble commented
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/entities/persistent/BatchJobImpl.java, line 103 at r7](https://reviewable.io/reviews/openmpf/openmpf/1365#-Mi2UhXTEDl0uGdvrjb6:-N0CbBc6E6XctYMsXeuk:beoadey) ([raw file](https://github.com/openmpf/openmpf/blob/da2055fa5ac7c350c553faa414c33522c30ebaf0/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/entities/persistent/BatchJobImpl.java#L103)):*
Ok. I get that unmodifiable collections are supposed to be a read-only view where the underlying collection can changed by other references to it, whereas immutable collections are a new read-only copy. The elements in each type of collection can be changed, unless they themselves are also immutable.
 
I'm having trouble understanding this:

> This returning `ImmutableCollection` is problematic because the underlying data is mutable. That is why things like `getWarnings()` are not declared as immutable.

It doesn't matter if you're using an unmodifiable map or immutable one. In both cases the underlying elements in the collection are mutable using that map.

Are you saying that sometime between when the collection of warnings is returned, and when it's actually used by the caller of `getWarnings()`, that something else might modify the collection by adding another warning? An unmodifiable map is not thread safe, but an immutable one is.


<!-- Sent from Reviewable.io -->

2022-04-22 12:33 UTC, brosenberg42 commented
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/entities/persistent/BatchJobImpl.java, line 103 at r7](https://reviewable.io/reviews/openmpf/openmpf/1365#-Mi2UhXTEDl0uGdvrjb6:-N0GA30-3pvGFlPxF21T:b5u1o90) ([raw file](https://github.com/openmpf/openmpf/blob/da2055fa5ac7c350c553faa414c33522c30ebaf0/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/entities/persistent/BatchJobImpl.java#L103)):*
It is really about accurately modeling the data and using the type system to explain intent. An `UnmodifiableCollection` is a read-only view. A read-only view of an object means that the object may change over time, but either a specific piece of code isn't allowed to modify it or it must be modified using some other interface. An `ImmutableCollection` is a collection that never changes.

Previously, the `_media` map was initialized in the constructor and never changed throughout the lifetime of the job. These changes make it so that `_media` changes after the job is created.

I explain more about this design decision in this comment: https://reviewable.io/reviews/openmpf/openmpf/1365#-Mi2PhPlDrYDW8mml6r_:-Mi2PhPlDrYDW8mml6ra:brwc55u

> immutable collections are a new read-only copy

Immutable is a stronger guarantee than read-only. You don't copy immutable collections. There is no point. Things like `ImmutableList.copyOf(...)` check if the parameter is an `ImmutableList`. If it is, no copy is made and the parameter is just returned. 

> It doesn't matter if you're using an unmodifiable map or immutable one. In both cases the underlying elements in the collection are mutable using that map.

It's not about the objects in the collection. It is about membership in the collection. Previously, `BatchJob.getMedia()` (the `BatchJob` interface not the impl) returned `ImmutableCollection<? extends Media>`. This meant that no media would be added or removed as the job progressed, but the individual `Media` elements will be modified. Also, `Media` is a read-only view so it would not be modifiable through the map returned from `BatchJob.getMedia()`

By returning `ImmutableCollection` here, you are saying that no media will be added to job after it is created, but that isn't true.


<!-- Sent from Reviewable.io -->

2022-06-10 19:35 UTC, jrobble reviewed
> Reviewed 27 of 28 files at r8, 1 of 1 files at r9, 2 of 7 files at r10, 2 of 9 files at r12, 4 of 6 files at r13, 6 of 13 files at r14, 17 of 17 files at r15, 1 of 1 files at r16, 6 of 6 files at r17.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1365)* status: all files reviewed, 51 unresolved discussions (waiting on @brosenberg42 and @hhuangMITRE)

___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/MarkupController.java` line 137 at r7](https://reviewable.io/reviews/openmpf/openmpf/1365#-MiMhj3p6FA3LAIrLUKm:-N4E5S08Ch4gYOiefht_:bb6un1j) ([raw file](https://github.com/openmpf/openmpf/blob/da2055fa5ac7c350c553faa414c33522c30ebaf0/trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/MarkupController.java#L137)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

I think this should result in a 404.
</blockquote></details>

Done
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/MarkupController.java` line 145 at r7](https://reviewable.io/reviews/openmpf/openmpf/1365#-MiMi8NDAdCEtnZUp5na:-N4E5T7F-OrUBb_qgoiB:bb6un1j) ([raw file](https://github.com/openmpf/openmpf/blob/da2055fa5ac7c350c553faa414c33522c30ebaf0/trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/MarkupController.java#L145)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

Another "Raw use of generic class"
</blockquote></details>

Done
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/MarkupController.java` line 182 at r7](https://reviewable.io/reviews/openmpf/openmpf/1365#-MiMiVY-5DRocMeFXhIB:-N4E5UMjB9aBHmeQlAVv:bb6un1j) ([raw file](https://github.com/openmpf/openmpf/blob/da2055fa5ac7c350c553faa414c33522c30ebaf0/trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/MarkupController.java#L182)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

Another "Raw use of generic class"
</blockquote></details>

Done
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/MarkupController.java` line 205 at r7](https://reviewable.io/reviews/openmpf/openmpf/1365#-Mj5lyPv4Xz8QByUyjEI:-N4E5XJl-_P2Vk2O4PPc:bb6un1j) ([raw file](https://github.com/openmpf/openmpf/blob/da2055fa5ac7c350c553faa414c33522c30ebaf0/trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/MarkupController.java#L205)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

This doesn't make sense. It is basically `start = min(start, start + length, markupResultModelsFiltered.size())`. This will handle paging correctly:
```java
markupResultModelsFiltered
        .stream()
        .sorted(Comparator.comparingLong(MarkupResultConvertedModel::getParentMediaId)
                        .thenComparingLong(MarkupResultConvertedModel::getMediaId))
        .skip(start)
        .limit(length)
        .collect(toList());
```
skip and limit will handle the parameters being out of bounds correctly, either returning an empty list or truncating the list.
</blockquote></details>

Done
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/MarkupController.java` line 331 at r7](https://reviewable.io/reviews/openmpf/openmpf/1365#-MiMjT3LBeqw328Kek4w:-N4E5i1OCDYFuzVsndnA:bb6un1j) ([raw file](https://github.com/openmpf/openmpf/blob/da2055fa5ac7c350c553faa414c33522c30ebaf0/trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/MarkupController.java#L331)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

This can be static
</blockquote></details>

Done
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/MarkupController.java` line 345 at r7](https://reviewable.io/reviews/openmpf/openmpf/1365#-MjAP3gGC5eOgkAcKc_e:-N4E5jAMD2NbBj45MttG:bb6un1j) ([raw file](https://github.com/openmpf/openmpf/blob/da2055fa5ac7c350c553faa414c33522c30ebaf0/trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/MarkupController.java#L345)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

Can we get rid of `markupImgUrl` now that it is always the same as `markupDownloadUrl`? Same thing for `sourceImgUrl`.
</blockquote></details>

Done
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/ServerMediaController.java` line 254 at r7](https://reviewable.io/reviews/openmpf/openmpf/1365#-MiMpO88CNSJOL9nJvTt:-N-ZQmB1CDUJ09CFIfSi:bunnwae) ([raw file](https://github.com/openmpf/openmpf/blob/da2055fa5ac7c350c553faa414c33522c30ebaf0/trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/ServerMediaController.java#L254)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

What is the point of all these catch clauses? It behaves the same way it did previously except it doesn't print out the stack trace. The stack trace is useful in diagnosing the issue. `response.setStatus(404); response.flushBuffer();` is only there because we want a status code other than 500.
</blockquote></details>

I believe I made this change only because it seemed like an oversight to handle the 404 error differently from the rest. I confirmed that the behavior is the same except for what's logged. I changed it back and left a comment.
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessorImpl.java` line 397 at r7](https://reviewable.io/reviews/openmpf/openmpf/1365#-MiN67kL4q3f9HldUVNI:-N4E4G3y0Az9Ig9KQivC:bb6un1j) ([raw file](https://github.com/openmpf/openmpf/blob/da2055fa5ac7c350c553faa414c33522c30ebaf0/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessorImpl.java#L397)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

This is wasteful because you are getting all of the properties when you really only need two.
</blockquote></details>

Done
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessorImpl.java` line 452 at r7](https://reviewable.io/reviews/openmpf/openmpf/1365#-MiN6OOt3mqEomk6TQ05:-N4E4HOTEGLPHAQ06qra:bb6un1j) ([raw file](https://github.com/openmpf/openmpf/blob/da2055fa5ac7c350c553faa414c33522c30ebaf0/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessorImpl.java#L452)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

You should use `tasksToMerge.containsValue` here.
</blockquote></details>

Done
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/ResponseProcessor.java` line 42 at r7](https://reviewable.io/reviews/openmpf/openmpf/1365#-Mi2NgaC45cfq_7hX4Zc:-N4E4Ide4QrnwpDFORd-:bb6un1j) ([raw file](https://github.com/openmpf/openmpf/blob/da2055fa5ac7c350c553faa414c33522c30ebaf0/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/ResponseProcessor.java#L42)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

This should be `private final` not `private static`.
</blockquote></details>

Done
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/DetectionResponseProcessor.java` line 74 at r7](https://reviewable.io/reviews/openmpf/openmpf/1365#-Mi2NzEk-KtYDoK7y1ur:-N4E4K2SADb15M0Q0SQc:bb6un1j) ([raw file](https://github.com/openmpf/openmpf/blob/da2055fa5ac7c350c553faa414c33522c30ebaf0/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/DetectionResponseProcessor.java#L74)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

These should all be `private final` not `private static`
</blockquote></details>

Done
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/DetectionResponseProcessor.java` line 287 at r7](https://reviewable.io/reviews/openmpf/openmpf/1365#-MiS5wLG3goxOKdJ85ZH:-N4E4Mus1j8PLOKgUHHh:bb6un1j) ([raw file](https://github.com/openmpf/openmpf/blob/da2055fa5ac7c350c553faa414c3 [...]

2022-06-13 18:35 UTC, brosenberg42 commented
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/S3StorageBackend.java` line 345 at r7](https://reviewable.io/reviews/openmpf/openmpf/1365#-MjAsHaL6wUwr38jaORn:-N4TJWTq7kqUeYEyl_md:bsfa17x) ([raw file](https://github.com/openmpf/openmpf/blob/da2055fa5ac7c350c553faa414c33522c30ebaf0/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/S3StorageBackend.java#L345)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

The exception handling is built into `putInS3IfAbsent`. We only want to delete the file if no exception is thrown. We would need to catch the exceptions outside of that method if we want to delete the file outside of that method. I think it's better to keep everything encapsulated in the method. We call this method with `deleteLocal=true` in three places.
</blockquote></details>

I don't think my suggestion changes the exception handling behavior from what it is now. In my code snippet above, if `putInS3IfAbsent(markupPath, combinedProperties);` throws an exception, `Files.delete(markupPath)` does not run. I don't think boolean parameters in **private** methods is that big of a deal, but moving the `Files.delete(markupPath)` out of the method seemed like an easy way to avoid the boolean parameter without changing the behavior of the code.


<!-- Sent from Reviewable.io -->

2022-06-23 20:49 UTC, jrobble reviewed
> Reviewed 2 of 7 files at r20, 4 of 7 files at r21, 2 of 9 files at r22, 40 of 44 files at r23, 4 of 4 files at r24.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1365)* status: all files reviewed, 51 unresolved discussions (waiting on @brosenberg42 and @hhuangMITRE)

___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/entities/persistent/BatchJobImpl.java` line 67 at r7](https://reviewable.io/reviews/openmpf/openmpf/1365#-Mj4UnWwCPiAn5L4bPCt:-N4iHtKaC999SxzM2Hud:b-896fjx) ([raw file](https://github.com/openmpf/openmpf/blob/da2055fa5ac7c350c553faa414c33522c30ebaf0/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/entities/persistent/BatchJobImpl.java#L67)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I'm fine with this, and adding `setProcessedAction()` to `InProgressBatchJobsService` to update the `MediaImpl`. That is, if we decide to keep these data members. Please see my other comment about `wasActionProcessed()`.
</blockquote></details>

Done
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/S3StorageBackend.java` line 345 at r7](https://reviewable.io/reviews/openmpf/openmpf/1365#-MjAsHaL6wUwr38jaORn:-N57Ax-93LIrG3D7Dp7b:bb6un1j) ([raw file](https://github.com/openmpf/openmpf/blob/da2055fa5ac7c350c553faa414c33522c30ebaf0/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/S3StorageBackend.java#L345)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

I don't think my suggestion changes the exception handling behavior from what it is now. In my code snippet above, if `putInS3IfAbsent(markupPath, combinedProperties);` throws an exception, `Files.delete(markupPath)` does not run. I don't think boolean parameters in **private** methods is that big of a deal, but moving the `Files.delete(markupPath)` out of the method seemed like an easy way to avoid the boolean parameter without changing the behavior of the code.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-06-28 19:04 UTC, brosenberg42 requested changes
> Reviewed 4 of 28 files at r8, 1 of 7 files at r10, 1 of 6 files at r13, 3 of 17 files at r15, 1 of 6 files at r17, 2 of 7 files at r20, 3 of 7 files at r21, 2 of 9 files at r22, 35 of 44 files at r23, 2 of 4 files at r24, 3 of 3 files at r25.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1365)* status: all files reviewed, 11 unresolved discussions (waiting on @hhuangMITRE)

___
*[`trunk/mpf-system-tests/src/main/java/org/mitre/mpf/mst/OutputChecker.java` line 286 at r25](https://reviewable.io/reviews/openmpf/openmpf/1365#-N5eQdGj2vwicAOhPQwc:-N5eQdGj2vwicAOhPQwd:b98k7lg) ([raw file](https://github.com/openmpf/openmpf/blob/6f918d2767dea8434fccbe69e40134192572d130/trunk/mpf-system-tests/src/main/java/org/mitre/mpf/mst/OutputChecker.java#L286)):*
> ```Java
>      */
>     private void compareProperties(String type,
>                                    Map expProperties,
> ```

These parameters should be `Map<String, String>`
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/MarkupController.java` line 205 at r7](https://reviewable.io/reviews/openmpf/openmpf/1365#-Mj5lyPv4Xz8QByUyjEI:-N5_SGyEEbKO_IVll5CQ:b4rtr49) ([raw file](https://github.com/openmpf/openmpf/blob/da2055fa5ac7c350c553faa414c33522c30ebaf0/trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/MarkupController.java#L205)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Done
</blockquote></details>

The comparison method I gave you above was assuming you made the change so that the parent media id for parent media is their own id instead of -1. 
The comparison method you added is inconsistent.
```
m1: (id=4, parent=2)
m2: (id=6, parent=2)
comp(m1, m2) = 1
comp(m2, m1) = 1
```
So that is saying `m1 > m2` and `m2 > m1`. Both can't be true.

```
comp(m1, m1) = 1
```
That is saying `m1 > m1`

This seems to work:
```java
    public int sortGroupingByParent(MarkupResultConvertedModel m1, MarkupResultConvertedModel m2) {
        boolean isParent1 = m1.getParentMediaId() == -1;
        boolean isParent2 = m2.getParentMediaId() == -1;
        long m1Group = isParent1 ? m1.getMediaId() : m1.getParentMediaId();
        long m2Group = isParent2 ? m2.getMediaId() : m2.getParentMediaId();
        if (m1Group != m2Group) {
            return Long.compare(m1Group, m2Group);
        }
        if (isParent1) {
            return -1;
        }
        if (isParent2) {
            return 1;
        }
        return Long.compare(m1.getMediaId(), m2.getMediaId());
    }
```
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/DetectionResponseProcessor.java` line 65 at r19](https://reviewable.io/reviews/openmpf/openmpf/1365#-N5eXtvmEG9v8Q6sIJKK:-N5eXtvmEG9v8Q6sIJKL:b-4ie97c) ([raw file](https://github.com/openmpf/openmpf/blob/02ee2da706fbe360c84f1e1b1471756a8bcaaae2/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/DetectionResponseProcessor.java#L65)):*
> ```Java
>     private static final Logger log = LoggerFactory.getLogger(DetectionResponseProcessor.class);
> 
>     private static final JsonUtils jsonUtils = new JsonUtils(ObjectMapperFactory.customObjectMapper());
> ```

This should not be static and should be injected. It should also be named `_jsonUtils`.
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/mediainspection/MediaInspectionHelper.java` line 179 at r2](https://reviewable.io/reviews/openmpf/openmpf/1365#-N5e_6lM4QRloghgyZP8:-N5e_6lM4QRloghgyZP9:b-udnqeh) ([raw file](https://github.com/openmpf/openmpf/blob/17ae3aeeb51c2908fdac9ec1c1b966a5fe21bd85/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/mediainspection/MediaInspectionHelper.java#L179)):*
> ```Java
>                 }
>             } catch (Exception e) {
>                 LOG.error("[Job {}|*|*] Failed to inspect {} due to an exception.", jobId, media.getUri(), e);
> ```

The job information will be added through MDC.
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/mediainspection/MediaInspectionProcessor.java` line 72 at r7](https://reviewable.io/reviews/openmpf/openmpf/1365#-MiMzoyC4mr6uNjcpuYM:-N5_ZXEjDTJCBTU8f6dK:bxlnuc9) ([raw file](https://github.com/openmpf/openmpf/blob/da2055fa5ac7c350c553faa414c33522c30ebaf0/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/mediainspection/MediaInspectionProcessor.java#L72)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

All instances of `media.setFailed(true)` are preceded by logging an error (look for "setFailed").

`BatchJobStatusType.onError()`, `.onWarning()`, and `.onFatalError` calls are all preceded by log messages.

I did a search for other places where job status is set and it seems that messages are logged at some point close to where the status is set.

Please let me know if there are specific places we're missing.
</blockquote></details>

I think part of the confusion here is that there were changes to how we handle the `BatchJobStatusType` that may not have been merged in at the time. Specifically we made changes to `BatchJobStatusType` to make it function like a state machine. We don't directly set the job status any more and instead use the `BatchJobStatusType.on*` methods. 

I looked for the instances of `media.setFailed` in all those instances we update the job status, so I think this can just be removed.
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/entities/persistent/BatchJob.java` line 55 at r24](https://reviewable.io/reviews/openmpf/openmpf/1365#-N5fQLDy-DEIePoPZnNk:-N5fQLDy-DEIePoPZnNl:b-romz95) ([raw file](https://github.com/openmpf/openmpf/blob/26647232aad6c15deed3a230ab94c628ba77887a/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/entities/persistent/BatchJob.java#L55)):*
> ```Java
>     public Media getMedia(long mediaId);
> 
>     public void addDerivativeMedia(Media media);
> ```

This method shouldn't be part of the interface because it modifies the job. Call `BatchJobImpl.addDerivativeMedia` in `InProgressJobService.initDerivativeMedia`
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/entities/persistent/BatchJob.java` line 51 at r25](https://reviewable.io/reviews/openmpf/openmpf/1365#-N5_gETJ9fZdfvPfxfYB:-N5_gETJ9fZdfvPfxfYC:b-cwrdo5) ([raw file](https://github.com/openmpf/openmpf/blob/6f918d2767dea8434fccbe69e40134192572d130/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/entities/persistent/BatchJob.java#L51)):*
> ```Java
>     public int getPriority();
> 
>     public Collection<MediaImpl> getMedia();
> ```

This should be returning `Collection<Media>` MediaImpl, like BatchJobImpl, should not be exposed outside of InProgressBatchJobService. Like BatchJobImpl, MediaImpl should only be modified through synchronized methods on InProgressBatchJobService.
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/entities/persistent/MediaImpl.java` line 213 at r7](https://reviewable.io/reviews/openmpf/openmpf/1365#-MiXuakM3zgLVirMJRCO:-N5aVmXmCqwu-TlCnOeS:b-inuqvr) ([raw file](https://github.com/openmpf/openmpf/blob/da2055fa5ac7c350c553faa414c33522c30ebaf0/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/entities/persistent/MediaImpl.java#L213)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I left a comment here giving an example of a case where we don't want to inherit a property like `ROTATION`. Some properties, like media-specific S3 stuff could be useful, but I think we should error on the side of caution. Let me know if you can think if a property that would be very useful to inherit.
</blockquote></details>

I agree that there are a lot of properties we don't want to inherit. I don't think maintaining a white list of properties to inherit is any better than having the code using the property know when it should check the parent  [...]

2022-06-30 17:49 UTC, jrobble requested changes
> Reviewed 3 of 3 files at r25, 14 of 14 files at r26.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1365)* status: all files reviewed, 10 unresolved discussions (waiting on @brosenberg42 and @hhuangMITRE)

___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/MarkupController.java` line 205 at r7](https://reviewable.io/reviews/openmpf/openmpf/1365#-Mj5lyPv4Xz8QByUyjEI:-N5l6-Ze3Xp6RM11fvmm:b6zrrkh) ([raw file](https://github.com/openmpf/openmpf/blob/da2055fa5ac7c350c553faa414c33522c30ebaf0/trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/MarkupController.java#L205)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

The comparison method I gave you above was assuming you made the change so that the parent media id for parent media is their own id instead of -1. 
The comparison method you added is inconsistent.
```
m1: (id=4, parent=2)
m2: (id=6, parent=2)
comp(m1, m2) = 1
comp(m2, m1) = 1
```
So that is saying `m1 > m2` and `m2 > m1`. Both can't be true.

```
comp(m1, m1) = 1
```
That is saying `m1 > m1`

This seems to work:
```java
    public int sortGroupingByParent(MarkupResultConvertedModel m1, MarkupResultConvertedModel m2) {
        boolean isParent1 = m1.getParentMediaId() == -1;
        boolean isParent2 = m2.getParentMediaId() == -1;
        long m1Group = isParent1 ? m1.getMediaId() : m1.getParentMediaId();
        long m2Group = isParent2 ? m2.getMediaId() : m2.getParentMediaId();
        if (m1Group != m2Group) {
            return Long.compare(m1Group, m2Group);
        }
        if (isParent1) {
            return -1;
        }
        if (isParent2) {
            return 1;
        }
        return Long.compare(m1.getMediaId(), m2.getMediaId());
    }
```

</blockquote></details>

Good catch.
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/mediainspection/MediaInspectionHelper.java` line 179 at r2](https://reviewable.io/reviews/openmpf/openmpf/1365#-N5e_6lM4QRloghgyZP8:-N5lBGPS0l-6kbOSwlm6:bk9q37s) ([raw file](https://github.com/openmpf/openmpf/blob/17ae3aeeb51c2908fdac9ec1c1b966a5fe21bd85/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/mediainspection/MediaInspectionHelper.java#L179)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

The job information will be added through MDC.
</blockquote></details>

How would you change this log message?

I know the MDC adds the job id, but it doesn't add the media url.
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/S3StorageBackend.java` line 215 at r7](https://reviewable.io/reviews/openmpf/openmpf/1365#-MjAwZcYEanlHXWB9Us1:-N5l7EXU64ZzPakkR_yP:b-qygqz8) ([raw file](https://github.com/openmpf/openmpf/blob/da2055fa5ac7c350c553faa414c33522c30ebaf0/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/S3StorageBackend.java#L215)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I will work on this unit test and a system test next.
</blockquote></details>

I added these in the last update.
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/StorageService.java` line 190 at r25](https://reviewable.io/reviews/openmpf/openmpf/1365#-N5a0wPW3qdXDpXGgTAd:-N5l9MJk2CSiKrjtf6tn:b-vs1pr4) ([raw file](https://github.com/openmpf/openmpf/blob/6f918d2767dea8434fccbe69e40134192572d130/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/StorageService.java#L190)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

I think we should refactor this to the code below. The code I provided handles exceptions using the same pattern used for the output object and artifacts. I think part that creates the future is cleaner.
```java
    public void storeDerivativeMedia(BatchJob job) {
        var semaphore = new Semaphore(Math.max(
                1, _propertiesUtil.getDerivativeMediaParallelUploadCount()));

        var futures = new ArrayList<CompletableFuture<Void>>();

        for (Media media : job.getMedia()) {
            if (!media.isDerivative()) {
                continue;
            }

            try {
                semaphore.acquire();
            }
            catch (InterruptedException e) {
                Thread.currentThread().interrupt();
                throw new IllegalStateException(e);
            }

            var future = ThreadUtil
                    .runAsync(() -> storeDerivativeMedia(job, media))
                    .whenComplete((x, y) -> semaphore.release());
            futures.add(future);
        }
        ThreadUtil.allOf(futures).join();
    }


    private void storeDerivativeMedia(BatchJob job, Media media) {
        Exception remoteException = null;
        try {
            for (var backend : _remoteBackends) {
                if (backend.canStoreDerivativeMedia(job, media.getParentId())) {
                    backend.storeDerivativeMedia(job, media);
                    return;
                }
            }
        }
        catch (StorageException | IOException e) {
            remoteException = e;
            handleDerivativeMediaRemoteStorageFailure(job.getId(), media, e);
        }

        try {
            _localBackend.storeDerivativeMedia(job, media);
        }
        catch (IOException localException) {
            if (remoteException != null) {
                localException.addSuppressed(remoteException);
            }
            handleDerivativeMediaLocalStorageFailure(job.getId(), media, localException);
        }
    }
```
</blockquote></details>

Looks good.


<!-- Sent from Reviewable.io -->

2022-07-07 14:37 UTC, jrobble reviewed
> Reviewed 7 of 7 files at r27.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1365)* status: all files reviewed, 2 unresolved discussions (waiting on @brosenberg42)

___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/mediainspection/MediaInspectionProcessor.java` line 72 at r7](https://reviewable.io/reviews/openmpf/openmpf/1365#-MiMzoyC4mr6uNjcpuYM:-N6O4psO-Cdsbw4uf9ij:bb6un1j) ([raw file](https://github.com/openmpf/openmpf/blob/da2055fa5ac7c350c553faa414c33522c30ebaf0/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/mediainspection/MediaInspectionProcessor.java#L72)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

This still needs to be addressed.
</blockquote></details>

Done
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/entities/persistent/BatchJob.java` line 55 at r24](https://reviewable.io/reviews/openmpf/openmpf/1365#-N5fQLDy-DEIePoPZnNk:-N6O4r6F535G7k1s5gQm:bb6un1j) ([raw file](https://github.com/openmpf/openmpf/blob/26647232aad6c15deed3a230ab94c628ba77887a/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/entities/persistent/BatchJob.java#L55)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

You did the second part, but you still need to remove this method from the interface.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-07-07 15:12 UTC, brosenberg42 approved these changes
> Reviewed 6 of 7 files at r27.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1365)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hhuangMITRE)



<!-- Sent from Reviewable.io -->

2022-07-11 18:52 UTC, jrobble reviewed
> Reviewed 5 of 5 files at r28.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1365)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hhuangMITRE)



<!-- Sent from Reviewable.io -->

2022-07-13 20:07 UTC, jrobble approved these changes
> Reviewed 2 of 2 files at r29.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1365)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hhuangMITRE)



<!-- Sent from Reviewable.io -->

2022-07-14 01:25 UTC, merged