Feature/check tiesdb
openmpf/openmpf pull request #1614
Opened 2022-11-08 13:47 UTC by brosenberg42

**Issues:**
- https://github.com/openmpf/openmpf/issues/1613

2022-11-08 13:52 UTC, brosenberg42 commented
*[`trunk/workflow-manager/src/main/resources/templates/important-properties.json` line 1 at r9](https://reviewable.io/reviews/openmpf/openmpf/1614#-NGMUnxt5n-MA9SRUDaJ:-NGMUnxt5n-MA9SRUDaK:b33a4z4) ([raw file](https://github.com/openmpf/openmpf/blob/cdfeeccea0169592a763aabcf83d10cfff1e86fe/trunk/workflow-manager/src/main/resources/templates/important-properties.json#L1)):*
> ```JSON
> {
> ```

As I started going through the properties, I started thinking that it might be better to take the opposite approach. Instead of listing the properties that **can't change** as I did here, it might be better to list the properties that **can** change.


<!-- Sent from Reviewable.io -->

2023-02-25 04:16 UTC, jrobble requested changes
> Reviewed 4 of 103 files at r3, 1 of 103 files at r4, 97 of 136 files at r9, 50 of 50 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1614)* status: all files reviewed, 32 unresolved discussions (waiting on @brosenberg42)

*[a discussion](https://reviewable.io/reviews/openmpf/openmpf/1614#-NP4HoyMBOWxhcWUS71I:-NP4HoyP1tHm709SYsnV:b-bpcpat) (no related file):*
I saw this in the WFM log:

```
2023-02-24 16:14:26,234 ERROR [Camel (camelContext) thread #9 - JmsConsumer[MPF.JOB_ROUTER]] o.m.m.w.s.TiesDbBeforeJobCheckServiceImpl - [Job 154] A matching job was found in TiesDb, but copying results from the old job failed due to: org.mitre.mpf.wfm.service.StorageException: An error occurred while trying to determine the S3 endpoint: Expected scheme-specific part at index 5: file:
org.mitre.mpf.wfm.service.StorageException: An error occurred while trying to determine the S3 endpoint: Expected scheme-specific part at index 5: file:
        at org.mitre.mpf.wfm.service.S3UrlUtil$1.getS3Endpoint(S3UrlUtil.java:129) ~[classes/:?]
        at org.mitre.mpf.wfm.service.S3StorageBackend.getOldJobOutputObjectStream(S3StorageBackend.java:432) ~[classes/:?]
```

This happened when I ran a job locally, stored the job in TiesDb, set up MinIO, and then ran the same job with `S3_ACCESS_KEY`, `S3_SECRET_KEY`, and `S3_RESULTS_BUCKET` settings.

There is no indication of an error in the JSON output object. It says `"status": "COMPLETE"`. The status in the job status page says "COMPLETE_WITH_ERRORS".

___
*[a discussion](https://reviewable.io/reviews/openmpf/openmpf/1614#-NP4KURB6brU-AXQr9tm:-NP4KURB6brU-AXQr9tn:b-n68ive) (no related file):*
I saw this in the WFM log:

```
Message History
---------------------------------------------------------------------------------------------------------------------------------------
RouteId              ProcessorId          Processor                                                                        Elapsed (ms)
[Job Router Route  ] [Job Router Route  ] [jms://MPF.JOB_ROUTER                                                          ] [         8]
[Job Router Route  ] [setExchangePattern] [setExchangePattern[InOnly]                                                    ] [         0]
[Job Router Route  ] [choice4           ] [when[{header{header(JobComplete)} == true}]choice[]                           ] [         0]
[Job Router Route  ] [process8          ] [ref:jobCompleteProcessorImpl                                                  ] [         8]

Stacktrace
---------------------------------------------------------------------------------------------------------------------------------------
java.util.NoSuchElementException: No value present
        at java.util.Optional.orElseThrow(Optional.java:377) ~[?:?]
        at org.mitre.mpf.wfm.service.JobConfigHasher.getJobConfigHash(JobConfigHasher.java:94) ~[classes/:?]
        at org.mitre.mpf.wfm.service.TiesDbService.getJobConfigHash(TiesDbService.java:323) ~[classes/:?]
        at org.mitre.mpf.wfm.service.TiesDbService.storeAssertions(TiesDbService.java:185) ~[classes/:?]
        at org.mitre.mpf.wfm.camel.JobCompleteProcessorImpl.wfmProcess(JobCompleteProcessorImpl.java:174) ~[classes/:?]
        at org.mitre.mpf.wfm.camel.WfmProcessor.lambda$0(WfmProcessor.java:59) ~[classes/:?]
        at org.mitre.mpf.mvc.util.MdcUtil.lambda$0(MdcUtil.java:120) ~[classes/:?]
        at org.mitre.mpf.mvc.util.MdcUtil.job(MdcUtil.java:102) ~[classes/:?]
        at org.mitre.mpf.mvc.util.MdcUtil.job(MdcUtil.java:114) ~[classes/:?]
        at org.mitre.mpf.wfm.camel.WfmProcessor.process(WfmProcessor.java:59) ~[classes/:?]
        at org.mitre.mpf.wfm.camel.WfmProcessor$$FastClassBySpringCGLIB$$dbb36fb4.invoke(<generated>) ~[classes/:?]
```

This happened when I ran a job using a piece of media in MinIO but didn't specify the `S3_ACCESS_KEY` and `S3_SECRET_KEY`. I can see attempts to retry downloading the media in the log. Since the media was not downloaded it has no hash, which activates the `orElseThrow()` later on when trying to get the job config hash.

This ultimately results in a message going into the DLQ that's not processed by the WFM. The job stays in the "IN_PROGRESS_ERRORS" state at 99% forever in the web UI.

___
___
*[`trunk/interop/src/main/java/org/mitre/mpf/interop/JsonOutputObject.java` line 44 at r10](https://reviewable.io/reviews/openmpf/openmpf/1614#-NNgkjguA5bnYbb_q2bH:-NNgkjguA5bnYbb_q2bI:b-rf5835) ([raw file](https://github.com/openmpf/openmpf/blob/0edf9b53bfcecf1c906f07c8dbac685ca568b53d/trunk/interop/src/main/java/org/mitre/mpf/interop/JsonOutputObject.java#L44)):*
> ```Java
> 
>     @JsonPropertyDescription("If the job didn't run because it was possible to get the results"
>         + "from TiesDb, this will be set to the job id of the job that generated those results.")
> ```

Missing space in front of "from TiesDb ..."
___
*[`trunk/mpf-rest-api/src/main/java/org/mitre/mpf/rest/api/TiesDbRepostResponse.java` line 1 at r10](https://reviewable.io/reviews/openmpf/openmpf/1614#-NOAmGTCE8wopnMOdzsp:-NOAmGTCE8wopnMOdzsq:b-fp6hkq) ([raw file](https://github.com/openmpf/openmpf/blob/0edf9b53bfcecf1c906f07c8dbac685ca568b53d/trunk/mpf-rest-api/src/main/java/org/mitre/mpf/rest/api/TiesDbRepostResponse.java#L1)):*
> ```Java
> package org.mitre.mpf.rest.api;
> ```

Missing header comments.
___
*[`trunk/mpf-rest-api/src/main/java/org/mitre/mpf/rest/api/TiesDbRepostResponse.java` line 10 at r10](https://reviewable.io/reviews/openmpf/openmpf/1614#-NOAmcUCEpIWCypz7jVx:-NOAmcUCEpIWCypz7jVy:b-u4wojp) ([raw file](https://github.com/openmpf/openmpf/blob/0edf9b53bfcecf1c906f07c8dbac685ca568b53d/trunk/mpf-rest-api/src/main/java/org/mitre/mpf/rest/api/TiesDbRepostResponse.java#L10)):*
> ```Java
> 
> 
>     public record Failure(long jobId, String error){}
> ```

Indentation off.
___
*[`trunk/workflow-manager/pom.xml` line 48 at r10](https://reviewable.io/reviews/openmpf/openmpf/1614#-NOAp29e29Td3DqRx4mR:-NOAp29e29Td3DqRx4mS:b-c2k322) ([raw file](https://github.com/openmpf/openmpf/blob/0edf9b53bfcecf1c906f07c8dbac685ca568b53d/trunk/workflow-manager/pom.xml#L48)):*
> ```XML
>         <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
>         <wfm.port>8080</wfm.port>
>         <extraArgLine/>
> ```

What's this used for? Still necessary?
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/JobController.java` line 434 at r10](https://reviewable.io/reviews/openmpf/openmpf/1614#-NP3adSP9xN_t8ECA0gQ:-NP3adSQ1QDqR07vZfkd:ba980s0) ([raw file](https://github.com/openmpf/openmpf/blob/0edf9b53bfcecf1c906f07c8dbac685ca568b53d/trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/JobController.java#L434)):*
> ```Java
> 
> 
>     @RequestMapping(value = {"/rest/jobs/tiesdbrepost", "jobs/tiesdbrepost"},
> ```

In the description explain what the body of the request is and provide an example. It's not clear looking at the Swagger page.
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/JobController.java` line 434 at r10](https://reviewable.io/reviews/openmpf/openmpf/1614#-NP5iZ0X2b0jaAv6uQra:-NOAp7tu73yFJqx6QOVN:b5tboou) ([raw file](https://github.com/openmpf/openmpf/blob/0edf9b53bfcecf1c906f07c8dbac685ca568b53d/trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/JobController.java#L434)):*
> ```Java
> 
> 
>     @RequestMapping(value = {"/rest/jobs/tiesdbrepost", "jobs/tiesdbrepost"},
> ```

We need to update the REST API doc. to include this exposed endpoint.
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/enums/MpfConstants.java` line 96 at r10](https://reviewable.io/reviews/openmpf/openmpf/1614#-NOBZQQm5xeHV-iXrusU:-NOBZQQm5xeHV-iXrusV:b-voj4dp) ([raw file](https://github.com/openmpf/openmpf/blob/0edf9b53bfcecf1c906f07c8dbac685ca568b53d/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/enums/MpfConstants.java#L96)):*
> ```Java
>             IS_DERIVATIVE_ME [...]

2023-03-01 22:25 UTC, jrobble requested changes
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1614)* status: all files reviewed, 43 unresolved discussions (waiting on @brosenberg42)

*[a discussion](https://reviewable.io/reviews/openmpf/openmpf/1614#-NP4HoyMBOWxhcWUS71I:-NPOE8Cu6lnAudTR7BIz:b6wcgf1) (no related file):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I saw this in the WFM log:

```
2023-02-24 16:14:26,234 ERROR [Camel (camelContext) thread #9 - JmsConsumer[MPF.JOB_ROUTER]] o.m.m.w.s.TiesDbBeforeJobCheckServiceImpl - [Job 154] A matching job was found in TiesDb, but copying results from the old job failed due to: org.mitre.mpf.wfm.service.StorageException: An error occurred while trying to determine the S3 endpoint: Expected scheme-specific part at index 5: file:
org.mitre.mpf.wfm.service.StorageException: An error occurred while trying to determine the S3 endpoint: Expected scheme-specific part at index 5: file:
        at org.mitre.mpf.wfm.service.S3UrlUtil$1.getS3Endpoint(S3UrlUtil.java:129) ~[classes/:?]
        at org.mitre.mpf.wfm.service.S3StorageBackend.getOldJobOutputObjectStream(S3StorageBackend.java:432) ~[classes/:?]
```

This happened when I ran a job locally, stored the job in TiesDb, set up MinIO, and then ran the same job with `S3_ACCESS_KEY`, `S3_SECRET_KEY`, and `S3_RESULTS_BUCKET` settings.

There is no indication of an error in the JSON output object. It says `"status": "COMPLETE"`. The status in the job status page says "COMPLETE_WITH_ERRORS".
</blockquote></details>

Note that another reason this can happen is when S3 is not configured correctly, or misbehaving, and the JSON, artifacts, and markup are stored locally as the fallback behavior.

___
*[a discussion](https://reviewable.io/reviews/openmpf/openmpf/1614#-NP4KURB6brU-AXQr9tm:-NPJMbVw93D6On-GVXpx:b-juvwi7) (no related file):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I saw this in the WFM log:

```
Message History
---------------------------------------------------------------------------------------------------------------------------------------
RouteId              ProcessorId          Processor                                                                        Elapsed (ms)
[Job Router Route  ] [Job Router Route  ] [jms://MPF.JOB_ROUTER                                                          ] [         8]
[Job Router Route  ] [setExchangePattern] [setExchangePattern[InOnly]                                                    ] [         0]
[Job Router Route  ] [choice4           ] [when[{header{header(JobComplete)} == true}]choice[]                           ] [         0]
[Job Router Route  ] [process8          ] [ref:jobCompleteProcessorImpl                                                  ] [         8]

Stacktrace
---------------------------------------------------------------------------------------------------------------------------------------
java.util.NoSuchElementException: No value present
        at java.util.Optional.orElseThrow(Optional.java:377) ~[?:?]
        at org.mitre.mpf.wfm.service.JobConfigHasher.getJobConfigHash(JobConfigHasher.java:94) ~[classes/:?]
        at org.mitre.mpf.wfm.service.TiesDbService.getJobConfigHash(TiesDbService.java:323) ~[classes/:?]
        at org.mitre.mpf.wfm.service.TiesDbService.storeAssertions(TiesDbService.java:185) ~[classes/:?]
        at org.mitre.mpf.wfm.camel.JobCompleteProcessorImpl.wfmProcess(JobCompleteProcessorImpl.java:174) ~[classes/:?]
        at org.mitre.mpf.wfm.camel.WfmProcessor.lambda$0(WfmProcessor.java:59) ~[classes/:?]
        at org.mitre.mpf.mvc.util.MdcUtil.lambda$0(MdcUtil.java:120) ~[classes/:?]
        at org.mitre.mpf.mvc.util.MdcUtil.job(MdcUtil.java:102) ~[classes/:?]
        at org.mitre.mpf.mvc.util.MdcUtil.job(MdcUtil.java:114) ~[classes/:?]
        at org.mitre.mpf.wfm.camel.WfmProcessor.process(WfmProcessor.java:59) ~[classes/:?]
        at org.mitre.mpf.wfm.camel.WfmProcessor$$FastClassBySpringCGLIB$$dbb36fb4.invoke(<generated>) ~[classes/:?]
```

This happened when I ran a job using a piece of media in MinIO but didn't specify the `S3_ACCESS_KEY` and `S3_SECRET_KEY`. I can see attempts to retry downloading the media in the log. Since the media was not downloaded it has no hash, which activates the `orElseThrow()` later on when trying to get the job config hash.

This ultimately results in a message going into the DLQ that's not processed by the WFM. The job stays in the "IN_PROGRESS_ERRORS" state at 99% forever in the web UI.


</blockquote></details>

I saw the same log content pasted above, and behavior in the web UI and DLQ, when running a job with a piece of remote media on a MinIO server that was not active (I killed the MinIO server Docker container).

___
*[a discussion](https://reviewable.io/reviews/openmpf/openmpf/1614#-NPJRL2476Np0mKQxZYn:-NPJRL271sn8Ryud1drg:b-vfcgch) (no related file):*
When a job is found in TiesDb, but the object storage server hosting the JSON output object cannot be reached, the job fails with `COMPLETE_WITH_ERRORS` in the web UI but the only way to know what failed is to check the log.

Similarly, the job ends with `COMPLETE_WITH_ERRORS` if there is an issue copying the results from one S3 bucket to another, such as bad credentials for the source or destination.

Is there a way to represent what went wrong in the web UI, possibly using the `TiesDb` status column, or a different job status?

___
*[a discussion](https://reviewable.io/reviews/openmpf/openmpf/1614#-NPK0e1UE7lmQQQYknpn:-NPK0e1VEa6NKLHx4eCi:b-gx688w) (no related file):*
Only listing `MEDIA_HASH` and `MIME_TYPE` in `media.metadata` in the job request will result in the job ending in `COMPLETE_WITH_WARNINGS` when the media isn't found in TiesDb due to things like:

> "Missing required image metadata: FRAME_WIDTH, FRAME_HEIGHT. Cannot skip media inspection."

Job producers are going to provide `MEDIA_HASH` and `MIME_TYPE` for every job since they don't know if the job has been run before and a record exists in TiesDb. Therefore, the first run of every image, video, and audio job will end in `COMPLETE_WITH_WARNINGS`, at best.

To address this, I believe we need to expose a property to enable / disable skipping media inspection.

___
*[a discussion](https://reviewable.io/reviews/openmpf/openmpf/1614#-NPPzCld1_jtzFLdvOcG:-NPPzCld1_jtzFLdvOcH:bntadqj) (no related file):*
Note that the TiesDb server only returns a max of 100 records at a time by default, so we need to hit the endpoint multiple times with an `offset` to keep getting pages of results. Below I explicitly set `limit` to 100 for clarity (and to mitigate the risk of the default value ever changing). If we want more records per page we can increase the `limit`.

```
curl -k "https://somehost/api/db/supplementals?sha256Hash=fadad724ec67749556913b659521e854124c3ad784fc94058c27999f2cd2eac9&limit=100&offset=0" | jq length
...
100

curl -k "https://somehost/api/db/supplementals?sha256Hash=fadad724ec67749556913b659521e854124c3ad784fc94058c27999f2cd2eac9&limit=100&offset=100" | jq length
...
100

curl -k "https://somehost/api/db/supplementals?sha256Hash=fadad724ec67749556913b659521e854124c3ad784fc94058c27999f2cd2eac9&limit=100&offset=200" | jq length
...
100

curl -k "https://somehost/api/db/supplementals?sha256Hash=fadad724ec67749556913b659521e854124c3ad784fc94058c27999f2cd2eac9&limit=100&offset=300" | jq length
...
42
```

Also, use the `&system=OpenMPF`filter. That way we avoid records that don't match our schema.

___
___
*[`trunk/interop/src/main/java/org/mitre/mpf/interop/JsonOutputObject.java` line 35 at r10](https://reviewable.io/reviews/openmpf/openmpf/1614#-NPK0IRD3k2RiE-H9k72:-NPK0IRD3k2RiE-H9k73:br2xrmr) ([raw file](https://github.com/openmpf/openmpf/blob/0edf9b53bfcecf1c906f07c8dbac685ca568b53d/trunk/interop/src/main/java/org/mitre/mpf/interop/JsonOutputObject.java#L35)):*
> ```Java
> 
> @JsonTypeName("OutputObject")
> @JsonPropertyOrder({"openmpfVersio [...]

2023-03-14 13:16 UTC, brosenberg42 commented
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/TiesDbBeforeJobCheckServiceImpl.java` line 429 at r10](https://reviewable.io/reviews/openmpf/openmpf/1614#-NP3m18Y8UL9jK7ythuU:-NQVE9zZ8jtO55mun38K:bnj8y4y) ([raw file](https://github.com/openmpf/openmpf/blob/0edf9b53bfcecf1c906f07c8dbac685ca568b53d/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/TiesDbBeforeJobCheckServiceImpl.java#L429)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

We still need to set `tiesDbSourceJobId` even if we're not using S3 object storage. Right now it's set to `"tiesDbSourceJobId": null,` in the JSON output object even if the job is reused.
</blockquote></details>

In order to set that field, we need to create a new a output object. We would also have to upload that output object to S3, but the user told us they don't want the results copied. I agree that it shouldn't say `"tiesDbSourceJobId": null,` when a job was skipped, but I don't know how we can both fix that issue and do what the user told us to do.


<!-- Sent from Reviewable.io -->

2023-03-16 10:04 UTC, brosenberg42 reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1614)* status: 128 of 153 files reviewed, 43 unresolved discussions (waiting on @jrobble)

*[a discussion](https://reviewable.io/reviews/openmpf/openmpf/1614#-NP4HoyMBOWxhcWUS71I:-NQVH-5xDT38fpY_sQMz:b-896fix) (no related file):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Note that another reason this can happen is when S3 is not configured correctly, or misbehaving, and the JSON, artifacts, and markup are stored locally as the fallback behavior.
</blockquote></details>

Done.

___
*[a discussion](https://reviewable.io/reviews/openmpf/openmpf/1614#-NP4KURB6brU-AXQr9tm:-NQ6p78p9mQtL7fqoDjO:b-896fix) (no related file):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I saw the same log content pasted above, and behavior in the web UI and DLQ, when running a job with a piece of remote media on a MinIO server that was not active (I killed the MinIO server Docker container).
</blockquote></details>

Done.

___
*[a discussion](https://reviewable.io/reviews/openmpf/openmpf/1614#-NPJRL2476Np0mKQxZYn:-NQVMGRUEhHN49AcVvVH:b-om0dpm) (no related file):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

When a job is found in TiesDb, but the object storage server hosting the JSON output object cannot be reached, the job fails with `COMPLETE_WITH_ERRORS` in the web UI but the only way to know what failed is to check the log.

Similarly, the job ends with `COMPLETE_WITH_ERRORS` if there is an issue copying the results from one S3 bucket to another, such as bad credentials for the source or destination.

Is there a way to represent what went wrong in the web UI, possibly using the `TiesDb` status column, or a different job status?
</blockquote></details>

I put it in the existing TiesDb status column.

___
*[a discussion](https://reviewable.io/reviews/openmpf/openmpf/1614#-NPPzCld1_jtzFLdvOcG:-NQa6K4q5EpGuxez1VAu:b-896fix) (no related file):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Note that the TiesDb server only returns a max of 100 records at a time by default, so we need to hit the endpoint multiple times with an `offset` to keep getting pages of results. Below I explicitly set `limit` to 100 for clarity (and to mitigate the risk of the default value ever changing). If we want more records per page we can increase the `limit`.

```
curl -k "https://somehost/api/db/supplementals?sha256Hash=fadad724ec67749556913b659521e854124c3ad784fc94058c27999f2cd2eac9&limit=100&offset=0" | jq length
...
100

curl -k "https://somehost/api/db/supplementals?sha256Hash=fadad724ec67749556913b659521e854124c3ad784fc94058c27999f2cd2eac9&limit=100&offset=100" | jq length
...
100

curl -k "https://somehost/api/db/supplementals?sha256Hash=fadad724ec67749556913b659521e854124c3ad784fc94058c27999f2cd2eac9&limit=100&offset=200" | jq length
...
100

curl -k "https://somehost/api/db/supplementals?sha256Hash=fadad724ec67749556913b659521e854124c3ad784fc94058c27999f2cd2eac9&limit=100&offset=300" | jq length
...
42
```

Also, use the `&system=OpenMPF`filter. That way we avoid records that don't match our schema.
</blockquote></details>

Done.

___
___
*[`trunk/interop/src/main/java/org/mitre/mpf/interop/JsonOutputObject.java` line 35 at r10](https://reviewable.io/reviews/openmpf/openmpf/1614#-NPK0IRD3k2RiE-H9k72:-NPwCnTRAjTtrjQoFsWS:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/0edf9b53bfcecf1c906f07c8dbac685ca568b53d/trunk/interop/src/main/java/org/mitre/mpf/interop/JsonOutputObject.java#L35)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

List `tiesDbSourceJobId` after `jobId`.
</blockquote></details>

Done.
___
*[`trunk/interop/src/main/java/org/mitre/mpf/interop/JsonOutputObject.java` line 44 at r10](https://reviewable.io/reviews/openmpf/openmpf/1614#-NNgkjguA5bnYbb_q2bH:-NPwCoaW3Jq7Meupzo_N:bs7wunb) ([raw file](https://github.com/openmpf/openmpf/blob/0edf9b53bfcecf1c906f07c8dbac685ca568b53d/trunk/interop/src/main/java/org/mitre/mpf/interop/JsonOutputObject.java#L44)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Missing space in front of "from TiesDb ..."
</blockquote></details>

Done..
___
*[`trunk/mpf-rest-api/src/main/java/org/mitre/mpf/rest/api/TiesDbRepostResponse.java` line 1 at r10](https://reviewable.io/reviews/openmpf/openmpf/1614#-NOAmGTCE8wopnMOdzsp:-NPwBdZ2AivGO4RnIUme:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/0edf9b53bfcecf1c906f07c8dbac685ca568b53d/trunk/mpf-rest-api/src/main/java/org/mitre/mpf/rest/api/TiesDbRepostResponse.java#L1)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Missing header comments.
</blockquote></details>

Done.
___
*[`trunk/mpf-rest-api/src/main/java/org/mitre/mpf/rest/api/TiesDbRepostResponse.java` line 10 at r10](https://reviewable.io/reviews/openmpf/openmpf/1614#-NOAmcUCEpIWCypz7jVx:-NPwBbZt6DCLV85Rf4pG:b-bytkpp) ([raw file](https://github.com/openmpf/openmpf/blob/0edf9b53bfcecf1c906f07c8dbac685ca568b53d/trunk/mpf-rest-api/src/main/java/org/mitre/mpf/rest/api/TiesDbRepostResponse.java#L10)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Indentation off.
</blockquote></details>

It looks correct to me.
___
*[`trunk/workflow-manager/pom.xml` line 48 at r10](https://reviewable.io/reviews/openmpf/openmpf/1614#-NOAp29e29Td3DqRx4mR:-NPwBy4f6CUMfg9XtGih:bogvhh8) ([raw file](https://github.com/openmpf/openmpf/blob/0edf9b53bfcecf1c906f07c8dbac685ca568b53d/trunk/workflow-manager/pom.xml#L48)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

What's this used for? Still necessary?
</blockquote></details>

It's for a code coverage plugin.
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/JobConfigHasher.java` line 51 at r10](https://reviewable.io/reviews/openmpf/openmpf/1614#-NOBEyEw3RHiGfOp-NUo:-NPwEUmo48AiQkimFM6J:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/0edf9b53bfcecf1c906f07c8dbac685ca568b53d/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/JobConfigHasher.java#L51)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Not used.
</blockquote></details>

Done.
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/JobConfigHasher.java` line 93 at r10](https://reviewable.io/reviews/openmpf/openmpf/1614#-NPUC8Fa3C3QSFzIPtva:-NPwEg3d8xMu-3zMODFa:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/0edf9b53bfcecf1c906f07c8dbac685ca568b53d/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/JobConfigHasher.java#L93)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

We should skip derivative media when calculating the hash. Derivative media are not part of the media collection when the job starts so there's no way to calculate a job hash using only the parent media such that it matches a hash in TiesDb that was calculated with the parent media and derivative media.

I ran some tests and the post-run job hash for a derivative media job was always the same for re-runs of the same job. It just never matched the pre-run job hash.
</blockquote></details>

Done.
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/JobConfigHasher.java` line 120 at r10](https://reviewable.io/reviews/openmpf/openmpf/1614#-NOBK9AX6_qYBaZ-Vwwr:-NQaBz3y9z3KI2LaVo8I:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/0edf9b53bfcecf1c906f07c8dbac685ca568b53d/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/JobConfigHasher.java#L120)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

What about hashing the JSON output object version?

Speaking of that, you should upda [...]

2023-03-17 11:43 UTC, brosenberg42 reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1614)* status: 126 of 154 files reviewed, 42 unresolved discussions (waiting on @jrobble)

*[a discussion](https://reviewable.io/reviews/openmpf/openmpf/1614#-NPK0e1UE7lmQQQYknpn:-NQeDOkd49-0I3Rkfwge:b-896fix) (no related file):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Only listing `MEDIA_HASH` and `MIME_TYPE` in `media.metadata` in the job request will result in the job ending in `COMPLETE_WITH_WARNINGS` when the media isn't found in TiesDb due to things like:

> "Missing required image metadata: FRAME_WIDTH, FRAME_HEIGHT. Cannot skip media inspection."

Job producers are going to provide `MEDIA_HASH` and `MIME_TYPE` for every job since they don't know if the job has been run before and a record exists in TiesDb. Therefore, the first run of every image, video, and audio job will end in `COMPLETE_WITH_WARNINGS`, at best.

To address this, I believe we need to expose a property to enable / disable skipping media inspection.
</blockquote></details>

Done.

___
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/JobController.java` line 434 at r10](https://reviewable.io/reviews/openmpf/openmpf/1614#-NP3adSP9xN_t8ECA0gQ:-NQjLbth1_zwTEFZrjWc:b-mc8wp6) ([raw file](https://github.com/openmpf/openmpf/blob/0edf9b53bfcecf1c906f07c8dbac685ca568b53d/trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/JobController.java#L434)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

In the description explain what the body of the request is and provide an example. It's not clear looking at the Swagger page.
</blockquote></details>

For the success field, I tried setting `@ApiModelProperty.example = "[1, 2, 3]"`, but on the Swagger page it showed up like `"success": "[1, 2, 3]"` instead of `"success": [1, 2, 3]`, so I am going to have to leave it as the default which is `"success": [0]`. I don't think we need to provide an example of something as basic as a list of numbers. I also tried to get the success field to be first, but Swagger is ignoring `@ApiModelProperty.position`.
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/JobConfigHasher.java` line 88 at r10](https://reviewable.io/reviews/openmpf/openmpf/1614#-NOQmHda8l8EKDER82uI:-NQfc8D51nNSoC0IMaV3:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/0edf9b53bfcecf1c906f07c8dbac685ca568b53d/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/JobConfigHasher.java#L88)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Since end users are likely to only ever run one piece of media at a time, it's not worth the effort to support the case where a user submits a single piece of media which matches one piece of media in a previously submitted job with multiple pieces of media.

I think we should leave a code comment explaining our decision to keep it simple.
</blockquote></details>

Done.
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/JobConfigHasher.java` line 176 at r10](https://reviewable.io/reviews/openmpf/openmpf/1614#-NPKa0212uTSHM9I0zvz:-NQfXHnD3BIRANrJFoPz:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/0edf9b53bfcecf1c906f07c8dbac685ca568b53d/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/JobConfigHasher.java#L176)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Right now `requiredByMediaTypes` takes precedence over `ignorableByAlgorithms`. I think that should be the other way around. For example, we may want to say that property P is required by all video actions except those for algorithm A. Right now we have no way to specify that easily. TBH though, I have not come up with a real use case for this. That just seems like how it should work.

Other than what I said in my other comment about wanting to, by default, ignore properties that aren't in an algorithm's `descriptor.json`, or in the common set, I'm not sure when we would want to manually specify ignoring an algorithm property unless it doesn't make sense for a certain kind of media. For example, maybe there is some algorithm B that supports property V for VIDEO and it doesn't make sense for AUDIO for that algorithm. If by default property V is ignored by all algorithms but B, we would only need to specify `requiredByMediaTypes=VIDEO` on it.

Maybe if two algorithms support a property with the same name in different ways we'd want to ignore it for one but not the other. For example:


| Algorithm| Ignored for VIDEO | Ignored for AUDIO |
| ----------- | ----------- | ----------- |
| X | No | Yes |
| Y | Yes | No |


One option would be to say that it's required by both media types and then make the`ignorableByAlgorithms` a tuple that specifies an algorithm and media type combination to be ignored, like `{X, AUDIO}` and `{Y, VIDEO}`. That ignorable tuple would take precedence over the required media types.

Honestly, this is in the weeds. It may be best to remove support for `ignorableByAlgorithms` to avoid confusion. We can add it in later when we have a use case. Speaking about confusion, see below.

---

Looking at what we have in `test-ignorable-properties.json`:

```json
    {
        "name": "FACECV_IMAGE_PROP",
        "requiredByMediaTypes": ["IMAGE"],
        "ignorableByAlgorithms": ["FACECV"]
    }
```

This seems odd. This means that all IMAGE jobs require this property no matter what, including FACECV, even though it's listed as an ignorable algorithm.

More generally, it's odd that FACECV is ignoring a "FACECV" IMAGE PROP (which implies it's defined in FACECV `descriptor.json`), but every other algorithm requires the "FACECV" prop. It would help to call this something like "NOT_APPLICABLE_TO_FACECV_FOR_NON_IMAGE_MEDIA_PROP".

Similarly, `FACECV_PROP` should be `NOT_APPLICABLE_TO_FACECV_PROP` and `MOG_PROP` should be `NOT_APPLICABLE_TO_MOG_PROP` for clarity.
</blockquote></details>

Done.
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/TiesDbBeforeJobCheckServiceImpl.java` line 217 at r10](https://reviewable.io/reviews/openmpf/openmpf/1614#-NOQez0A0qFEO5NQEx9M:-NQeGHet7CLOVoDuL5Rw:bu4u90v) ([raw file](https://github.com/openmpf/openmpf/blob/0edf9b53bfcecf1c906f07c8dbac685ca568b53d/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/TiesDbBeforeJobCheckServiceImpl.java#L217)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Maybe we should check for the TiesDb URL before media hash and mime type. That way the following code will evaluate to false and we don't try to check TiesDb later:

```java
        boolean shouldCheckTiesDbAfterMediaInspection
                = tiesDbCheckResult.status() == TiesDbCheckStatus.MEDIA_HASHES_ABSENT
                        || tiesDbCheckResult.status() == TiesDbCheckStatus.MEDIA_MIME_TYPES_ABSENT;
```
</blockquote></details>

This change resulted in a 38% performance improvement and a total of 172,997 nanoseconds saved. 🏎️💨
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/TiesDbBeforeJobCheckServiceImpl.java` line 295 at r10](https://reviewable.io/reviews/openmpf/openmpf/1614#-NOS3aOs1zQjscuY4689:-NQf_7zuCyTSXKRU2y5T:bulctwq) ([raw file](https://github.com/openmpf/openmpf/blob/0edf9b53bfcecf1c906f07c8dbac685ca568b53d/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/TiesDbBeforeJobCheckServiceImpl.java#L295)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

So a TiesDb assertion is created for each action in the pipeline and the `processDate` corresponds to `jobRequest.getTimeCompleted()`. That means all of the actions will have the same `COMPLETE_THEN_DATE` sort priority for that job. It doesn't really matter which one is selected by `max()` since they all have the same `outputUri` anyway.

It's worth ex [...]

2023-03-21 03:46 UTC, jrobble commented
*[`trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/service/TestTiesDbBeforeJobCheckService.java` line 118 at r12](https://reviewable.io/reviews/openmpf/openmpf/1614#-NR-ytrHCvprwl5jb7o-:-NR-ytrHCvprwl5jb7o0:b-bnwr9u) ([raw file](https://github.com/openmpf/openmpf/blob/bb9805609ec0d545dacfa9ffff2a8a6580f9b37f/trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/service/TestTiesDbBeforeJobCheckService.java#L118)):*
> ```Java
> 
> 
> public class TestTiesDbBeforeJobCheckService extends MockitoTest.Lenient {
> ```

Why is this lenient and not strict?


<!-- Sent from Reviewable.io -->

2023-03-21 03:46 UTC, jrobble commented
*[`trunk/workflow-manager/src/main/webapp/resources/mytheme/js/controllers/JobsCtrl.js` line 460 at r12](https://reviewable.io/reviews/openmpf/openmpf/1614#-NR-f9zy1KYY5XNmUKM0:-NR-f6hV008JwASNWViv:bofp54n) ([raw file](https://github.com/openmpf/openmpf/blob/bb9805609ec0d545dacfa9ffff2a8a6580f9b37f/trunk/workflow-manager/src/main/webapp/resources/mytheme/js/controllers/JobsCtrl.js#L460)):*
> ```JavaScript
>         }
>         else if (status === 'PAST JOB FOUND') {
>             return status + '\u{1f454}';
> ```

What's up with the necktie emoji?


<!-- Sent from Reviewable.io -->

2023-03-21 10:34 UTC, brosenberg42 reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1614)* status: 126 of 154 files reviewed, 44 unresolved discussions (waiting on @jrobble)

___
*[`trunk/workflow-manager/src/main/webapp/resources/mytheme/js/controllers/JobsCtrl.js` line 460 at r12](https://reviewable.io/reviews/openmpf/openmpf/1614#-NR-f9zy1KYY5XNmUKM0:-NR2glNh0mbOXSu7-Tyq:b-d6kmc9) ([raw file](https://github.com/openmpf/openmpf/blob/bb9805609ec0d545dacfa9ffff2a8a6580f9b37f/trunk/workflow-manager/src/main/webapp/resources/mytheme/js/controllers/JobsCtrl.js#L460)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

What's up with the necktie emoji?
</blockquote></details>

I can see how that is confusing. There should at least one more tie since it isn't called TieDb.
___
*[`trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/service/TestTiesDbBeforeJobCheckService.java` line 118 at r12](https://reviewable.io/reviews/openmpf/openmpf/1614#-NR-ytrHCvprwl5jb7o-:-NR2gqAA27CceexW5Pc3:b1xdey) ([raw file](https://github.com/openmpf/openmpf/blob/bb9805609ec0d545dacfa9ffff2a8a6580f9b37f/trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/service/TestTiesDbBeforeJobCheckService.java#L118)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Why is this lenient and not strict?
</blockquote></details>

It is not worth it to go back and re-write a bunch of tests just to use `MockitoTest.Strict`. `MockitoTest.Strict` is nice because you don't need most `verify(mock)` calls, but this test already has the verify calls in it. I added both `MockitoTest.Strict` and `MockitoTest.Lenient`, so we could use whichever one was more convenient for a given test class. If I was writing new tests I would start with `MockitoTest.Strict`, but might switch to `MockitoTest.Lenient` if it lead to cleaner tests.


<!-- Sent from Reviewable.io -->

2023-04-04 02:58 UTC, jrobble requested changes
> Reviewed 11 of 25 files at r11, 9 of 11 files at r12, 11 of 14 files at r13, 1 of 1 files at r14, 3 of 4 files at r15, 1 of 1 files at r16, 6 of 6 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1614)* status: all files reviewed, 4 unresolved discussions (waiting on @brosenberg42)

*[a discussion](https://reviewable.io/reviews/openmpf/openmpf/1614#-NPJRL2476Np0mKQxZYn:-NRsr_WR3wfUGuy0yqDq:b-6qb86e) (no related file):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

I put it in the existing TiesDb status column.
</blockquote></details>

Usually when a job ends in `COMPLETE_WITH_ERRORS` or `COMPLETE_WITH_WARNINGS` the `errors` or `warnings` collection in the JSON output object has an entry. I'm wondering if the job status should just be `ERROR` in this case since nothing completed.

Interestingly, while debugging, I do see that this code is executed:

```java
            jobRequest.setTiesDbStatus("COPY ERROR: " + msg);
            _inProgressJobs.addJobError(
                    job.getId(),
                    IssueCodes.TIES_DB_BEFORE_JOB_CHECK,
                    msg);
```

___
___
*[`trunk/mpf-rest-api/src/main/java/org/mitre/mpf/rest/api/TiesDbRepostResponse.java` line 10 at r10](https://reviewable.io/reviews/openmpf/openmpf/1614#-NOAmcUCEpIWCypz7jVx:-NR3kpjMAUy6L8JchrAY:bscpzvt) ([raw file](https://github.com/openmpf/openmpf/blob/0edf9b53bfcecf1c906f07c8dbac685ca568b53d/trunk/mpf-rest-api/src/main/java/org/mitre/mpf/rest/api/TiesDbRepostResponse.java#L10)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

It looks correct to me.
</blockquote></details>

My mistake. I realize now that you're defining a record within a record.
___
*[`trunk/workflow-manager/pom.xml` line 48 at r10](https://reviewable.io/reviews/openmpf/openmpf/1614#-NOAp29e29Td3DqRx4mR:-NQkCnTuBrMV3JjFyIMc:b-isxvz5) ([raw file](https://github.com/openmpf/openmpf/blob/0edf9b53bfcecf1c906f07c8dbac685ca568b53d/trunk/workflow-manager/pom.xml#L48)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

It's for a code coverage plugin.
</blockquote></details>

It's worth leaving a comment explaining that, and which plugin if we remember.
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/JobController.java` line 434 at r10](https://reviewable.io/reviews/openmpf/openmpf/1614#-NP3adSP9xN_t8ECA0gQ:-NRsWoNw6jadKEky7VNF:bnyzz1d) ([raw file](https://github.com/openmpf/openmpf/blob/0edf9b53bfcecf1c906f07c8dbac685ca568b53d/trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/JobController.java#L434)):*
It's not clear to the user what they need to provide if all they see for the input example is:

```
[
  0
]
```

Thanks for trying to fix the output example.

Please set the `@ApiOperation` `notes` field to the following (similar to what we do for `/rest/jobs`):

> Provide a list of job ids as input. For example: `[0, 12, 35]`. The output will contain a list of failures along with a list of successes. Each failure will contain the job id and associated error message. The success list will only contain the job ids.
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/JobConfigHasher.java` line 106 at r10](https://reviewable.io/reviews/openmpf/openmpf/1614#-NOBIzMFBR9LYxoRY-O6:-NRsak_m8k7bhVmV8pq9:bidee51) ([raw file](https://github.com/openmpf/openmpf/blob/0edf9b53bfcecf1c906f07c8dbac685ca568b53d/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/JobConfigHasher.java#L106)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

We need to update every component to add an `outputVersion=1.0`. If it's not there in the `descriptor.json` I'm not going to remember to update it. We also need to update the [doc](https://openmpf.github.io/docs/site/Component-Descriptor-Reference/index.html) to explain what it is and when to update it.

I feel like it will be easier to remember to update it if we get in the habit of updating the `componentVersion` for each component whenever there is a change. I see no reason why that necessarily has to match the Docker tag, other than to avoid user confusion.

If showing different versions on the Component Registration page in the web UI will be too confusing, I think we can use the `middlewareVersion` field to populate the `Version` column in the table on that page. Basically, the whole point of that field is to represent compatibility, which is the only thing I imagine that the user does currently when looking at the table on that page. We can always keep the `middlewareVersion` and Docker tag in sync.

Better yet, we can update the table so that instead of a just a `Version` column, we instead have a `Compatibility Version` column and `Component Version` column to represent the `middlewareVersion` and `componentVersion` respectively. Maybe even have a column for `outputVersion`.

We don't need to make any of the versioning changes in this PR. If you agree with what I proposed above, we can create a separate issue for it.  
</blockquote></details>

Here's the separate issue: https://github.com/openmpf/openmpf/issues/1656
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/TiesDbBeforeJobCheckServiceImpl.java` line 429 at r10](https://reviewable.io/reviews/openmpf/openmpf/1614#-NP3m18Y8UL9jK7ythuU:-NR-h3GX1PbowzSPMujO:byxe2a7) ([raw file](https://github.com/openmpf/openmpf/blob/0edf9b53bfcecf1c906f07c8dbac685ca568b53d/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/TiesDbBeforeJobCheckServiceImpl.java#L429)):*
> we need to create a new a output object. We would also have to upload that output object to S3, but the user told us they don't want the results copied

If I run two of the same jobs back to back with the following job properties:

```
    "TIES_DB_URL": "https://tiesdb.somewhere",
    "S3_RESULTS_BUCKET": "http://localhost:9090/results",
    "S3_ACCESS_KEY": "minio",
    "S3_SECRET_KEY": "minio123"
```

Each job results in a new JSON output object being uploaded to S3. Is this intentional? They are exactly the same except for the value of the `jobId` field.
___
*[`trunk/workflow-manager/src/main/resources/properties/mpf.properties` line 460 at r14](https://reviewable.io/reviews/openmpf/openmpf/1614#-NR9O_eH7JBqU3YyOGBe:-NR9O_eH7JBqU3YyOGBf:b-s8dhcp) ([raw file](https://github.com/openmpf/openmpf/blob/f3b15f29e922131bb6db97d927091bcd2c2a33ac/trunk/workflow-manager/src/main/resources/properties/mpf.properties#L460)):*
> ```INI
> 
> ties.db.url=
> ties.db.skip.check=true
> ```

I think we should set this to false by default. If the user provides a `TIES_DB_URL` then I think it's safe to assume that they want to use TiesDb in its entirety, which means checking for jobs and uploading results.
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/HttpClientUtils.java` line 177 at r10](https://reviewable.io/reviews/openmpf/openmpf/1614#-NOBhrSC5ZPqEhdCJQOy:-NRt132b3-0w20R9S8-Q:bipicsn) ([raw file](https://github.com/openmpf/openmpf/blob/0edf9b53bfcecf1c906f07c8dbac685ca568b53d/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/HttpClientUtils.java#L177)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

We can't change the meaning of existing properties without a major release. 

I don't understand the change from `detection.http.retry` to ` detection.connection.http.retry`. I don't think people really want different settings based on whether the error was connection issue or an error status code. I think it will just be confusing. HTTP/3 and QUIC don't use TCP which will only further add to the confusion.
</blockquote></details>

Let's ignore the `detection.http.retry` vs. `detection.connection.http.retry` thing. It doesn't add much.

I created a separate task for the next major release to rename `http.callback.*` system properties to `http.re [...]

2023-04-04 12:12 UTC, brosenberg42 reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1614)* status: 153 of 157 files reviewed, 4 unresolved discussions (waiting on @jrobble)

*[a discussion](https://reviewable.io/reviews/openmpf/openmpf/1614#-NPJRL2476Np0mKQxZYn:-NSB3SU8-pKiL4UDPcWF:b-896fix) (no related file):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Usually when a job ends in `COMPLETE_WITH_ERRORS` or `COMPLETE_WITH_WARNINGS` the `errors` or `warnings` collection in the JSON output object has an entry. I'm wondering if the job status should just be `ERROR` in this case since nothing completed.

Interestingly, while debugging, I do see that this code is executed:

```java
            jobRequest.setTiesDbStatus("COPY ERROR: " + msg);
            _inProgressJobs.addJobError(
                    job.getId(),
                    IssueCodes.TIES_DB_BEFORE_JOB_CHECK,
                    msg);
```

</blockquote></details>

Done.

___
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/JobController.java` line 434 at r10](https://reviewable.io/reviews/openmpf/openmpf/1614#-NP5iZ0X2b0jaAv6uQra:-NS5qteV9Hx16IKTh2jj:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/0edf9b53bfcecf1c906f07c8dbac685ca568b53d/trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/JobController.java#L434)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

We need to update the REST API doc. to include this exposed endpoint.
</blockquote></details>

Done.
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/JobController.java` line 434 at r10](https://reviewable.io/reviews/openmpf/openmpf/1614#-NP3adSP9xN_t8ECA0gQ:-NSB-1xh2PLopn5wCfZa:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/0edf9b53bfcecf1c906f07c8dbac685ca568b53d/trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/JobController.java#L434)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

It's not clear to the user what they need to provide if all they see for the input example is:

```
[
  0
]
```

Thanks for trying to fix the output example.

Please set the `@ApiOperation` `notes` field to the following (similar to what we do for `/rest/jobs`):

> Provide a list of job ids as input. For example: `[0, 12, 35]`. The output will contain a list of failures along with a list of successes. Each failure will contain the job id and associated error message. The success list will only contain the job ids.
</blockquote></details>

Done.
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/enums/MpfConstants.java` line 96 at r10](https://reviewable.io/reviews/openmpf/openmpf/1614#-NOBZQQm5xeHV-iXrusU:-NS5qyPv7NdiU5P2Xj73:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/0edf9b53bfcecf1c906f07c8dbac685ca568b53d/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/enums/MpfConstants.java#L96)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

We should write a TiesDb Guide in the github.io docs that explains the various settings, like the Object Storage Guide. It also needs to explain the format of `ties-db-check-ignorable-props.json`.
</blockquote></details>

Done.
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/TiesDbBeforeJobCheckServiceImpl.java` line 429 at r10](https://reviewable.io/reviews/openmpf/openmpf/1614#-NP3m18Y8UL9jK7ythuU:-NSB1nBM3FD6Yu6vyh7u:bq2u2vj) ([raw file](https://github.com/openmpf/openmpf/blob/0edf9b53bfcecf1c906f07c8dbac685ca568b53d/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/TiesDbBeforeJobCheckServiceImpl.java#L429)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

> we need to create a new a output object. We would also have to upload that output object to S3, but the user told us they don't want the results copied

If I run two of the same jobs back to back with the following job properties:

```
    "TIES_DB_URL": "https://tiesdb.somewhere",
    "S3_RESULTS_BUCKET": "http://localhost:9090/results",
    "S3_ACCESS_KEY": "minio",
    "S3_SECRET_KEY": "minio123"
```

Each job results in a new JSON output object being uploaded to S3. Is this intentional? They are exactly the same except for the value of the `jobId` field.
</blockquote></details>

`ties.db.s3.copy.disabled` defaults to false, so that is the correct behavior.
___
*[`trunk/workflow-manager/src/main/resources/properties/mpf.properties` line 460 at r14](https://reviewable.io/reviews/openmpf/openmpf/1614#-NR9O_eH7JBqU3YyOGBe:-NSAyVxP-5nvNzPqcsK8:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/f3b15f29e922131bb6db97d927091bcd2c2a33ac/trunk/workflow-manager/src/main/resources/properties/mpf.properties#L460)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I think we should set this to false by default. If the user provides a `TIES_DB_URL` then I think it's safe to assume that they want to use TiesDb in its entirety, which means checking for jobs and uploading results.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-04-05 02:36 UTC, jrobble requested changes
> Reviewed 4 of 4 files at r18, 1 of 1 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1614)* status: all files reviewed, 1 unresolved discussion (waiting on @brosenberg42)

___
*[`trunk/workflow-manager/pom.xml` line 48 at r19](https://reviewable.io/reviews/openmpf/openmpf/1614#-NSBwxUz9VLEW2XwPmXW:-NSBwxV-0QwRnlWau6HC:ba16v7t) ([raw file](https://github.com/openmpf/openmpf/blob/0cee6d47f0c0ca1e77cb5bf930993c84c967a80a/trunk/workflow-manager/pom.xml#L48)):*
> ```XML
>         <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
>         <wfm.port>8080</wfm.port>
>         <!--
> ```

Good intel!
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/JobController.java` line 455 at r19](https://reviewable.io/reviews/openmpf/openmpf/1614#-NSBxPmg0Ff2Xc0vN25Y:-NSBxPmiEZ7mzcHJ96xd:bqm779l) ([raw file](https://github.com/openmpf/openmpf/blob/0cee6d47f0c0ca1e77cb5bf930993c84c967a80a/trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/JobController.java#L455)):*
> ```Java
>             value = "Retry posting job results to TiesDB.",
>             notes = """
>                 Provide a list of job ids as input. For example: `[1, 12, 35]`. The output will \
> ```

Good catch. 0 is not a valid job id.
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/TiesDbBeforeJobCheckServiceImpl.java` line 429 at r10](https://reviewable.io/reviews/openmpf/openmpf/1614#-NP3m18Y8UL9jK7ythuU:-NSBzE1wEcvkRSJgzZnU:b-hncugn) ([raw file](https://github.com/openmpf/openmpf/blob/0edf9b53bfcecf1c906f07c8dbac685ca568b53d/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/TiesDbBeforeJobCheckServiceImpl.java#L429)):*
I'm looking at the property description:

> When true and a job is skipped because a compatible job is found in TiesDb, the results from the previous job will not be copied to a **different S3 bucket**.

In the example I provided above it's the same S3 bucket. In my mind, not using S3 - that is, using local object storage - is similar to using the same S3 bucket: it's not necessary to create a copy of the JSON output in the same location as the previous output.

Just thinking out loud. If you think otherwise please let me know.


<!-- Sent from Reviewable.io -->

2023-04-05 11:58 UTC, brosenberg42 reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1614)* status: all files reviewed, 1 unresolved discussion (waiting on @jrobble)

___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/TiesDbBeforeJobCheckServiceImpl.java` line 429 at r10](https://reviewable.io/reviews/openmpf/openmpf/1614#-NP3m18Y8UL9jK7ythuU:-NSG8izP1RPWwq-lbXX0:bgpp2f9) ([raw file](https://github.com/openmpf/openmpf/blob/0edf9b53bfcecf1c906f07c8dbac685ca568b53d/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/TiesDbBeforeJobCheckServiceImpl.java#L429)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I'm looking at the property description:

> When true and a job is skipped because a compatible job is found in TiesDb, the results from the previous job will not be copied to a **different S3 bucket**.

In the example I provided above it's the same S3 bucket. In my mind, not using S3 - that is, using local object storage - is similar to using the same S3 bucket: it's not necessary to create a copy of the JSON output in the same location as the previous output.

Just thinking out loud. If you think otherwise please let me know.
</blockquote></details>

Regarding "different S3 bucket", documentation should explain the intended use of a feature. Explaining ways of using a feature that don't make sense only makes the documentation longer and harder to understand. 

Updating the output object is necessary to make the behavior consistent and easy to understand.  "If S3 copy is enabled, a new output object is generated." is easier to understand than "If S3 copy is enabled and you don't do something that doesn't make sense, then a new output object is created." The desciption of tiesDbSourceJobId also becomes more complicated in the same way.

The situation you are describing is unlikely to happen and only occurs when a user a is not using a feature correctly. The current behavior is still correct and allows the user to access the correct output. If the job would fail or WFM would do something wrong, then I would agree we should change the behavior to protect the user, but that isn't the situation we are in. You are suggesting that we should make the code and documentation more complicated to save the user a small amount of processing time when they do something that doesn't make sense.


<!-- Sent from Reviewable.io -->

2023-04-10 20:18 UTC, jrobble requested changes
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1614)* status: all files reviewed, 1 unresolved discussion (waiting on @brosenberg42)

___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/TiesDbBeforeJobCheckServiceImpl.java` line 429 at r10](https://reviewable.io/reviews/openmpf/openmpf/1614#-NP3m18Y8UL9jK7ythuU:-NSgmWU9-8rktV0k9BUf:bb6ujgj) ([raw file](https://github.com/openmpf/openmpf/blob/0edf9b53bfcecf1c906f07c8dbac685ca568b53d/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/TiesDbBeforeJobCheckServiceImpl.java#L429)):*
I think we should add the following line to the end of the `TIES_DB_S3_COPY_DISABLED` description:

> Copying results will always result in a new JSON output object, even if using the same S3 location as the previous job.

Also, an end user has asked that we change `TIES_DB_S3_COPY_DISABLED` to `TIES_DB_S3_COPY_ENABLED`.


<!-- Sent from Reviewable.io -->

2023-04-11 11:34 UTC, brosenberg42 reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1614)* status: 145 of 157 files reviewed, 1 unresolved discussion (waiting on @jrobble)

___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/TiesDbBeforeJobCheckServiceImpl.java` line 429 at r10](https://reviewable.io/reviews/openmpf/openmpf/1614#-NP3m18Y8UL9jK7ythuU:-NSk5EBcA_EvZH98ivdY:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/0edf9b53bfcecf1c906f07c8dbac685ca568b53d/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/TiesDbBeforeJobCheckServiceImpl.java#L429)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I think we should add the following line to the end of the `TIES_DB_S3_COPY_DISABLED` description:

> Copying results will always result in a new JSON output object, even if using the same S3 location as the previous job.

Also, an end user has asked that we change `TIES_DB_S3_COPY_DISABLED` to `TIES_DB_S3_COPY_ENABLED`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-04-12 22:04 UTC, jrobble approved these changes
> Reviewed 12 of 12 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1614)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @brosenberg42)



<!-- Sent from Reviewable.io -->

2023-04-18 15:17 UTC, merged