Feat/wfm trigger
openmpf/openmpf pull request #1644
Opened 2023-02-10 17:08 UTC by brosenberg42

**Issues:**
- https://github.com/openmpf/openmpf/issues/1574
- https://github.com/openmpf/openmpf/issues/1642

2023-07-03 17:14 UTC, jrobble requested changes
> Reviewed 2 of 41 files at r1, 39 of 39 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1644)* status: all files reviewed, 18 unresolved discussions (waiting on @brosenberg42)

*[a discussion](https://reviewable.io/reviews/openmpf/openmpf/1644#-NYUnFbAAM3KkRw9kf_f:-NYUnFbAAM3KkRw9kf_g:b-bu1lun) (no related file):*
There are still four files with `private AutoCloseable _closeable;` in them.

___
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/entities/persistent/MediaImpl.java` line 32 at r2](https://reviewable.io/reviews/openmpf/openmpf/1644#-NZRG7d2C5g7de4-weMs:-NZRG7d7DjqsrzRSSDLa:bysl4rx) ([raw file](https://github.com/openmpf/openmpf/blob/f6a51a81af754955d0f85cb04712b44f4d7f1d21/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/entities/persistent/MediaImpl.java#L32)):*
> ```Java
> import com.fasterxml.jackson.annotation.JsonIgnore;
> import com.fasterxml.jackson.annotation.JsonProperty;
> import com.google.common.collect.HashMultimap;
> ```

Unused:

```
import com.google.common.collect.HashMultimap;

import com.google.common.collect.Multimap;
```
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/enums/MpfConstants.java` line 105 at r2](https://reviewable.io/reviews/openmpf/openmpf/1644#-NYUdw-D8yDJ_7nwVN4H:-NYUdw-D8yDJ_7nwVN4I:bayb7e3) ([raw file](https://github.com/openmpf/openmpf/blob/9bc681d668ed8254aaeb03bcdcf062696a8949bb/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/enums/MpfConstants.java#L105)):*
> ```Java
>             FFPROBE_IGNORE_STDERR = "FFPROBE_IGNORE_STDERR",
>             FFPROBE_STDERR_NUM_LINES = "FFPROBE_STDERR_NUM_LINES",
>             TRIGGER = "TRIGGER";
> ```

Needs github.io documentation.
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/segmenting/AudioMediaSegmenter.java` line 44 at r2](https://reviewable.io/reviews/openmpf/openmpf/1644#-NZRgwy0AOyYiUIktD6l:-NZRgwy26Z2MI3iraDsd:b-ciom25) ([raw file](https://github.com/openmpf/openmpf/blob/f6a51a81af754955d0f85cb04712b44f4d7f1d21/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/segmenting/AudioMediaSegmenter.java#L44)):*
> ```Java
> 
> import javax.inject.Inject;
> import java.util.ArrayList;
> ```

Unused.
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/segmenting/DefaultMediaSegmenter.java` line 42 at r2](https://reviewable.io/reviews/openmpf/openmpf/1644#-NZRh2UL0ch8FUV-Qs3l:-NZRh2UL0ch8FUV-Qs3m:b-ciom25) ([raw file](https://github.com/openmpf/openmpf/blob/f6a51a81af754955d0f85cb04712b44f4d7f1d21/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/segmenting/DefaultMediaSegmenter.java#L42)):*
> ```Java
> 
> import javax.inject.Inject;
> import java.util.ArrayList;
> ```

Unused.
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/segmenting/ImageMediaSegmenter.java` line 40 at r2](https://reviewable.io/reviews/openmpf/openmpf/1644#-NZRh8h04K6BXC5z4OIk:-NZRh8h04K6BXC5z4OIl:b-ciom25) ([raw file](https://github.com/openmpf/openmpf/blob/f6a51a81af754955d0f85cb04712b44f4d7f1d21/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/segmenting/ImageMediaSegmenter.java#L40)):*
> ```Java
> 
> import javax.inject.Inject;
> import java.util.ArrayList;
> ```

Unused.
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/segmenting/TriggerProcessor.java` line 8 at r2](https://reviewable.io/reviews/openmpf/openmpf/1644#-NYUcEOkCJDw5YmUdAsP:-NYUcEOkCJDw5YmUdAsQ:b-7a7ao8) ([raw file](https://github.com/openmpf/openmpf/blob/9bc681d668ed8254aaeb03bcdcf062696a8949bb/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/segmenting/TriggerProcessor.java#L8)):*
> ```Java
>  * 52.227-14, Alt. IV (DEC 2007).                                             *
>  *                                                                            *
>  * Copyright 2022 The MITRE Corporation. All Rights Reserved.                 *
> ```

Update copyright year in header blocks.
___
*[`trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/camelOps/TestDetectionResponseProcessor.java` line 73 at r2](https://reviewable.io/reviews/openmpf/openmpf/1644#-NZRhaCuAZ8RKfr4mzoy:-NZRhaCv9aHVdRaBMv5Q:b-z6ca6p) ([raw file](https://github.com/openmpf/openmpf/blob/9bc681d668ed8254aaeb03bcdcf062696a8949bb/trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/camelOps/TestDetectionResponseProcessor.java#L73)):*
> ```Java
> import org.mitre.mpf.wfm.util.FrameTimeInfo;
> import org.mitre.mpf.wfm.util.IoUtils;
> import org.mitre.mpf.wfm.util.JsonUtils;
> ```

These aren't used:

```
import org.mitre.mpf.wfm.util.JsonUtils;
import org.mitre.mpf.wfm.util.ObjectMapperFactory;
```
___
*[`trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/camelOps/TestDetectionTaskSplitter.java` line 969 at r2](https://reviewable.io/reviews/openmpf/openmpf/1644#-NZRSvy7E7QDiXDjAGwo:-NZRSvy7E7QDiXDjAGwp:b-c82vys) ([raw file](https://github.com/openmpf/openmpf/blob/9bc681d668ed8254aaeb03bcdcf062696a8949bb/trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/camelOps/TestDetectionTaskSplitter.java#L969)):*
> ```Java
> 
> 
>         // parent only
> ```

Please consider using the following:

```
        // nothing run yet
        job.setCurrentTaskIndex(0);
        Assert.assertEquals(-1, detectionSplitter.getLastProcessedTaskIndex(job, parentMedia));
        Assert.assertEquals(-1, detectionSplitter.getLastProcessedTaskIndex(job, childMedia1));
        Assert.assertEquals(-1, detectionSplitter.getLastProcessedTaskIndex(job, childMedia2));

        // after parent only extraction
        job.setCurrentTaskIndex(1);
        Assert.assertEquals(0, detectionSplitter.getLastProcessedTaskIndex(job, parentMedia));
        Assert.assertEquals(-1, detectionSplitter.getLastProcessedTaskIndex(job, childMedia1));
        Assert.assertEquals(-1, detectionSplitter.getLastProcessedTaskIndex(job, childMedia2));

        // after parent only detection
        job.setCurrentTaskIndex(2);
        Assert.assertEquals(1, detectionSplitter.getLastProcessedTaskIndex(job, parentMedia));
        Assert.assertEquals(-1, detectionSplitter.getLastProcessedTaskIndex(job, childMedia1));
        Assert.assertEquals(-1, detectionSplitter.getLastProcessedTaskIndex(job, childMedia2));

        // after child only detection
        job.setCurrentTaskIndex(3);
        Assert.assertEquals(1, detectionSplitter.getLastProcessedTaskIndex(job, parentMedia));
        Assert.assertEquals(2, detectionSplitter.getLastProcessedTaskIndex(job, childMedia1));
        Assert.assertEquals(2, detectionSplitter.getLastProcessedTaskIndex(job, childMedia2));

        // after parent and child detection
        job.setCurrentTaskIndex(4);
        Assert.assertEquals(3, detectionSplitter.getLastProcessedTaskIndex(job, parentMedia));
        Assert.assertEquals(3, detectionSplitter.getLastProcessedTaskIndex(job, childMedia1));
        Assert.assertEquals(3, detectionSplitter.getLastProcessedTaskIndex(job, childMedia2));
```

Among other things, I added the last section for task 4.
___
*[`trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/segmenting/TestTriggerProcessor.java` line 8 at r2](https://reviewable.io/reviews/openmpf/openmpf/1644#-NYUcMCz1S3JIydoRYh_:-NYUcMCz1S3JIydoRYha:b-7a7ao8) ([raw file](https://github.com/openmpf/openmpf/blob/9bc681d668ed8254aaeb03bcdcf062696a8949bb/trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/segmenting/TestTriggerProcessor.java#L8)):*
> ```Java
>  * 52.227-14, Alt. IV (DEC 2007).                                             *
>  *                                                                            *
>  * Copyright 2022 The MITRE Corporation. All Rights Reserved.                 *
> ```

Update copyright year in header blocks.
___
*[`trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/segmenting/TestTriggerProcessor.java` line 125 at r2](https://reviewable.io/reviews/openmpf/openmpf/1644#-NZR-gP-8UDSHtjchsok:-NZR-gP-8UDSHtjchsol:b-o7dxwx) ([raw file](https://github.com/openmpf/openmpf/blob/ [...]

2023-07-18 17:57 UTC, brosenberg42 reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1644)* status: 29 of 46 files reviewed, 18 unresolved discussions (waiting on @brosenberg42 and @jrobble)

___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/enums/MpfConstants.java` line 105 at r2](https://reviewable.io/reviews/openmpf/openmpf/1644#-NYUdw-D8yDJ_7nwVN4H:-N_e5Rh86EzXoDO_X2Nk:b-xxcdwj) ([raw file](https://github.com/openmpf/openmpf/blob/9bc681d668ed8254aaeb03bcdcf062696a8949bb/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/enums/MpfConstants.java#L105)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Needs github.io documentation.
</blockquote></details>

Where?


<!-- Sent from Reviewable.io -->

2023-07-26 21:50 UTC, jrobble requested changes
> Reviewed 10 of 11 files at r3, 7 of 8 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1644)* status: all files reviewed, 7 unresolved discussions (waiting on @brosenberg42)

*[a discussion](https://reviewable.io/reviews/openmpf/openmpf/1644#-NYUnFbAAM3KkRw9kf_f:-NaE-3IzESVJYqLU5ddm:beylz4t) (no related file):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

I was only able to find 3.
</blockquote></details>

I may have had an extra .orig file due to a merge. I don't see any in your most recent commit.

___
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/TrackOutputHelper.java` line 83 at r5](https://reviewable.io/reviews/openmpf/openmpf/1644#-NaJ0tuT-y17qPrgXL5d:-NaJ0tuT-y17qPrgXL5e:bjaoth5) ([raw file](https://github.com/openmpf/openmpf/blob/8a86ae10ceaa392c863781492a620a12ceacd447/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/TrackOutputHelper.java#L83)):*
> ```Java
>         boolean isSuppressed = isSuppressed(job, media, taskIdx);
>         boolean isMergeTarget = isMergeTarget(job, media, taskIdx);
>         boolean needToCheckTrackTriggers
> ```

Should we call the variable `needToCheckSuppressedTriggers` and the method `needToCheckTriggers()`? The variable has something to do with track suppression because of `isSuppressed &&`, while the method does not.
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/TrackOutputHelper.java` line 170 at r5](https://reviewable.io/reviews/openmpf/openmpf/1644#-NaJ0j1o3xnvdJQcUVNZ:-NaJ0j1o3xnvdJQcUVN_:b-gvcghg) ([raw file](https://github.com/openmpf/openmpf/blob/8a86ae10ceaa392c863781492a620a12ceacd447/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/TrackOutputHelper.java#L170)):*
> ```Java
> 
> 
>     private boolean needToCheckSuppressedTriggers(BatchJob job, Media media, int taskIdx) {
> ```

Should we just call this `needToCheckTriggers()`? I don't see what this method itself has to do with track suppression.
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/TrackOutputHelper.java` line 223 at r5](https://reviewable.io/reviews/openmpf/openmpf/1644#-NaE6Yt9DouUWyLbV20L:-NaE6YtA-NQCWv_B36rC:b-f4im3s) ([raw file](https://github.com/openmpf/openmpf/blob/8a86ae10ceaa392c863781492a620a12ceacd447/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/TrackOutputHelper.java#L223)):*
> ```Java
>         }
>         else {
>             return taskCount - 2;
> ```

Do you do this because the only non-DETECTION algorithm is MARKUP?

I'm wondering if it would be better to iterate backwards until we find a DETECTION algorithm just in case we ever start supporting other non-DETECTION algorithms.

Minimally, leave a comment here explaining that the only non-DETECTION algorithm is MARKUP.
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/RedisImpl.java` line 121 at r5](https://reviewable.io/reviews/openmpf/openmpf/1644#-NaE5QqR8krKIcMoGfaS:-NaE5QqT8-YlktFpb2af:b-pywcei) ([raw file](https://github.com/openmpf/openmpf/blob/8a86ae10ceaa392c863781492a620a12ceacd447/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/RedisImpl.java#L121)):*
> ```Java
>     public synchronized Optional<String> getTrackType(
>             long jobId, long mediaId, int taskIndex, int actionIndex) {
>         var tracks = getTrackListOps(jobId, mediaId, taskIndex, actionIndex);
> ```

This isn't a track at this point. Consider calling it `trackListOps` instead.
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/enums/MpfConstants.java` line 105 at r2](https://reviewable.io/reviews/openmpf/openmpf/1644#-NYUdw-D8yDJ_7nwVN4H:-NaE-Th978Ii7uyQbr_c:b-39jnl0) ([raw file](https://github.com/openmpf/openmpf/blob/9bc681d668ed8254aaeb03bcdcf062696a8949bb/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/enums/MpfConstants.java#L105)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

Where?
</blockquote></details>

I think it's worth creating a Trigger Guide to explain the motivation, WFM properties, and provide some examples, similar to the Feed Forward Guide. It doesn't have to be long. I just think there is enough to talk about to warrant a separate guide, and the content doesn't fit anywhere else.
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/segmenting/TriggerProcessor.java` line 51 at r5](https://reviewable.io/reviews/openmpf/openmpf/1644#-NaE7efE2Bwk2VspuhH5:-NaE7efF3KKkLjZaNY87:blxj4wy) ([raw file](https://github.com/openmpf/openmpf/blob/8a86ae10ceaa392c863781492a620a12ceacd447/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/segmenting/TriggerProcessor.java#L51)):*
> ```Java
> public class TriggerProcessor {
> 
>     public static final Predicate<Track> ALL_MATCH = t -> true;
> ```

I don't think this needs to be public.
___
*[`trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/segmenting/TestTriggerProcessor.java` line 125 at r2](https://reviewable.io/reviews/openmpf/openmpf/1644#-NZR-gP-8UDSHtjchsok:-NaDoH-X6wSzvh5JU3Ye:bdmfh1b) ([raw file](https://github.com/openmpf/openmpf/blob/9bc681d668ed8254aaeb03bcdcf062696a8949bb/trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/segmenting/TestTriggerProcessor.java#L125)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

It is testing the case where there are no input tracks to test against the trigger.
</blockquote></details>

Okay, I get it now.
___
*[`trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/segmenting/TestTriggerProcessor.java` line 138 at r2](https://reviewable.io/reviews/openmpf/openmpf/1644#-NZ7AT70D6DYoQd2_LCv:-NaDopN45PllQiFUPfLv:b-d6hri2) ([raw file](https://github.com/openmpf/openmpf/blob/9bc681d668ed8254aaeb03bcdcf062696a8949bb/trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/segmenting/TestTriggerProcessor.java#L138)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

As I mention in the method name, this is a test for handling jobs with no triggers at all. We can't check for `TriggerProcessor.getTracks()`. `TriggerProcessor` is the class we are testing. It is not a mock. 
Since this is a unit test for TriggerProcessor it is safe to assume everything is related to triggers. The other uses for `InProgressJobs.getTracksStream()` are not relevent in a unit test.

</blockquote></details>

I was thinking that you can verify that `TriggerProcessor.getTracks()` is never called (you're currently verifying that `InProgressJobs.getTracksStream()` is never called), but as you said, it's not a mock so that's not an option without doing something like `Mockito.spy()`.

Looking more closely at how these tests are structured, the only way `InProgressJobs.getTracksStream()` is called is through `TriggerProcessor.getTracks()`. My initial concern is that maybe sometime in the future we call `InProgressJobs.getTracksStream()` for some other reason not related to triggers. In that case, one of two things can happen. First, it won't matter since that code flow is not executed as part of this test. Second, it will be executed and this test will fail. If the latter, we can simply update this test.
___
*[`trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/segmenting/TestTriggerProcessor.java` line 206 at r2](https://reviewable.io/reviews/openmpf/openmpf/1644#-NZ7WK2Y25OWDfPxv_XJ:-NaDwUo9A7GCuGw_ZA8-:b-oce464) ([raw file](https://github.com/openmpf/openmpf/blob/9bc681d668ed8254aaeb03bcdcf062696a8949bb/trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/segmenting/TestTriggerProcessor.java#L206)):*
> Middle refers to the median of the task indices.

Since the indices are 0, 1, 2, 3, and 4, I assume you're referring to index 2, which would mean the "no trigger" is the same as the ALL_MATCH trigger (both blank and null trigger property represent ALL_MATCH).

A line-ending comment could help here:

```java
.setTrigger("", 2)  // blank is the sa [...]

2023-07-26 21:53 UTC, jrobble commented
*[`trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/segmenting/TestTriggerProcessor.java` line 138 at r2](https://reviewable.io/reviews/openmpf/openmpf/1644#-NZ7AT70D6DYoQd2_LCv:-NaJBKoZBbRR3v7dqSaK:bubpmo0) ([raw file](https://github.com/openmpf/openmpf/blob/9bc681d668ed8254aaeb03bcdcf062696a8949bb/trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/segmenting/TestTriggerProcessor.java#L138)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I was thinking that you can verify that `TriggerProcessor.getTracks()` is never called (you're currently verifying that `InProgressJobs.getTracksStream()` is never called), but as you said, it's not a mock so that's not an option without doing something like `Mockito.spy()`.

Looking more closely at how these tests are structured, the only way `InProgressJobs.getTracksStream()` is called is through `TriggerProcessor.getTracks()`. My initial concern is that maybe sometime in the future we call `InProgressJobs.getTracksStream()` for some other reason not related to triggers. In that case, one of two things can happen. First, it won't matter since that code flow is not executed as part of this test. Second, it will be executed and this test will fail. If the latter, we can simply update this test.

</blockquote></details>

So to be clear, I'm not asking you to do anything here.


<!-- Sent from Reviewable.io -->

2023-07-31 17:53 UTC, brosenberg42 reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1644)* status: 43 of 46 files reviewed, 7 unresolved discussions (waiting on @jrobble)

___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/TrackOutputHelper.java` line 83 at r5](https://reviewable.io/reviews/openmpf/openmpf/1644#-NaJ0tuT-y17qPrgXL5d:-NaMumZq8ENX3ZS9K3MV:b-tukx5j) ([raw file](https://github.com/openmpf/openmpf/blob/8a86ae10ceaa392c863781492a620a12ceacd447/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/TrackOutputHelper.java#L83)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Should we call the variable `needToCheckSuppressedTriggers` and the method `needToCheckTriggers()`? The variable has something to do with track suppression because of `isSuppressed &&`, while the method does not.
</blockquote></details>

They are both related to track suppression. The first line of `needToCheckSuppressedTriggers` is checking if suppression is enabled. The lines directly surrounding the variable provide enough context and it is already a long variable name. The method is much further away, so more context is needed. Otherwise, someone looking at the method might not see what the method has to do with track suppression. 
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/TrackOutputHelper.java` line 223 at r5](https://reviewable.io/reviews/openmpf/openmpf/1644#-NaE6Yt9DouUWyLbV20L:-NaMxefn6LVGOAB092pL:bjnaf4f) ([raw file](https://github.com/openmpf/openmpf/blob/8a86ae10ceaa392c863781492a620a12ceacd447/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/TrackOutputHelper.java#L223)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Do you do this because the only non-DETECTION algorithm is MARKUP?

I'm wondering if it would be better to iterate backwards until we find a DETECTION algorithm just in case we ever start supporting other non-DETECTION algorithms.

Minimally, leave a comment here explaining that the only non-DETECTION algorithm is MARKUP.
</blockquote></details>

The methods in this class already have a lot parameters. To avoid adding even more, this method is called in a few places, so I think it is better to keep it simple. There are a lot of places throughout the code base that depend on there only being detection and markup algorithms. If that change is ever made, a developer would find all references to `ActionType` and update them accordingly.
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/RedisImpl.java` line 121 at r5](https://reviewable.io/reviews/openmpf/openmpf/1644#-NaE5QqR8krKIcMoGfaS:-NaMzSfGEP3PLXaxN5rc:b-yfda76) ([raw file](https://github.com/openmpf/openmpf/blob/8a86ae10ceaa392c863781492a620a12ceacd447/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/RedisImpl.java#L121)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

This isn't a track at this point. Consider calling it `trackListOps` instead.
</blockquote></details>

It has the interface of a list. There isn't a difference between `tracks.index(0)` and `tracks.get(0)`. 
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/segmenting/TriggerProcessor.java` line 51 at r5](https://reviewable.io/reviews/openmpf/openmpf/1644#-NaE7efE2Bwk2VspuhH5:-NaMzbL00o4irTXzFqjq:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/8a86ae10ceaa392c863781492a620a12ceacd447/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/segmenting/TriggerProcessor.java#L51)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I don't think this needs to be public.
</blockquote></details>

Done.
___
*[`trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/segmenting/TestTriggerProcessor.java` line 206 at r2](https://reviewable.io/reviews/openmpf/openmpf/1644#-NZ7WK2Y25OWDfPxv_XJ:-NaMzsug-n0iiWcxkZFG:byh77l9) ([raw file](https://github.com/openmpf/openmpf/blob/9bc681d668ed8254aaeb03bcdcf062696a8949bb/trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/segmenting/TestTriggerProcessor.java#L206)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

> Middle refers to the median of the task indices.

Since the indices are 0, 1, 2, 3, and 4, I assume you're referring to index 2, which would mean the "no trigger" is the same as the ALL_MATCH trigger (both blank and null trigger property represent ALL_MATCH).

A line-ending comment could help here:

```java
.setTrigger("", 2)  // blank is the same as no trigger
```

> Your version of the test doesn't fail when TriggerProcessor gets unnecessary tracks out of Redis.

What are the "unnecessary tracks" in your test? Maybe we want to generate some tracks for task 1 here:

```java
        var tracks = builder()
            .addTrack("EN", 1) // this
            .addTrack("ES", 1) // this

            .setTrigger("", 2)
            .addTrack(11, "EN", 2)
            .addTrack("ES", 2)
```
</blockquote></details>

The test name says "checking" and the test contains verify/never because it shouldn't even attempt to get the tracks. The exception generated explains why it is better not to include those tracks. 
```
org.mockito.exceptions.misusing.UnnecessaryStubbingException:   
Unnecessary stubbings detected.  
Clean & maintainable test code requires zero unnecessary code.  
Following stubbings are unnecessary (click to navigate to relevant line of code):  
 at org.mitre.mpf.wfm.segmenting.TestTriggerProcessor$TestCaseBuilder.getTriggeredTracks([TestTriggerProcessor.java:400]
Please remove unnecessary stubbings or use 'lenient' strictness. More info: javadoc for UnnecessaryStubbingException class.
```
I only used `lenient()` in certain cases where it was accessing local data from the passed in `BatchJob`. None of the stubbings for `_mockInProgressJobs` are lenient.


<!-- Sent from Reviewable.io -->

2023-09-05 12:14 UTC, brosenberg42 reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1644)* status: 21 of 129 files reviewed, 2 unresolved discussions (waiting on @jrobble)

___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/segmenting/TriggerProcessor.java` line 124 at r7](https://reviewable.io/reviews/openmpf/openmpf/1644#-NahDIwbAbBEzhCyE2o_:-Nd6SRWXEsWS8Mrnc4f6:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/a8faa7919611187b5fdd08586987c20a9ad91f2a/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/segmenting/TriggerProcessor.java#L124)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please call this `taskIdx`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-25 03:06 UTC, jrobble requested changes
> Reviewed 85 of 107 files at r8, 22 of 22 files at r9, 3 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1644)* status: all files reviewed, 15 unresolved discussions (waiting on @brosenberg42)

*[a discussion](https://reviewable.io/reviews/openmpf/openmpf/1644#-Nh7zFzfDu8zXMbel4Kg:-Nh7zFzfDu8zXMbel4Kh:b9o8zpe) (no related file):*
In `ArtifactExtractionPolicy.java`:

```java
	/** Default: Extract artifacts for tracks associated
            with a &quot;visual&quot; detection type according to the
            detection.artifact.extraction.policy.* settings. For example, this
            would include faces and cars, but it would exclude speech,
            motion and scene detection. */
	VISUAL_TYPES_ONLY,

	/** Default: Extract artifacts for tracks associated with any
         * detection type according to the detection.artifact.extraction.policy.* settings. */
	ALL_TYPES,
```

"detection type" is used twice in the above comments. Change to "track type".

___
*[a discussion](https://reviewable.io/reviews/openmpf/openmpf/1644#-NhXFn9Z6cacOrauz9lN:-NhXFn9aDNdAZvvLNrBi:bs44uk9) (no related file):*
```
8e4237971957da59108bec54643c610eb66ad4cf48282e8c8c621ebbf" responded with a non-200 status code of 404. There are 1  attempts remaining and the next attempt will begin in 30000 ms.
```

`There are 1  attempts remaining` has an extra space after the `1`.

___
*[a discussion](https://reviewable.io/reviews/openmpf/openmpf/1644#-NhZQwxn1_q6SJdfGHyY:-NhZQwxr1gOz6Ac95t2O:b-69h2g6) (no related file):*
Getting this:

```
2023-10-24 15:33:46,598 INFO [http-nio-8080-exec-7] o.m.m.w.d.InProgressBatchJobsService - [Job 56] Initializing batch job 56 which will run the "OCV TRITON YOLO OBJECT DETECTION (WITH MARKUP) PIPELINE" pipeline on the following media: "file:///opt/mpf/share/remote-media/dog-1080.jpg" (id=13)
2023-10-24 15:33:46,605 INFO [http-nio-8080-exec-7] o.m.m.w.d.InProgressBatchJobsService - [Job 56] Setting status of job 56 to IN_PROGRESS
2023-10-24 15:33:46,610 INFO [http-nio-8080-exec-7] o.m.m.w.b.i.JobRequestServiceImpl - [Job 56] Skipping job processing because compatible job found in TiesDb.
2023-10-24 15:33:46,613 INFO [Camel (camelContext) thread #7 - JmsConsumer[MPF.JOB_ROUTER]] o.m.m.w.d.InProgressBatchJobsService - [Job 56] Changing job 56's current task index from -1 to 0
2023-10-24 15:33:46,613 INFO [Camel (camelContext) thread #7 - JmsConsumer[MPF.JOB_ROUTER]] o.m.m.w.c.DefaultTaskSplitter - [Job 56] Task 1/2 - Operation: DETECTION - ActionType: DETECTION.
2023-10-24 15:33:46,615 INFO [Camel (camelContext) thread #7 - JmsConsumer[MPF.JOB_ROUTER]] o.m.m.w.c.DefaultTaskSplitter - [Job 56] DefaultTaskSplitter produced 1 work units with correlation id '56:16a9a502-aa55-4e3e-9925-c02c86f9a21f'.
2023-10-24 15:33:47,225 ERROR [Camel (camelContext) thread #46 - JmsConsumer[MPF.COMPLETED_DETECTIONS]] o.a.c.p.DefaultErrorHandler - Failed delivery for (MessageId: ID-23106830b23d-1698160439551-0-409 on ExchangeId: ID-23106830b23d-1698160439551-0-408). Exhausted after delivery attempt: 1 caught: java.lang.NumberFormatException: Cannot parse null string

Message History
---------------------------------------------------------------------------------------------------------------------------------------
RouteId              ProcessorId          Processor                                                                        Elapsed (ms)
[Detection Response] [Detection Response] [jms://MPF.COMPLETED_DETECTIONS                                                ] [        10]
[Detection Response] [setExchangePattern] [setExchangePattern[InOnly]                                                    ] [         0]
[Detection Response] [unmarshal1        ] [unmarshal[org.apache.camel.model.DataFormatDefinition@1eb0a4e3]               ] [         1]
[Detection Response] [process2          ] [ref:detectionResponseProcessor                                                ] [         3]
[Detection Response] [choice1           ] [when[{header{header(Unsolicited)} == true}]choice[]                           ] [         0]
[Detection Response] [aggregate1        ] [aggregate[header(CorrelationId)]                                              ] [         0]
[Detection Response] [process3          ] [ref:trackMergingProcessor                                                     ] [         1]
[Detection Response] [process4          ] [ref:MovingTrackLabelProcessor                                                 ] [         0]
[Detection Response] [process5          ] [ref:detectionTransformationProcessor                                          ] [         3]

Stacktrace
---------------------------------------------------------------------------------------------------------------------------------------
java.lang.NumberFormatException: Cannot parse null string
        at java.lang.Integer.parseInt(Integer.java:630) ~[?:?]
        at java.lang.Integer.parseInt(Integer.java:786) ~[?:?]
        at org.mitre.mpf.wfm.camel.operations.detection.transformation.DetectionTransformationProcessor.wfmProcess(DetectionTransformationProcessor.java:102) ~[classes/:?]
        at org.mitre.mpf.wfm.camel.WfmProcessor.lambda$process$0(WfmProcessor.java:59) ~[classes/:?]
        at org.mitre.mpf.mvc.util.MdcUtil.lambda$asSupplier$0(MdcUtil.java:120) ~[classes/:?]
        at org.mitre.mpf.mvc.util.MdcUtil.job(MdcUtil.java:102) ~[classes/:?]
        at org.mitre.mpf.mvc.util.MdcUtil.job(MdcUtil.java:114) ~[classes/:?]
        at org.mitre.mpf.wfm.camel.WfmProcessor.process(WfmProcessor.java:59) ~[classes/:?]
        at org.mitre.mpf.wfm.camel.WfmProcessor$$FastClassBySpringCGLIB$$dbb36fb4.invoke(<generated>) ~[classes/:?]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.24.jar:5.3.24]

```

For this job:

```json
{
  "jobProperties": {
    "TIES_DB_URL" : "https://somehost"
  },
  "media": [
    {
      "mediaUri": "file:///opt/mpf/share/remote-media/dog-1080.jpg",
      "metadata" : {
        "MEDIA_HASH": "7783d66ccd942eacb982e7eeb645f5a446621d1e53745f42f894a64bf1a970e4",
        "MIME_TYPE": "image/jpeg"
      }
    }
  ],
  "pipelineName": "OCV TRITON YOLO OBJECT DETECTION (WITH MARKUP) PIPELINE"
}
```

This is the line that causes the NPE:

```
                    int frameWidth = Integer.parseInt(media.getMetadata().get("FRAME_WIDTH"));
```

You stated that:

> It's a merge issue from the camel refactor

> BeginTaskProcessor doesn't copy the `JOB_COMPLETE` header

___
*[a discussion](https://reviewable.io/reviews/openmpf/openmpf/1644#-NhZXTfEAXCOKb64-WIY:-NhZXTfG2OOcVqc9mvt9:b-aw7vpp) (no related file):*
When a `TRIGGER` is specified for an action, check if a valid `FEED_FORWARD_TYPE` is also specified. If not, don't create the job. I think we should do this as part of the job pre-validation, similar to what we do when `S3_RESULTS_BUCKET` is specified but `S3_ACCESS_KEY` or `S3_SECRET_KEY` is missing.

___
___
*[`trunk/mpf-system-tests/src/test/java/org/mitre/mpf/mst/TestSystemOnDiff.java` line 68 at r10](https://reviewable.io/reviews/openmpf/openmpf/1644#-Nh7ynVq7e_6nPDvBvRV:-Nh7ynVq7e_6nPDvBvRW:bpmys15) ([raw file](https://github.com/openmpf/openmpf/blob/3047abcf64fde9c9267e3e16b5165d488a462a4a/trunk/mpf-system-tests/src/test/java/org/mitre/mpf/mst/TestSystemOnDiff.java#L68)):*
Change:

> Output object did not contain expected detection type:

to:

> Output object did not contain expected track type:

There are multiple lines in this file like that. Please change them all.
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessorImpl.java` line 584 at r10](https://reviewable.io/reviews/openmpf/openmpf/1644#-Nge1IRJ-sUfjqx-MGLh:-Nge1IRJ-sUfjqx-MGLi:b-p4xys) ([raw file](https://github.com/openmpf/openmpf/blob/3047abcf64fde9c9267e3e16b5165d488a462a4a/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessorImpl.java#L584)):*
> ```Java [...]

2023-11-01 14:38 UTC, brosenberg42 reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1644)* status: 96 of 157 files reviewed, 13 unresolved discussions (waiting on @brosenberg42 and @jrobble)

*[a discussion](https://reviewable.io/reviews/openmpf/openmpf/1644#-Nh7zFzfDu8zXMbel4Kg:-Ni-sy_w5ZpHb45aJj8k:b-896fix) (no related file):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

In `ArtifactExtractionPolicy.java`:

```java
	/** Default: Extract artifacts for tracks associated
            with a &quot;visual&quot; detection type according to the
            detection.artifact.extraction.policy.* settings. For example, this
            would include faces and cars, but it would exclude speech,
            motion and scene detection. */
	VISUAL_TYPES_ONLY,

	/** Default: Extract artifacts for tracks associated with any
         * detection type according to the detection.artifact.extraction.policy.* settings. */
	ALL_TYPES,
```

"detection type" is used twice in the above comments. Change to "track type".
</blockquote></details>

Done.

___
*[a discussion](https://reviewable.io/reviews/openmpf/openmpf/1644#-NhXFn9Z6cacOrauz9lN:-Ni-sysp0es1SQCf2n77:b-896fix) (no related file):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

```
8e4237971957da59108bec54643c610eb66ad4cf48282e8c8c621ebbf" responded with a non-200 status code of 404. There are 1  attempts remaining and the next attempt will begin in 30000 ms.
```

`There are 1  attempts remaining` has an extra space after the `1`.
</blockquote></details>

Done.

___
*[a discussion](https://reviewable.io/reviews/openmpf/openmpf/1644#-NhZQwxn1_q6SJdfGHyY:-Ni-yPru0xSP-jIY-ivC:b-896fix) (no related file):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Getting this:

```
2023-10-24 15:33:46,598 INFO [http-nio-8080-exec-7] o.m.m.w.d.InProgressBatchJobsService - [Job 56] Initializing batch job 56 which will run the "OCV TRITON YOLO OBJECT DETECTION (WITH MARKUP) PIPELINE" pipeline on the following media: "file:///opt/mpf/share/remote-media/dog-1080.jpg" (id=13)
2023-10-24 15:33:46,605 INFO [http-nio-8080-exec-7] o.m.m.w.d.InProgressBatchJobsService - [Job 56] Setting status of job 56 to IN_PROGRESS
2023-10-24 15:33:46,610 INFO [http-nio-8080-exec-7] o.m.m.w.b.i.JobRequestServiceImpl - [Job 56] Skipping job processing because compatible job found in TiesDb.
2023-10-24 15:33:46,613 INFO [Camel (camelContext) thread #7 - JmsConsumer[MPF.JOB_ROUTER]] o.m.m.w.d.InProgressBatchJobsService - [Job 56] Changing job 56's current task index from -1 to 0
2023-10-24 15:33:46,613 INFO [Camel (camelContext) thread #7 - JmsConsumer[MPF.JOB_ROUTER]] o.m.m.w.c.DefaultTaskSplitter - [Job 56] Task 1/2 - Operation: DETECTION - ActionType: DETECTION.
2023-10-24 15:33:46,615 INFO [Camel (camelContext) thread #7 - JmsConsumer[MPF.JOB_ROUTER]] o.m.m.w.c.DefaultTaskSplitter - [Job 56] DefaultTaskSplitter produced 1 work units with correlation id '56:16a9a502-aa55-4e3e-9925-c02c86f9a21f'.
2023-10-24 15:33:47,225 ERROR [Camel (camelContext) thread #46 - JmsConsumer[MPF.COMPLETED_DETECTIONS]] o.a.c.p.DefaultErrorHandler - Failed delivery for (MessageId: ID-23106830b23d-1698160439551-0-409 on ExchangeId: ID-23106830b23d-1698160439551-0-408). Exhausted after delivery attempt: 1 caught: java.lang.NumberFormatException: Cannot parse null string

Message History
---------------------------------------------------------------------------------------------------------------------------------------
RouteId              ProcessorId          Processor                                                                        Elapsed (ms)
[Detection Response] [Detection Response] [jms://MPF.COMPLETED_DETECTIONS                                                ] [        10]
[Detection Response] [setExchangePattern] [setExchangePattern[InOnly]                                                    ] [         0]
[Detection Response] [unmarshal1        ] [unmarshal[org.apache.camel.model.DataFormatDefinition@1eb0a4e3]               ] [         1]
[Detection Response] [process2          ] [ref:detectionResponseProcessor                                                ] [         3]
[Detection Response] [choice1           ] [when[{header{header(Unsolicited)} == true}]choice[]                           ] [         0]
[Detection Response] [aggregate1        ] [aggregate[header(CorrelationId)]                                              ] [         0]
[Detection Response] [process3          ] [ref:trackMergingProcessor                                                     ] [         1]
[Detection Response] [process4          ] [ref:MovingTrackLabelProcessor                                                 ] [         0]
[Detection Response] [process5          ] [ref:detectionTransformationProcessor                                          ] [         3]

Stacktrace
---------------------------------------------------------------------------------------------------------------------------------------
java.lang.NumberFormatException: Cannot parse null string
        at java.lang.Integer.parseInt(Integer.java:630) ~[?:?]
        at java.lang.Integer.parseInt(Integer.java:786) ~[?:?]
        at org.mitre.mpf.wfm.camel.operations.detection.transformation.DetectionTransformationProcessor.wfmProcess(DetectionTransformationProcessor.java:102) ~[classes/:?]
        at org.mitre.mpf.wfm.camel.WfmProcessor.lambda$process$0(WfmProcessor.java:59) ~[classes/:?]
        at org.mitre.mpf.mvc.util.MdcUtil.lambda$asSupplier$0(MdcUtil.java:120) ~[classes/:?]
        at org.mitre.mpf.mvc.util.MdcUtil.job(MdcUtil.java:102) ~[classes/:?]
        at org.mitre.mpf.mvc.util.MdcUtil.job(MdcUtil.java:114) ~[classes/:?]
        at org.mitre.mpf.wfm.camel.WfmProcessor.process(WfmProcessor.java:59) ~[classes/:?]
        at org.mitre.mpf.wfm.camel.WfmProcessor$$FastClassBySpringCGLIB$$dbb36fb4.invoke(<generated>) ~[classes/:?]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.24.jar:5.3.24]

```

For this job:

```json
{
  "jobProperties": {
    "TIES_DB_URL" : "https://somehost"
  },
  "media": [
    {
      "mediaUri": "file:///opt/mpf/share/remote-media/dog-1080.jpg",
      "metadata" : {
        "MEDIA_HASH": "7783d66ccd942eacb982e7eeb645f5a446621d1e53745f42f894a64bf1a970e4",
        "MIME_TYPE": "image/jpeg"
      }
    }
  ],
  "pipelineName": "OCV TRITON YOLO OBJECT DETECTION (WITH MARKUP) PIPELINE"
}
```

This is the line that causes the NPE:

```
                    int frameWidth = Integer.parseInt(media.getMetadata().get("FRAME_WIDTH"));
```

You stated that:

> It's a merge issue from the camel refactor

> BeginTaskProcessor doesn't copy the `JOB_COMPLETE` header
</blockquote></details>

Done.

___
*[a discussion](https://reviewable.io/reviews/openmpf/openmpf/1644#-NhZXTfEAXCOKb64-WIY:-Ni0eOk95X70diFMlSV5:b-896fix) (no related file):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

When a `TRIGGER` is specified for an action, check if a valid `FEED_FORWARD_TYPE` is also specified. If not, don't create the job. I think we should do this as part of the job pre-validation, similar to what we do when `S3_RESULTS_BUCKET` is specified but `S3_ACCESS_KEY` or `S3_SECRET_KEY` is missing.
</blockquote></details>

Done.

___
___
*[`trunk/mpf-system-tests/src/test/java/org/mitre/mpf/mst/TestSystemOnDiff.java` line 68 at r10](https://reviewable.io/reviews/openmpf/openmpf/1644#-Nh7ynVq7e_6nPDvBvRV:-Ni-z4Tw-_03oz_axVE4:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/3047abcf64fde9c9267e3e16b5165d488a462a4a/trunk/mpf-system-tests/src/test/java/org/mitre/mpf/mst/TestSystemOnDiff.java#L68)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Change:

> Output object did not contain expected detection type:

to:

> Output object did not contain expected track type:

 [...]

2023-11-10 01:20 UTC, jrobble requested changes
> Reviewed 61 of 61 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1644)* status: all files reviewed, 5 unresolved discussions (waiting on @brosenberg42)

___
*[`trunk/mpf-system-tests/src/test/java/org/mitre/mpf/mst/TestSystemOnDiff.java` line 309 at r8](https://reviewable.io/reviews/openmpf/openmpf/1644#-NikMaCR1D4Hhyb1PCV5:-NikMaCY6GMXZDA73mlm:b-6h42u7) ([raw file](https://github.com/openmpf/openmpf/blob/930dfae90c313bf76d368f3da9df9d42b2cdcdbf/trunk/mpf-system-tests/src/test/java/org/mitre/mpf/mst/TestSystemOnDiff.java#L309)):*
> ```Java
>                 outputMedia.getTrackTypes().get(JsonActionOutputObject.TRACKS_MERGED_TYPE);
>         assertEquals(1, mergedTracksOutput.size());
>         assertEquals("Tracks merged for task other than TESSERACT OCR",
> ```

I ran some examples. The only actions we're listing in `TRACKS MERGED` are those that are in the middle of a merge chain. We're no longer listing the action at the beginning of the chain.

I believe the reason is, as we discussed, that showing the same action in the `TRACKS MERGED` section and listing the actual tracks for that action would be confusing.
___
*[`trunk/mpf-system-tests/src/test/resources/output/face/runDetectMarkupMultipleMediaTypes.json` line 10 at r11](https://reviewable.io/reviews/openmpf/openmpf/1644#-NikNOBz4-SYqS2UOc4w:-NikNOBz4-SYqS2UOc4x:b-z7vej7) ([raw file](https://github.com/openmpf/openmpf/blob/671851724b384abd7564fa374e72ffe6349aeca4/trunk/mpf-system-tests/src/test/resources/output/face/runDetectMarkupMultipleMediaTypes.json#L10)):*
> ```JSON
>       "details": [
>         {
>           "source": "WORKFLOW_MANAGER",
> ```

Did you intend to remove this? "source" is still a field in `JsonIssueDetails.java`.
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessorImpl.java` line 584 at r10](https://reviewable.io/reviews/openmpf/openmpf/1644#-Nge1IRJ-sUfjqx-MGLh:-NikbZhn7c9SDuOqPZwz:b15zd7) ([raw file](https://github.com/openmpf/openmpf/blob/3047abcf64fde9c9267e3e16b5165d488a462a4a/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessorImpl.java#L584)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I tested this with a dynamic speech pipeline with `OUTPUT_LAST_TASK_ONLY=false` and in the JSON it lists the downstream STT tracks and only the language tracks from the first stage that aren't triggered downstream. The track count only counts the number of tracks in the JSON, which is the downstream STT tracks and the untriggered upstream language track.

I believe this is the correct behavior based on what we discussed.
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/TrackOutputHelper.java` line 159 at r11](https://reviewable.io/reviews/openmpf/openmpf/1644#-Nil0CQRAPFCFsCINmk-:-Nil-qo1BpRicMDo8uP3:bmyvlt7) ([raw file](https://github.com/openmpf/openmpf/blob/672b2f3edef6b976f4cc68347dd188d11ce6778d/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/TrackOutputHelper.java#L159)):*
> ```Java
>     private String getMergedAction(Track track, BatchJob job) {
>         int actionIndex;
>         if (track.getMergedTaskIndex() == track.getTaskIndex()) {
> ```

This first condition will only happen when task merging is disabled, right? I guess someone could try to set `OUTPUT_MERGE_WITH_PREVIOUS_TASK=TRUE` on the first task in a pipeline.
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/trackmerging/TrackMergingProcessor.java` line 269 at r11](https://reviewable.io/reviews/openmpf/openmpf/1644#-Nil6L0O-iMF6wBR5KRl:-Nil6L0P-_ONNveWei4v:b-19lvkq) ([raw file](https://github.com/openmpf/openmpf/blob/672b2f3edef6b976f4cc68347dd188d11ce6778d/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/trackmerging/TrackMergingProcessor.java#L269)):*
> ```Java
>     }
> 
>     /** Combines two tracks. This is a destructive method. The contents of track1 reflect the merged track. */
> ```

This comment is not accurate, so please remove it.
___
*[`trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/service/TestTiesDbBeforeJobCheckService.java` line 897 at r11](https://reviewable.io/reviews/openmpf/openmpf/1644#-NikIO_H4ZarjrkOPVVr:-NikIO_I2N3l5DM_K9ZG:b-b8x6y7) ([raw file](https://github.com/openmpf/openmpf/blob/672b2f3edef6b976f4cc68347dd188d11ce6778d/trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/service/TestTiesDbBeforeJobCheckService.java#L897)):*
> ```Java
> 
>         var action1 = JsonActionOutputObject.factory(
>                 "source1", "algo1", ImmutableSortedSet.of(track1));
> ```

There are a few instances of "source1" and "source2" in here you should change to "action1" and "action2".
___
*[`trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/service/TestTiesDbBeforeJobCheckService.java` line 1096 at r11](https://reviewable.io/reviews/openmpf/openmpf/1644#-NikIj8i8ecwxjtXMgW7:-NikIj8i8ecwxjtXMgW8:b-ll9ia9) ([raw file](https://github.com/openmpf/openmpf/blob/672b2f3edef6b976f4cc68347dd188d11ce6778d/trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/service/TestTiesDbBeforeJobCheckService.java#L1096)):*
> ```Java
>                 List.of(detection));
> 
>         var action = new JsonActionOutputObject("source", "algo");
> ```

Change "source" to "action".


<!-- Sent from Reviewable.io -->

2023-11-13 12:38 UTC, brosenberg42 reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1644)* status: 153 of 157 files reviewed, 5 unresolved discussions (waiting on @jrobble)

___
*[`trunk/mpf-system-tests/src/test/resources/output/face/runDetectMarkupMultipleMediaTypes.json` line 10 at r11](https://reviewable.io/reviews/openmpf/openmpf/1644#-NikNOBz4-SYqS2UOc4w:-Nj7RB3_1vip0Bw7oRs7:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/671851724b384abd7564fa374e72ffe6349aeca4/trunk/mpf-system-tests/src/test/resources/output/face/runDetectMarkupMultipleMediaTypes.json#L10)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Did you intend to remove this? "source" is still a field in `JsonIssueDetails.java`.
</blockquote></details>

Done.
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/TrackOutputHelper.java` line 159 at r11](https://reviewable.io/reviews/openmpf/openmpf/1644#-Nil0CQRAPFCFsCINmk-:-Nj7VBXP6eSjvHjbv90L:b-87rmoq) ([raw file](https://github.com/openmpf/openmpf/blob/672b2f3edef6b976f4cc68347dd188d11ce6778d/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/TrackOutputHelper.java#L159)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

This first condition will only happen when task merging is disabled, right? I guess someone could try to set `OUTPUT_MERGE_WITH_PREVIOUS_TASK=TRUE` on the first task in a pipeline.
</blockquote></details>

That is correct.
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/trackmerging/TrackMergingProcessor.java` line 269 at r11](https://reviewable.io/reviews/openmpf/openmpf/1644#-Nil6L0O-iMF6wBR5KRl:-Nj7W3gsDgzpwMz1Jnk-:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/672b2f3edef6b976f4cc68347dd188d11ce6778d/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/trackmerging/TrackMergingProcessor.java#L269)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

This comment is not accurate, so please remove it.
</blockquote></details>

Done.
___
*[`trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/service/TestTiesDbBeforeJobCheckService.java` line 897 at r11](https://reviewable.io/reviews/openmpf/openmpf/1644#-NikIO_H4ZarjrkOPVVr:-Nj7WZWd7FSagUqgeKD9:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/672b2f3edef6b976f4cc68347dd188d11ce6778d/trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/service/TestTiesDbBeforeJobCheckService.java#L897)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

There are a few instances of "source1" and "source2" in here you should change to "action1" and "action2".
</blockquote></details>

Done.
___
*[`trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/service/TestTiesDbBeforeJobCheckService.java` line 1096 at r11](https://reviewable.io/reviews/openmpf/openmpf/1644#-NikIj8i8ecwxjtXMgW7:-Nj7WZjk1K4AZPXszg1U:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/672b2f3edef6b976f4cc68347dd188d11ce6778d/trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/service/TestTiesDbBeforeJobCheckService.java#L1096)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Change "source" to "action".
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-11-14 03:20 UTC, jrobble approved these changes
> Reviewed 4 of 4 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1644)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @brosenberg42)



<!-- Sent from Reviewable.io -->

2023-11-14 13:33 UTC, merged