Feat/subject tracking
openmpf/openmpf pull request #1833
Opened 2024-07-10 17:26 UTC by brosenberg42

**Issues:**

- https://github.com/openmpf/openmpf/issues/1 < Example
- https://github.com/openmpf/openmpf/issues/2 < Example

If a related issue doesn't exist, then create one first and assign it to yourself.

**Related PRs:**

- https://github.com/openmpf/openmpf/pull/22 < Example
- https://github.com/openmpf/openmpf/pull/53 < Example

Please review our [Contributor Guide](https://openmpf.github.io/docs/site/Contributor-Guide/index.html).

2024-09-24 15:42 UTC, jrobble requested changes
> Reviewed 200 of 200 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1833)* status: all files reviewed, 27 unresolved discussions (waiting on @brosenberg42)

*[a discussion](https://reviewable.io/reviews/openmpf/openmpf/1833#-O7ZaeOMD6XycnNnSo0u:-O7ZaeOMD6XycnNnSo0v:brnxf40) (no related file):*
I tried getting subject tracking working via `mpf start`. Here's what happened:

```
2024-09-11 15:09:32,320 INFO [main] o.m.m.w.s.c.AnsibleDeploymentService - TASK [Send the component descriptor path to stdout] ****************************
2024-09-11 15:09:32,375 INFO [main] o.m.m.w.s.c.AnsibleDeploymentService - ok: [localhost] => {
2024-09-11 15:09:32,376 INFO [main] o.m.m.w.s.c.AnsibleDeploymentService -     "msg": "COMPONENT_DESCRIPTOR_PATH=/home/mpf/openmpf-projects/openmpf/trunk/install/plugins/PythonSubjectComponent/descriptor/descriptor.json"
2024-09-11 15:09:32,376 INFO [main] o.m.m.w.s.c.AnsibleDeploymentService - }
2024-09-11 15:09:32,385 INFO [main] o.m.m.w.s.c.AnsibleDeploymentService - 
2024-09-11 15:09:32,385 INFO [main] o.m.m.w.s.c.AnsibleDeploymentService - TASK [Check if component has wheelhouse directory] *****************************
2024-09-11 15:09:32,639 INFO [main] o.m.m.w.s.c.AnsibleDeploymentService - ok: [localhost]
2024-09-11 15:09:32,647 INFO [main] o.m.m.w.s.c.AnsibleDeploymentService - 
2024-09-11 15:09:32,647 INFO [main] o.m.m.w.s.c.AnsibleDeploymentService - TASK [Upgrade pip for Python component virtualenv] *****************************
2024-09-11 15:09:37,538 INFO [main] o.m.m.w.s.c.AnsibleDeploymentService - changed: [localhost]
2024-09-11 15:09:37,544 INFO [main] o.m.m.w.s.c.AnsibleDeploymentService - 
2024-09-11 15:09:37,544 INFO [main] o.m.m.w.s.c.AnsibleDeploymentService - TASK [Setup virtualenv for Python setuptools-based component] ******************
2024-09-11 15:09:38,114 INFO [main] o.m.m.w.s.c.AnsibleDeploymentService - fatal: [localhost]: FAILED! => {"changed": false, "cmd": ["/home/mpf/openmpf-projects/openmpf/trunk/install/plugins/PythonSubjectComponent//venv/bin/pip3", "install", "--find-links", "/home/mpf/openmpf-projects/openmpf/trunk/install/plugins/PythonSubjectComponent//wheelhouse", "--no-index", " "], "msg": "\n:stderr: ERROR: Invalid requirement: '': Expected package name at the start of dependency specifier\n    \n    ^\n"}
```

As discussed, more work needs to be done to enable non-Docker deployments.

___
___
*[`trunk/CMakeLists.txt` line 41 at r1](https://reviewable.io/reviews/openmpf/openmpf/1833#-O4lkFxJ4gEf87z3BQcm:-O4lkFxJ4gEf87z3BQcn:b-8zv13w) ([raw file](https://github.com/openmpf/openmpf/blob/8ab9fa38eb9991fb3edc8d20e9f13ede523eaf47/trunk/CMakeLists.txt#L41)):*
Missing "to" here:

> Need to get clang-tidy **to** work.

Make change below too.
___
*[`trunk/CMakeLists.txt` line 48 at r1](https://reviewable.io/reviews/openmpf/openmpf/1833#-O4lk-371rmHAH2QQNv9:-O4lk-371rmHAH2QQNvA:b7qnppn) ([raw file](https://github.com/openmpf/openmpf/blob/8ab9fa38eb9991fb3edc8d20e9f13ede523eaf47/trunk/CMakeLists.txt#L48)):*
> ```CMake
>     message("Configuring as RELEASE build")
>     # Strip executables and shared libraries during the link phase.
>     add_link_options(-s)
> ```

The old file has the `-O3` optimization flag. Do we not care about optimizing the code anymore?

Do we want to strip and optimize when we build components?
___
*[`trunk/cpp-executors-common/PythonLogger.h` line 56 at r1](https://reviewable.io/reviews/openmpf/openmpf/1833#-O63nBVh4etPBmgxehei:-O63nBVh4etPBmgxehej:bsqkpi3) ([raw file](https://github.com/openmpf/openmpf/blob/8ab9fa38eb9991fb3edc8d20e9f13ede523eaf47/trunk/cpp-executors-common/PythonLogger.h#L56)):*
> ```objc
> 
> private:
>     class Impl;
> ```

In `PythonComponentHandle.h` you state:

```
        // The pybind11 library declares everything with hidden visibility, so the pybind11 types cannot be
        // referenced in a header file. To avoid referencing any pybind11 types the
        // "Pointer to implementation" or "pImpl" pattern is used here. This also has the benefit that including
        // this header, won't cause all of the Python headers to be included.
```

What's the advantage of using pImpl here? Consider adding a comment to explain it.
___
*[`trunk/subject-tracking/executor/cpp/ComponentRegistration.cpp` line 54 at r1](https://reviewable.io/reviews/openmpf/openmpf/1833#-O6710mR5CIYO_9fZowM:-O6710mR5CIYO_9fZowN:blopl5w) ([raw file](https://github.com/openmpf/openmpf/blob/8ab9fa38eb9991fb3edc8d20e9f13ede523eaf47/trunk/subject-tracking/executor/cpp/ComponentRegistration.cpp#L54)):*
Check spelling on "registration":

> MPF.SUBJECT_COMPONENT_REGISRATION
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/JobController.java` line 31 at r1](https://reviewable.io/reviews/openmpf/openmpf/1833#-O6TVnNYDFhOkSUC5jcr:-O6TVnNYDFhOkSUC5jcs:b-d1nch) ([raw file](https://github.com/openmpf/openmpf/blob/8ab9fa38eb9991fb3edc8d20e9f13ede523eaf47/trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/JobController.java#L31)):*
> ```Java
> import static java.util.stream.Collectors.toList;
> 
> import java.io.File;
> ```

VScode says these are not used:

```java
import java.io.File;
import java.io.IOException;
import java.net.URI;
import java.nio.file.NoSuchFileException;
```
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/PipelineController.java` line 53 at r1](https://reviewable.io/reviews/openmpf/openmpf/1833#-O6TXywd37YuDUtSO2m8:-O6TXywd37YuDUtSO2m9:bf7jlek) ([raw file](https://github.com/openmpf/openmpf/blob/0dbc6ef40baa41fa5423e546ffd8e31e4829adef/trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/PipelineController.java#L53)):*
> ```Java
> 
> @Api("Pipelines")
> @Scope("request")
> ```

Why remove this? `@Scope("request")` seems to be what our other controllers are using since they don't maintain state.
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/ActiveMQConfiguration.java` line 59 at r1](https://reviewable.io/reviews/openmpf/openmpf/1833#-O6S50wZBsQ8euakged1:-O6S50wZBsQ8euakged2:b-ybtnmm) ([raw file](https://github.com/openmpf/openmpf/blob/8ab9fa38eb9991fb3edc8d20e9f13ede523eaf47/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/ActiveMQConfiguration.java#L59)):*
> ```Java
> public class ActiveMQConfiguration {
> 
>     @Bean(name = "activemqBroker", destroyMethod = "stop")
> ```

I don't see a `stop()` method.
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/ActiveMQConfiguration.java` line 86 at r1](https://reviewable.io/reviews/openmpf/openmpf/1833#-O6S4uqICI-Pk6yyg-3u:-O6S4uqICI-Pk6yyg-3v:b-q1andc) ([raw file](https://github.com/openmpf/openmpf/blob/8ab9fa38eb9991fb3edc8d20e9f13ede523eaf47/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/ActiveMQConfiguration.java#L86)):*
> ```Java
>     }
> 
>     private static void enablePurgeInactiveQueues(BrokerService broker, PolicyEntry policy) {
> ```

What kind of queues are affected by this?

When do they go inactive? Do they go inactive when the producer/consumer connection to the broker dies?
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/ActiveMQConfiguration.java` line 123 at r1](https://reviewable.io/reviews/openmpf/openmpf/1833#-O6SE8O41dIcYrcSifr4:-O6SE8O51srSyT2Q8a3l:brem5k2) ([raw file](https://github.com/openmpf/openmpf/blob/8ab9fa38eb9991fb3edc8d20e9f13ede523eaf47/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/ActiveMQConfiguration.java#L123)):*
> ```Java
>         var poolFactory = (PooledConnectionFactory) amqConfig.getConnectionFactory();
>         var baseConnectionFactory = (ActiveMQConnectionFactory) poolFactory.getConnectionFactory();
>         // This feature interferes with Camel's ability to reply to temporary queues.
> ```

Do you have a link that describes this issue in more detail? Can you add it as a comment?
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/ActiveMQConfiguration.java` line 206 at r1]( [...]

2024-10-02 12:29 UTC, brosenberg42 reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1833)* status: 172 of 213 files reviewed, 27 unresolved discussions (waiting on @jrobble)

___
*[`trunk/CMakeLists.txt` line 41 at r1](https://reviewable.io/reviews/openmpf/openmpf/1833#-O4lkFxJ4gEf87z3BQcm:-O82Ga_9-ZrkV41HHSi9:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/8ab9fa38eb9991fb3edc8d20e9f13ede523eaf47/trunk/CMakeLists.txt#L41)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Missing "to" here:

> Need to get clang-tidy **to** work.

Make change below too.
</blockquote></details>

Done.
___
*[`trunk/CMakeLists.txt` line 48 at r1](https://reviewable.io/reviews/openmpf/openmpf/1833#-O4lk-371rmHAH2QQNv9:-O7ZiBsQCy913HyMDvfs:bnrfco) ([raw file](https://github.com/openmpf/openmpf/blob/8ab9fa38eb9991fb3edc8d20e9f13ede523eaf47/trunk/CMakeLists.txt#L48)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

The old file has the `-O3` optimization flag. Do we not care about optimizing the code anymore?

Do we want to strip and optimize when we build components?
</blockquote></details>

CMake sets `-O3` automatically when `CMAKE_BUILD_TYPE` is `RELEASE`. The previous code seems to be assuming either that the only two build types are `DEBUG` and `RELEASE`, or that every build type other than `DEBUG` uses `-O3`. `RelWithDebInfo` and `MinSizeRel` may use different optimization flags. 

You can check the flags that are actually used by looking at `openmpf-projects/openmpf/trunk/build/compile_commands.json`. The compiler flags that get set for every source file are: `-O3 -DNDEBUG -fvisibility=hidden -std=gnu++17`. There are also flags for include paths and things like that, but those aren't relevant here.

We can add the strip flag to the components, but it likely won't have much of an effect. It makes a bigger difference for the stuff that links to Python and the ActiveMQ library.
___
*[`trunk/cpp-executors-common/PythonLogger.h` line 56 at r1](https://reviewable.io/reviews/openmpf/openmpf/1833#-O63nBVh4etPBmgxehei:-O83-5hJC5nChm0q1pkZ:broiht5) ([raw file](https://github.com/openmpf/openmpf/blob/8ab9fa38eb9991fb3edc8d20e9f13ede523eaf47/trunk/cpp-executors-common/PythonLogger.h#L56)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

In `PythonComponentHandle.h` you state:

```
        // The pybind11 library declares everything with hidden visibility, so the pybind11 types cannot be
        // referenced in a header file. To avoid referencing any pybind11 types the
        // "Pointer to implementation" or "pImpl" pattern is used here. This also has the benefit that including
        // this header, won't cause all of the Python headers to be included.
```

What's the advantage of using pImpl here? Consider adding a comment to explain it.
</blockquote></details>

We don't need to use pimpl any more because I added `set_target_properties(subject_tracking_executor PROPERTIES CXX_VISIBILITY_PRESET hidden)`
___
*[`trunk/subject-tracking/executor/cpp/ComponentRegistration.cpp` line 54 at r1](https://reviewable.io/reviews/openmpf/openmpf/1833#-O6710mR5CIYO_9fZowM:-O83-pfj2kAWb0sz9h3i:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/8ab9fa38eb9991fb3edc8d20e9f13ede523eaf47/trunk/subject-tracking/executor/cpp/ComponentRegistration.cpp#L54)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Check spelling on "registration":

> MPF.SUBJECT_COMPONENT_REGISRATION
</blockquote></details>

Done.
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/JobController.java` line 31 at r1](https://reviewable.io/reviews/openmpf/openmpf/1833#-O6TVnNYDFhOkSUC5jcr:-O830BrjDa9OUuabmihx:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/8ab9fa38eb9991fb3edc8d20e9f13ede523eaf47/trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/JobController.java#L31)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

VScode says these are not used:

```java
import java.io.File;
import java.io.IOException;
import java.net.URI;
import java.nio.file.NoSuchFileException;
```
</blockquote></details>

Done.
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/PipelineController.java` line 53 at r1](https://reviewable.io/reviews/openmpf/openmpf/1833#-O6TXywd37YuDUtSO2m8:-O7Zjo3JBeaY4yGJwr1A:byy2xtk) ([raw file](https://github.com/openmpf/openmpf/blob/0dbc6ef40baa41fa5423e546ffd8e31e4829adef/trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/PipelineController.java#L53)):*
It was causing issues with Spring test. I think `@Scope("request")` is for when you want the controller to maintain state, but just for a single request. If there is no state, then we are  safe to re-use the same instance for multiple requests.

From https://docs.spring.io/spring-framework/reference/core/beans/factory-scopes.html#beans-factory-scopes-prototype:
> As a rule, you should use the prototype scope for all stateful beans and the **singleton scope for stateless beans**.
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/ActiveMQConfiguration.java` line 59 at r1](https://reviewable.io/reviews/openmpf/openmpf/1833#-O6S50wZBsQ8euakged1:-O8BpOh16-W-aUEKLgf6:b-s70tig) ([raw file](https://github.com/openmpf/openmpf/blob/8ab9fa38eb9991fb3edc8d20e9f13ede523eaf47/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/ActiveMQConfiguration.java#L59)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I don't see a `stop()` method.
</blockquote></details>

`BrokerService` is  `org.apache.activemq.broker.BrokerService`.
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/ActiveMQConfiguration.java` line 86 at r1](https://reviewable.io/reviews/openmpf/openmpf/1833#-O6S4uqICI-Pk6yyg-3u:-O7Zkjt66hSUYUsawAJ8:bjk1akm) ([raw file](https://github.com/openmpf/openmpf/blob/8ab9fa38eb9991fb3edc8d20e9f13ede523eaf47/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/ActiveMQConfiguration.java#L86)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

What kind of queues are affected by this?

When do they go inactive? Do they go inactive when the producer/consumer connection to the broker dies?
</blockquote></details>

The policy is applied to all queues. A queue is considered to be inactive when it is empty and there are no consumers present. ActiveMQ always creates a queue when a consumer tries to read from a queue that doesn't exist, so consumers don't need to do anything special when gc is enabled.
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/ActiveMQConfiguration.java` line 123 at r1](https://reviewable.io/reviews/openmpf/openmpf/1833#-O6SE8O41dIcYrcSifr4:-O87O03g-EcPZG0GybYu:b-rhtz94) ([raw file](https://github.com/openmpf/openmpf/blob/8ab9fa38eb9991fb3edc8d20e9f13ede523eaf47/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/ActiveMQConfiguration.java#L123)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Do you have a link that describes this issue in more detail? Can you add it as a comment?
</blockquote></details>

No, it is an observation. I didn't look for an issue because we don't use that feature. If we do need that feature enabled in the future, a developer will know to make sure Camel can still reply to temporary queues. 
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/ActiveMQConfiguration.java` line 206 at r1](https://reviewable.io/reviews/openmpf/openmpf/1833#-O6SGkt64VV72GqJgcxi:-O7Zm--d4BfM2bW3RxRE:b-4fybgw) ([raw file](https://github.com/openmpf/openmpf/blob/8ab9fa38eb9991fb3edc8d20e9f13ede523eaf47/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/ActiveMQConfiguration.java#L206)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Are thes [...]

2024-10-21 17:30 UTC, jrobble requested changes
> Reviewed 37 of 39 files at r2, 3 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1833)* status: all files reviewed, 12 unresolved discussions (waiting on @brosenberg42 and @jrobble)

___
*[`trunk/CMakeLists.txt` line 48 at r1](https://reviewable.io/reviews/openmpf/openmpf/1833#-O4lk-371rmHAH2QQNv9:-O9RPSP26trvAnhUqmrX:bzhf1am) ([raw file](https://github.com/openmpf/openmpf/blob/8ab9fa38eb9991fb3edc8d20e9f13ede523eaf47/trunk/CMakeLists.txt#L48)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

CMake sets `-O3` automatically when `CMAKE_BUILD_TYPE` is `RELEASE`. The previous code seems to be assuming either that the only two build types are `DEBUG` and `RELEASE`, or that every build type other than `DEBUG` uses `-O3`. `RelWithDebInfo` and `MinSizeRel` may use different optimization flags. 

You can check the flags that are actually used by looking at `openmpf-projects/openmpf/trunk/build/compile_commands.json`. The compiler flags that get set for every source file are: `-O3 -DNDEBUG -fvisibility=hidden -std=gnu++17`. There are also flags for include paths and things like that, but those aren't relevant here.

We can add the strip flag to the components, but it likely won't have much of an effect. It makes a bigger difference for the stuff that links to Python and the ActiveMQ library.
</blockquote></details>

Ok. Let's not worry about stripping symbols from components if space savings will be negligible. Leaving them in could help with debugging issues.
___
*[`trunk/mpf-rest-api/src/main/java/org/mitre/mpf/rest/api/subject/SubjectJobDetails.java` line 55 at r4](https://reviewable.io/reviews/openmpf/openmpf/1833#-O9jSasd2BpUUKoj7ebA:-O9jSasd2BpUUKoj7ebB:by4exsh) ([raw file](https://github.com/openmpf/openmpf/blob/2bf62f5b63479029a6c9f7c2dd45132aaf6aab2a/trunk/mpf-rest-api/src/main/java/org/mitre/mpf/rest/api/subject/SubjectJobDetails.java#L55)):*
> ```Java
> 
>     // When this view is used, callbackStatus will not be included when writing out the JSON.
>     public interface OutputObjectView {
> ```

I had to do some digging to future out how this interface is applied. The only reference to it is:

```java
    @Inject
    SubjectJobResultsService(
            PropertiesUtil propertiesUtil,
            ObjectMapper objectMapper,
            SubjectJobRepo subjectJobRepo,
            JmsUtils jmsUtils,
            JobCompleteCallbackService jobCompleteCallbackService,
            TransactionTemplate transactionTemplate) {
        _propertiesUtil = propertiesUtil;
        _objectWriter = objectMapper
                .copy()
                .enable(MapperFeature.DEFAULT_VIEW_INCLUSION)
                .writerWithView(SubjectJobDetails.OutputObjectView.class);
```

`MapperFeature.DEFAULT_VIEW_INCLUSION` includes all of the properties with no view, which is everything but `callbackStatus`. It seems that the `OutputObjectView` interface only serves as a catch-all for fields without an annotation.

I think this implementation is fine, but please leave a comment near `public interface OutputObjectView` to explain how it relies on the use of `MapperFeature.DEFAULT_VIEW_INCLUSION`. Without digging deeper, as I did, it seems like `OutputObjectView` is underutilized / dead code.
___
*[`trunk/mpf-rest-api/src/main/java/org/mitre/mpf/rest/api/subject/SubjectJobRequest.java` line 50 at r4](https://reviewable.io/reviews/openmpf/openmpf/1833#-O9jXFq94TrSqB8TI86g:-O9jXFq94TrSqB8TI86h:b-dmzkmd) ([raw file](https://github.com/openmpf/openmpf/blob/2bf62f5b63479029a6c9f7c2dd45132aaf6aab2a/trunk/mpf-rest-api/src/main/java/org/mitre/mpf/rest/api/subject/SubjectJobRequest.java#L50)):*
> ```Java
> 
>         @NotEmpty
>         Collection<Long> detectionJobIds,
> ```

Leaving a note here to mention that we talked about supporting a single-shot version of subject-tracking where this is allowed to be empty / missing. You said that will most likely be implemented as a separate REST call. Will that have a separate request class?
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/PipelineController.java` line 53 at r1](https://reviewable.io/reviews/openmpf/openmpf/1833#-O6TXywd37YuDUtSO2m8:-O9WdMnjAgelZ7jSVk9Q:bvtcfge) ([raw file](https://github.com/openmpf/openmpf/blob/0dbc6ef40baa41fa5423e546ffd8e31e4829adef/trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/PipelineController.java#L53)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

It was causing issues with Spring test. I think `@Scope("request")` is for when you want the controller to maintain state, but just for a single request. If there is no state, then we are  safe to re-use the same instance for multiple requests.

From https://docs.spring.io/spring-framework/reference/core/beans/factory-scopes.html#beans-factory-scopes-prototype:
> As a rule, you should use the prototype scope for all stateful beans and the **singleton scope for stateless beans**.
</blockquote></details>

Ok. Singleton scope is the default.
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessorImpl.java` line 59 at r4](https://reviewable.io/reviews/openmpf/openmpf/1833#-O9jf9o36dYxEP98XjL6:-O9jf9o36dYxEP98XjL7:bjiueao) ([raw file](https://github.com/openmpf/openmpf/blob/2bf62f5b63479029a6c9f7c2dd45132aaf6aab2a/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessorImpl.java#L59)):*
> ```Java
> import org.apache.http.entity.StringEntity;
> import org.mitre.mpf.interop.JsonAction;
> import org.mitre.mpf.mvc.security.OAuthClientTokenProvider;
> ```

Unused imports:

```
import org.apache.http.HttpResponse;
import org.apache.http.client.config.RequestConfig;
import org.apache.http.client.methods.HttpGet;
import org.apache.http.client.methods.HttpPost;
import org.apache.http.client.methods.HttpUriRequest;
import org.apache.http.client.utils.URIBuilder;
import org.apache.http.entity.ContentType;
import org.apache.http.entity.StringEntity;
import org.mitre.mpf.mvc.security.OAuthClientTokenProvider;
import org.mitre.mpf.interop.JsonCallbackBody;
```
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/subject/SubjectJobProcessors.java` line 67 at r1](https://reviewable.io/reviews/openmpf/openmpf/1833#-O6U7FFU9uo9xV1tfssX:-O9RT6kW-fpkGSH_cfZM:b-6ni6yl) ([raw file](https://github.com/openmpf/openmpf/blob/8ab9fa38eb9991fb3edc8d20e9f13ede523eaf47/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/subject/SubjectJobProcessors.java#L67)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

`openmpfVersion` and `externalJobId`
</blockquote></details>

Ok. I don't think `siteId` is useful and `timing` can be added in later.
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/entities/persistent/DbSubjectJobOutput.java` line 45 at r1](https://reviewable.io/reviews/openmpf/openmpf/1833#-O6SkVoIBSZ1txMV2fH-:-O9RTkMF5gNdMtL1yYmj:b9jn793) ([raw file](https://github.com/openmpf/openmpf/blob/8ab9fa38eb9991fb3edc8d20e9f13ede523eaf47/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/entities/persistent/DbSubjectJobOutput.java#L45)):*
> don't provide the consistency guarantees of SQL database

What do you mean by "consistency guarantees"? Can you provide an example of a situation where saving to the SQL DB is a better choice? I just trying to understand your reasoning.

I think this will cause the SQL DB to blow up in size for production loads.
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/SubjectJobResultsService.java` line 172 at r1](https://reviewable.io/reviews/openmpf/openmpf/1833#-O6SqXhmAbBjvCRGs4Pj:-O6SqXhmAbBjvCRGs4Pk:b563he4) ([raw file](https://github.com/openmpf/openmpf/blob/8ab9fa38eb9991fb3edc8d20e9f13ede523eaf47/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/SubjectJobResultsService.java#L [...]

2024-12-09 16:29 UTC, brosenberg42 reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1833)* status: 103 of 245 files reviewed, 12 unresolved discussions (waiting on @jrobble)

___
*[`trunk/mpf-rest-api/src/main/java/org/mitre/mpf/rest/api/subject/SubjectJobDetails.java` line 55 at r4](https://reviewable.io/reviews/openmpf/openmpf/1833#-O9jSasd2BpUUKoj7ebA:-ODg8nEu4aUqocYdPOmz:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/2bf62f5b63479029a6c9f7c2dd45132aaf6aab2a/trunk/mpf-rest-api/src/main/java/org/mitre/mpf/rest/api/subject/SubjectJobDetails.java#L55)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I had to do some digging to future out how this interface is applied. The only reference to it is:

```java
    @Inject
    SubjectJobResultsService(
            PropertiesUtil propertiesUtil,
            ObjectMapper objectMapper,
            SubjectJobRepo subjectJobRepo,
            JmsUtils jmsUtils,
            JobCompleteCallbackService jobCompleteCallbackService,
            TransactionTemplate transactionTemplate) {
        _propertiesUtil = propertiesUtil;
        _objectWriter = objectMapper
                .copy()
                .enable(MapperFeature.DEFAULT_VIEW_INCLUSION)
                .writerWithView(SubjectJobDetails.OutputObjectView.class);
```

`MapperFeature.DEFAULT_VIEW_INCLUSION` includes all of the properties with no view, which is everything but `callbackStatus`. It seems that the `OutputObjectView` interface only serves as a catch-all for fields without an annotation.

I think this implementation is fine, but please leave a comment near `public interface OutputObjectView` to explain how it relies on the use of `MapperFeature.DEFAULT_VIEW_INCLUSION`. Without digging deeper, as I did, it seems like `OutputObjectView` is underutilized / dead code.
</blockquote></details>

Done.
___
*[`trunk/mpf-rest-api/src/main/java/org/mitre/mpf/rest/api/subject/SubjectJobRequest.java` line 50 at r4](https://reviewable.io/reviews/openmpf/openmpf/1833#-O9jXFq94TrSqB8TI86g:-ODfxK3F-rcfNd3pAKQ6:b2nhswy) ([raw file](https://github.com/openmpf/openmpf/blob/2bf62f5b63479029a6c9f7c2dd45132aaf6aab2a/trunk/mpf-rest-api/src/main/java/org/mitre/mpf/rest/api/subject/SubjectJobRequest.java#L50)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Leaving a note here to mention that we talked about supporting a single-shot version of subject-tracking where this is allowed to be empty / missing. You said that will most likely be implemented as a separate REST call. Will that have a separate request class?
</blockquote></details>

Yes
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessorImpl.java` line 59 at r4](https://reviewable.io/reviews/openmpf/openmpf/1833#-O9jf9o36dYxEP98XjL6:-ODfxU1t5vqV-7Xl0Z84:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/2bf62f5b63479029a6c9f7c2dd45132aaf6aab2a/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessorImpl.java#L59)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Unused imports:

```
import org.apache.http.HttpResponse;
import org.apache.http.client.config.RequestConfig;
import org.apache.http.client.methods.HttpGet;
import org.apache.http.client.methods.HttpPost;
import org.apache.http.client.methods.HttpUriRequest;
import org.apache.http.client.utils.URIBuilder;
import org.apache.http.entity.ContentType;
import org.apache.http.entity.StringEntity;
import org.mitre.mpf.mvc.security.OAuthClientTokenProvider;
import org.mitre.mpf.interop.JsonCallbackBody;
```
</blockquote></details>

Done.
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/SubjectJobResultsService.java` line 172 at r1](https://reviewable.io/reviews/openmpf/openmpf/1833#-O6SqXhmAbBjvCRGs4Pj:-ODfyHcE5TArYX3CiCU7:bm7cyvo) ([raw file](https://github.com/openmpf/openmpf/blob/8ab9fa38eb9991fb3edc8d20e9f13ede523eaf47/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/SubjectJobResultsService.java#L172)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Is there a unit test for this?
</blockquote></details>

TestSubjectJobResultsService.canHandleIoExceptionWhenSavingJson
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/SubjectJobResultsService.java` line 178 at r4](https://reviewable.io/reviews/openmpf/openmpf/1833#-O9jlf9D0DdSrNwTWBWW:-ODfxbrc1MnthKAe5JMA:b32w12) ([raw file](https://github.com/openmpf/openmpf/blob/2bf62f5b63479029a6c9f7c2dd45132aaf6aab2a/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/SubjectJobResultsService.java#L178)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I haven't checked all of the flows. Is it possible to send more than one callback per job? I'm wondering if we should do something to prevent that.

Just making sure we thought of that possibility.
</blockquote></details>

No
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/JmsUtils.java` line 89 at r1](https://reviewable.io/reviews/openmpf/openmpf/1833#-O6SOhtvDgHWzWpCNhj2:-ODfySpYAn5OSXecCsm0:b-ymmsex) ([raw file](https://github.com/openmpf/openmpf/blob/8ab9fa38eb9991fb3edc8d20e9f13ede523eaf47/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/JmsUtils.java#L89)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Thanks for making this change. Are you planning on going back and renaming more things to include "detection"? For example, in Swagger we have "job-controller" and "subject-job-controller". To be more clear, the former should be "detection-job-controller".
</blockquote></details>

Maybe for some of the user facing swagger stuff, but not most of the internal stuff. Re-naming things to include "Batch" was a mistake. I don't want to repeat the same mistake. It also makes the current situation worse because `DetectionJob` is long and `BatchDetectionJob` is even worse. 
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/PropertiesUtil.java` line 146 at r1](https://reviewable.io/reviews/openmpf/openmpf/1833#-O6SP4yA2V90oIp5g31n:-ODg2Z5j9X9uyBqEhS9N:bej1m24) ([raw file](https://github.com/openmpf/openmpf/blob/8ab9fa38eb9991fb3edc8d20e9f13ede523eaf47/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/PropertiesUtil.java#L146)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please change the name of the variable as well.
</blockquote></details>

I haven't been convinced that adding "detection" to most of the code is a good idea. Assuming you next ask me to change the name of the methods that use that variable, that results in the word "detection" being added to the code 18 times.
___
*[`trunk/workflow-manager/src/main/webapp/resources/js/controllers/admin/AdminComponentRegistrationCtrl.js` line 67 at r1](https://reviewable.io/reviews/openmpf/openmpf/1833#-O6T_kxZ7rALN39kQf97:-ODg8tyJ044GahrtIigR:b-79um07) ([raw file](https://github.com/openmpf/openmpf/blob/8ab9fa38eb9991fb3edc8d20e9f13ede523eaf47/trunk/workflow-manager/src/main/webapp/resources/js/controllers/admin/AdminComponentRegistrationCtrl.js#L67)):*
> When we talk about components in our verbal discussions we have to specify which ones we're talking about.

This isn't true. In conversations, "component" still means "detection component" and we only specify if we are talking about subject tracking. People don't just change the words they use because they "officially" changed.
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/entities/persistent/DbSubjectJobOutput.java` line 45 at r1](https://reviewable.io/reviews/openmpf/openmpf/1833#-O6SkVoIBSZ1txMV2fH-:-ODg7zoMD-dbmQsjtG_X:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/8ab9fa38eb9991fb3edc8d20e9f13ede523eaf47/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/da [...]

2024-12-20 21:15 UTC, jrobble requested changes
> Reviewed 142 of 163 files at r5.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1833)* status: 243 of 245 files reviewed, 10 unresolved discussions (waiting on @brosenberg42)

___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/JmsUtils.java` line 89 at r1](https://reviewable.io/reviews/openmpf/openmpf/1833#-O6SOhtvDgHWzWpCNhj2:-OE_p_DG-WrQVL8fVbe_:b-szfgmq) ([raw file](https://github.com/openmpf/openmpf/blob/8ab9fa38eb9991fb3edc8d20e9f13ede523eaf47/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/JmsUtils.java#L89)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

Maybe for some of the user facing swagger stuff, but not most of the internal stuff. Re-naming things to include "Batch" was a mistake. I don't want to repeat the same mistake. It also makes the current situation worse because `DetectionJob` is long and `BatchDetectionJob` is even worse.
</blockquote></details>

We agree that it's ugly. As discussed elsewhere, maybe a cleaner approach is to use package names, name spaces, and/or class names to separate the behavior.
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/PropertiesUtil.java` line 146 at r1](https://reviewable.io/reviews/openmpf/openmpf/1833#-O6SP4yA2V90oIp5g31n:-OEVRzkdCK8AXX09AEjQ:b-6wjrqa) ([raw file](https://github.com/openmpf/openmpf/blob/8ab9fa38eb9991fb3edc8d20e9f13ede523eaf47/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/PropertiesUtil.java#L146)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

I haven't been convinced that adding "detection" to most of the code is a good idea. Assuming you next ask me to change the name of the methods that use that variable, that results in the word "detection" being added to the code 18 times.
</blockquote></details>

It's for clarity. Currently, "outputObjectsDirectory" seems like a fine place to put subject tracking outputs as well as detection outputs. The code needs to be self-explanatory.
___
*[`trunk/workflow-manager/src/main/webapp/resources/js/controllers/admin/AdminComponentRegistrationCtrl.js` line 67 at r1](https://reviewable.io/reviews/openmpf/openmpf/1833#-O6T_kxZ7rALN39kQf97:-OE_1eeN6GUVXr91WacQ:bv09sig) ([raw file](https://github.com/openmpf/openmpf/blob/8ab9fa38eb9991fb3edc8d20e9f13ede523eaf47/trunk/workflow-manager/src/main/webapp/resources/js/controllers/admin/AdminComponentRegistrationCtrl.js#L67)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

> When we talk about components in our verbal discussions we have to specify which ones we're talking about.

This isn't true. In conversations, "component" still means "detection component" and we only specify if we are talking about subject tracking. People don't just change the words they use because they "officially" changed.
</blockquote></details>

Per our discussion, it's worth considering using separate name spaces or class files so that we don't have to rename every method / variable.
___
*[`trunk/mpf-rest-api/src/main/java/org/mitre/mpf/rest/api/subject/SubjectJobResult.java` line 32 at r1](https://reviewable.io/reviews/openmpf/openmpf/1833#-O6XU2eO4a2fGxLhwwa8:-O6XU2ePD_m-ftAGVQGr:b-j3wq6y) ([raw file](https://github.com/openmpf/openmpf/blob/8ab9fa38eb9991fb3edc8d20e9f13ede523eaf47/trunk/mpf-rest-api/src/main/java/org/mitre/mpf/rest/api/subject/SubjectJobResult.java#L32)):*
> ```Java
> import java.util.Map;
> 
> public record SubjectJobResult(
> ```

No *Json POJO files? How will we generate the Interop schema?

We need to check with consumers if they're okay with processing the JSON directly without an interop package.
___
*[`trunk/workflow-manager/src/main/webapp/resources/layouts/subject-jobs.html` line 41 at r1](https://reviewable.io/reviews/openmpf/openmpf/1833#-O7Zeq9JBIrdsssS_9Ri:-O7Zeq9K3DMHIkpdd-uU:b-jkwdsu) ([raw file](https://github.com/openmpf/openmpf/blob/8ab9fa38eb9991fb3edc8d20e9f13ede523eaf47/trunk/workflow-manager/src/main/webapp/resources/layouts/subject-jobs.html#L41)):*
> ```HTML
>                     <th>Id</th>
>                     <th>Component</th>
>                     <th>Time Received</th>
> ```

TODO: Ensure "Callback" and TiesDB support.

---

As discussed, this information will be represented in the table some way so that it's clear at a glance there was a callback / TiesDB issue. The user may have to expand the entry (row) to get more information. There are different ways to consider designing the job table UI.
___
*[`trunk/subject-tracking/executor/CMakeLists.txt` line 27 at r5](https://reviewable.io/reviews/openmpf/openmpf/1833#-OEZzl9CBZsWx_aj3K_e:-OEZzl9CBZsWx_aj3K_f:bdk345b) ([raw file](https://github.com/openmpf/openmpf/blob/6b4b54ab795c07a7bbd5ddc6ed30a9dcac4f8803/trunk/subject-tracking/executor/CMakeLists.txt#L27)):*
> ```CMake
> #############################################################################
> 
> file(GLOB_RECURSE SRC_FILES *.py)
> ```

Please leave a comment about why this *.py line is necessary.


<!-- Sent from Reviewable.io -->

2025-01-02 18:17 UTC, brosenberg42 reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1833)* status: 240 of 245 files reviewed, 10 unresolved discussions (waiting on @jrobble)

___
*[`trunk/mpf-rest-api/src/main/java/org/mitre/mpf/rest/api/subject/SubjectJobResult.java` line 32 at r1](https://reviewable.io/reviews/openmpf/openmpf/1833#-O6XU2eO4a2fGxLhwwa8:-OFcBr-J5HjjxVxi_H-w:bhm7pn4) ([raw file](https://github.com/openmpf/openmpf/blob/8ab9fa38eb9991fb3edc8d20e9f13ede523eaf47/trunk/mpf-rest-api/src/main/java/org/mitre/mpf/rest/api/subject/SubjectJobResult.java#L32)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

No *Json POJO files? How will we generate the Interop schema?

We need to check with consumers if they're okay with processing the JSON directly without an interop package.
</blockquote></details>

We can move some of this stuff to the interop package. We just need to change the version of Java used for the interop package from 8 to 16 so we can use records. 
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/JmsUtils.java` line 89 at r1](https://reviewable.io/reviews/openmpf/openmpf/1833#-O6SOhtvDgHWzWpCNhj2:-OFcBSoZ2zooRkO0u9Zb:bl85a6k) ([raw file](https://github.com/openmpf/openmpf/blob/8ab9fa38eb9991fb3edc8d20e9f13ede523eaf47/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/JmsUtils.java#L89)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

We agree that it's ugly. As discussed elsewhere, maybe a cleaner approach is to use package names, name spaces, and/or class names to separate the behavior.
</blockquote></details>

Added to: https://github.com/openmpf/openmpf/issues/1866
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/PropertiesUtil.java` line 146 at r1](https://reviewable.io/reviews/openmpf/openmpf/1833#-O6SP4yA2V90oIp5g31n:-OFby6eD8dookkqMBqmJ:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/8ab9fa38eb9991fb3edc8d20e9f13ede523eaf47/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/PropertiesUtil.java#L146)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

It's for clarity. Currently, "outputObjectsDirectory" seems like a fine place to put subject tracking outputs as well as detection outputs. The code needs to be self-explanatory.
</blockquote></details>

Done.
___
*[`trunk/workflow-manager/src/main/webapp/resources/js/controllers/admin/AdminComponentRegistrationCtrl.js` line 67 at r1](https://reviewable.io/reviews/openmpf/openmpf/1833#-O6T_kxZ7rALN39kQf97:-OFcBL3h9H-7GP2gaST_:bc6zwsm) ([raw file](https://github.com/openmpf/openmpf/blob/8ab9fa38eb9991fb3edc8d20e9f13ede523eaf47/trunk/workflow-manager/src/main/webapp/resources/js/controllers/admin/AdminComponentRegistrationCtrl.js#L67)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Per our discussion, it's worth considering using separate name spaces or class files so that we don't have to rename every method / variable.
</blockquote></details>

Added to https://github.com/openmpf/openmpf/issues/1866
___
*[`trunk/workflow-manager/src/main/webapp/resources/layouts/subject-jobs.html` line 41 at r1](https://reviewable.io/reviews/openmpf/openmpf/1833#-O7Zeq9JBIrdsssS_9Ri:-OFcBND1Af8cbmsqVgwv:bc6zwsm) ([raw file](https://github.com/openmpf/openmpf/blob/8ab9fa38eb9991fb3edc8d20e9f13ede523eaf47/trunk/workflow-manager/src/main/webapp/resources/layouts/subject-jobs.html#L41)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

TODO: Ensure "Callback" and TiesDB support.

---

As discussed, this information will be represented in the table some way so that it's clear at a glance there was a callback / TiesDB issue. The user may have to expand the entry (row) to get more information. There are different ways to consider designing the job table UI.
</blockquote></details>

Added to https://github.com/openmpf/openmpf/issues/1866
___
*[`trunk/subject-tracking/executor/CMakeLists.txt` line 27 at r5](https://reviewable.io/reviews/openmpf/openmpf/1833#-OEZzl9CBZsWx_aj3K_e:-OFbn1x40U9pVkaYlHR9:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/6b4b54ab795c07a7bbd5ddc6ed30a9dcac4f8803/trunk/subject-tracking/executor/CMakeLists.txt#L27)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please leave a comment about why this *.py line is necessary.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2025-02-05 18:33 UTC, jrobble reviewed
> Reviewed 1 of 2 files at r6, 2 of 4 files at r7, 127 of 127 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1833)* status: all files reviewed, 3 unresolved discussions (waiting on @jrobble)

___
*[a discussion](https://reviewable.io/reviews/openmpf/openmpf/1833#-O7ZaeOMD6XycnNnSo0u:-OIMNMvDDknyDIataFVw:b-kzicbr) (no related file):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I tried getting subject tracking working via `mpf start`. Here's what happened:

```
2024-09-11 15:09:32,320 INFO [main] o.m.m.w.s.c.AnsibleDeploymentService - TASK [Send the component descriptor path to stdout] ****************************
2024-09-11 15:09:32,375 INFO [main] o.m.m.w.s.c.AnsibleDeploymentService - ok: [localhost] => {
2024-09-11 15:09:32,376 INFO [main] o.m.m.w.s.c.AnsibleDeploymentService -     "msg": "COMPONENT_DESCRIPTOR_PATH=/home/mpf/openmpf-projects/openmpf/trunk/install/plugins/PythonSubjectComponent/descriptor/descriptor.json"
2024-09-11 15:09:32,376 INFO [main] o.m.m.w.s.c.AnsibleDeploymentService - }
2024-09-11 15:09:32,385 INFO [main] o.m.m.w.s.c.AnsibleDeploymentService - 
2024-09-11 15:09:32,385 INFO [main] o.m.m.w.s.c.AnsibleDeploymentService - TASK [Check if component has wheelhouse directory] *****************************
2024-09-11 15:09:32,639 INFO [main] o.m.m.w.s.c.AnsibleDeploymentService - ok: [localhost]
2024-09-11 15:09:32,647 INFO [main] o.m.m.w.s.c.AnsibleDeploymentService - 
2024-09-11 15:09:32,647 INFO [main] o.m.m.w.s.c.AnsibleDeploymentService - TASK [Upgrade pip for Python component virtualenv] *****************************
2024-09-11 15:09:37,538 INFO [main] o.m.m.w.s.c.AnsibleDeploymentService - changed: [localhost]
2024-09-11 15:09:37,544 INFO [main] o.m.m.w.s.c.AnsibleDeploymentService - 
2024-09-11 15:09:37,544 INFO [main] o.m.m.w.s.c.AnsibleDeploymentService - TASK [Setup virtualenv for Python setuptools-based component] ******************
2024-09-11 15:09:38,114 INFO [main] o.m.m.w.s.c.AnsibleDeploymentService - fatal: [localhost]: FAILED! => {"changed": false, "cmd": ["/home/mpf/openmpf-projects/openmpf/trunk/install/plugins/PythonSubjectComponent//venv/bin/pip3", "install", "--find-links", "/home/mpf/openmpf-projects/openmpf/trunk/install/plugins/PythonSubjectComponent//wheelhouse", "--no-index", " "], "msg": "\n:stderr: ERROR: Invalid requirement: '': Expected package name at the start of dependency specifier\n    \n    ^\n"}
```

As discussed, more work needs to be done to enable non-Docker deployments.
</blockquote></details>

Added to [Finish subject tracking implementation #1866](https://github.com/openmpf/openmpf/issues/1866)
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/StorageService.java` line 238 at r5](https://reviewable.io/reviews/openmpf/openmpf/1833#-OEWsqM557pk59G0OArs:-OEWsqM557pk59G0OArt:bn1vty8) ([raw file](https://github.com/openmpf/openmpf/blob/6b4b54ab795c07a7bbd5ddc6ed30a9dcac4f8803/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/StorageService.java#L238)):*
> ```Java
>             remoteException = ex;
>             var warning =
>                     "The output object was stored locally because storing it remotely failed "
> ```

Detection jobs use an issue code:

```
outputObject.addWarnings(0, List.of(new JsonIssueDetails(
                    IssueSources.WORKFLOW_MANAGER.toString(), IssueCodes.REMOTE_STORAGE_UPLOAD.toString(),
````

---

Added to [Finish subject tracking implementation #1866](https://github.com/openmpf/openmpf/issues/1866)


<!-- Sent from Reviewable.io -->

2025-02-06 04:05 UTC, jrobble requested changes
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1833)* status: all files reviewed, 3 unresolved discussions (waiting on @brosenberg42)

___
*[`trunk/mpf-rest-api/src/main/java/org/mitre/mpf/rest/api/subject/SubjectJobResult.java` line 32 at r1](https://reviewable.io/reviews/openmpf/openmpf/1833#-O6XU2eO4a2fGxLhwwa8:-OHe-nDz20N-m73Z_vvj:ba7vgsr) ([raw file](https://github.com/openmpf/openmpf/blob/8ab9fa38eb9991fb3edc8d20e9f13ede523eaf47/trunk/mpf-rest-api/src/main/java/org/mitre/mpf/rest/api/subject/SubjectJobResult.java#L32)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

We can move some of this stuff to the interop package. We just need to change the version of Java used for the interop package from 8 to 16 so we can use records.
</blockquote></details>

I generate the *.schema.json files for the interop package by running `openmpf-projects/openmpf/trunk/interop/src/test/java/org/mitre/mpf/SchemaCreator.java`. I added the last two class entries to this list while testing this:

```java
        for(Class clazz : new Class[] {
                // JsonAction.class,
                JsonCallbackBody.class,
                // JsonDetectionOutputObject.class,
                // JsonDetectionProcessingError.class,
                // JsonMarkupOutputObject.class,
                // JsonMediaOutputObject.class,
                JsonOutputObject.class,
                // JsonPipeline.class,
                // JsonTask.class,
                // JsonTrackOutputObject.class
                JsonSegmentSummaryReport.class,
                JsonHealthReportCollection.class,
                SubjectJobRequest.class,
                SubjectJobResult.class
```

I believe that's all we need to add since the request and result encompass the other `org.mitre.mpf.interop.subject` classes.

Please add those entries to the list and any others you think are necessary.
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/JmsUtils.java` line 117 at r1](https://reviewable.io/reviews/openmpf/openmpf/1833#-O6SMSLvEW8KB41IVIjk:-O6SMSLvEW8KB41IVIjl:b-v2j9l9) ([raw file](https://github.com/openmpf/openmpf/blob/8ab9fa38eb9991fb3edc8d20e9f13ede523eaf47/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/JmsUtils.java#L117)):*
> ```Java
>     }
> 
>     public void cancelSubjectJob(long jobId, String componentName) {
> ```

If one or more of the detection jobs have errors or are cancelled then the subject tracking job should generate a warning.
___
*[`trunk/workflow-manager/pom.xml` line 893 at r9](https://reviewable.io/reviews/openmpf/openmpf/1833#-OIOJu7hDD5QUs6dsK2A:-OIOJu7hDD5QUs6dsK2B:b-ba2b8d) ([raw file](https://github.com/openmpf/openmpf/blob/bf7ed95ecb99e885c03319fb1d5ee06f1e77b7f5/trunk/workflow-manager/pom.xml#L893)):*
> ```XML
>                 <!-- Enables the Querydsl annotation processor. At compile time it will generate
>                      classes for each class annotated with @Entity. The generated class name is a
>                      "Q" followed by the @Enitity class name. -->
> ```

Check spelling: "@Enitity"


<!-- Sent from Reviewable.io -->

2025-02-07 15:05 UTC, brosenberg42 reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1833)* status: 210 of 314 files reviewed, 3 unresolved discussions (waiting on @jrobble)

___
*[`trunk/workflow-manager/pom.xml` line 893 at r9](https://reviewable.io/reviews/openmpf/openmpf/1833#-OIOJu7hDD5QUs6dsK2A:-OIQFPED4ylU2kX82QIM:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/bf7ed95ecb99e885c03319fb1d5ee06f1e77b7f5/trunk/workflow-manager/pom.xml#L893)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Check spelling: "@Enitity"
</blockquote></details>

Done.
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/JmsUtils.java` line 117 at r1](https://reviewable.io/reviews/openmpf/openmpf/1833#-O6SMSLvEW8KB41IVIjk:-OIVwNriAD69uRb0k73B:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/8ab9fa38eb9991fb3edc8d20e9f13ede523eaf47/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/JmsUtils.java#L117)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

If one or more of the detection jobs have errors or are cancelled then the subject tracking job should generate a warning.
</blockquote></details>

Done.
___
*[`trunk/mpf-rest-api/src/main/java/org/mitre/mpf/rest/api/subject/SubjectJobResult.java` line 32 at r1](https://reviewable.io/reviews/openmpf/openmpf/1833#-O6XU2eO4a2fGxLhwwa8:-OIVwLXI-S2y8cPOlQ0I:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/8ab9fa38eb9991fb3edc8d20e9f13ede523eaf47/trunk/mpf-rest-api/src/main/java/org/mitre/mpf/rest/api/subject/SubjectJobResult.java#L32)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I generate the *.schema.json files for the interop package by running `openmpf-projects/openmpf/trunk/interop/src/test/java/org/mitre/mpf/SchemaCreator.java`. I added the last two class entries to this list while testing this:

```java
        for(Class clazz : new Class[] {
                // JsonAction.class,
                JsonCallbackBody.class,
                // JsonDetectionOutputObject.class,
                // JsonDetectionProcessingError.class,
                // JsonMarkupOutputObject.class,
                // JsonMediaOutputObject.class,
                JsonOutputObject.class,
                // JsonPipeline.class,
                // JsonTask.class,
                // JsonTrackOutputObject.class
                JsonSegmentSummaryReport.class,
                JsonHealthReportCollection.class,
                SubjectJobRequest.class,
                SubjectJobResult.class
```

I believe that's all we need to add since the request and result encompass the other `org.mitre.mpf.interop.subject` classes.

Please add those entries to the list and any others you think are necessary.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2025-02-08 01:48 UTC, jrobble requested changes
> Reviewed 3 of 104 files at r10.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1833)* status: 213 of 314 files reviewed, 3 unresolved discussions (waiting on @brosenberg42)

___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessorImpl.java` line 283 at r10](https://reviewable.io/reviews/openmpf/openmpf/1833#-OIWAwHQ43sv_NcT5Ohb:-OIWAwHR4ld3S5B9Z-9A:b-8afbbb) ([raw file](https://github.com/openmpf/openmpf/blob/2c4913e5f635ebf29f3b04e46f9ba07f2e9d7048/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessorImpl.java#L283)):*
> ```Java
>             DetectionError.NETWORK_ERROR,
>             DetectionError.UNRECOGNIZED_DETECTION_ERROR,
>             DetectionError.UNSUPPORTED_DATA_TYPE);
> ```

I feel like these should be kept with the error code definitions in `DetectionProtobuf.java` in the hopes that a dev might add something to this list if and when they add a new error code.

Alternatively, those definitions should take a parameter in the constructor to indicate if they're fatal.
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessorImpl.java` line 294 at r10](https://reviewable.io/reviews/openmpf/openmpf/1833#-OIWWQ5Z1uF0cNOKO3CY:-OIWWQ5Z1uF0cNOKO3CZ:b-hrny1p) ([raw file](https://github.com/openmpf/openmpf/blob/2c4913e5f635ebf29f3b04e46f9ba07f2e9d7048/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessorImpl.java#L294)):*
> ```Java
>             return completionStatus;
>         }
>         return job.getDetectionProcessingErrors()
> ```

So, if the overall job status is `COMPLETE_WITH_ERRORS`, and all of the media has failed, then we check all of the detection errors across all of the media to see if any of them are fatal. If so, we transition the job status to fatal error.

I believe we set the entire job as `COMPLETE_WITH_ERRORS` if only one piece of media fails. Only one sub-job needs a detection error to mark a piece of media as failed. That means we let one sub-job for that one piece of media characterize the whole job.

If we were to follow this same approach then one fatal error code from one sub-job for one piece of media should result in characterizing the whole job as fatal (resulting in the final `ERROR` status). Instead, you put an additional check in place that all media has to fail, not just the one with the fatal error. I'm not sure which approach is better.

Currently, fatal errors are only used when there is a problem splitting a job into pieces, being unable to check ties db when configured to do so, and being unable to generate the output object. In all of those cases the job will not have any valid tracks. In your current approach at least one piece of media may generate a valid track for a sub-job, even if every other sub-job for that media fails.

I've had the mindset that fatal (the `ERROR` status) means that we could not do any useful work. I think that if one sub-job can generate at least one valid track then `COMPLETE_WITH_ERRORS` is be more fitting. I'm not saying it has to be done that way.


<!-- Sent from Reviewable.io -->

2025-02-10 12:28 UTC, brosenberg42 reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1833)* status: 213 of 314 files reviewed, 3 unresolved discussions (waiting on @jrobble)

___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessorImpl.java` line 283 at r10](https://reviewable.io/reviews/openmpf/openmpf/1833#-OIWAwHQ43sv_NcT5Ohb:-OIjpHOfEOZYhXrJpx00:b-ajupmj) ([raw file](https://github.com/openmpf/openmpf/blob/2c4913e5f635ebf29f3b04e46f9ba07f2e9d7048/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessorImpl.java#L283)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I feel like these should be kept with the error code definitions in `DetectionProtobuf.java` in the hopes that a dev might add something to this list if and when they add a new error code.

Alternatively, those definitions should take a parameter in the constructor to indicate if they're fatal.
</blockquote></details>

Reverted changes since they are unrelated.
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessorImpl.java` line 294 at r10](https://reviewable.io/reviews/openmpf/openmpf/1833#-OIWWQ5Z1uF0cNOKO3CY:-OIjpIJp96-QQXSDpO51:bs247hh) ([raw file](https://github.com/openmpf/openmpf/blob/2c4913e5f635ebf29f3b04e46f9ba07f2e9d7048/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessorImpl.java#L294)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

So, if the overall job status is `COMPLETE_WITH_ERRORS`, and all of the media has failed, then we check all of the detection errors across all of the media to see if any of them are fatal. If so, we transition the job status to fatal error.

I believe we set the entire job as `COMPLETE_WITH_ERRORS` if only one piece of media fails. Only one sub-job needs a detection error to mark a piece of media as failed. That means we let one sub-job for that one piece of media characterize the whole job.

If we were to follow this same approach then one fatal error code from one sub-job for one piece of media should result in characterizing the whole job as fatal (resulting in the final `ERROR` status). Instead, you put an additional check in place that all media has to fail, not just the one with the fatal error. I'm not sure which approach is better.

Currently, fatal errors are only used when there is a problem splitting a job into pieces, being unable to check ties db when configured to do so, and being unable to generate the output object. In all of those cases the job will not have any valid tracks. In your current approach at least one piece of media may generate a valid track for a sub-job, even if every other sub-job for that media fails.

I've had the mindset that fatal (the `ERROR` status) means that we could not do any useful work. I think that if one sub-job can generate at least one valid track then `COMPLETE_WITH_ERRORS` is be more fitting. I'm not saying it has to be done that way.
</blockquote></details>

Reverted changes since they are unrelated.


<!-- Sent from Reviewable.io -->

2025-02-10 17:16 UTC, jrobble approved these changes
> Reviewed 2 of 104 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1833)* status: 216 of 314 files reviewed, all discussions resolved (waiting on @brosenberg42)



<!-- Sent from Reviewable.io -->

2025-02-10 17:16 UTC, jrobble approved these changes

2025-02-10 17:29 UTC, merged