Feat/json path
openmpf/openmpf pull request #1850
Opened 2024-09-20 17:52 UTC by brosenberg42

**Issues:**

- https://github.com/openmpf/openmpf/issues/1 < Example
- https://github.com/openmpf/openmpf/issues/2 < Example

If a related issue doesn't exist, then create one first and assign it to yourself.

**Related PRs:**

- https://github.com/openmpf/openmpf/pull/22 < Example
- https://github.com/openmpf/openmpf/pull/53 < Example

Please review our [Contributor Guide](https://openmpf.github.io/docs/site/Contributor-Guide/index.html).

2024-10-09 20:16 UTC, brosenberg42 reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1850)* status: 0 of 112 files reviewed, 1 unresolved discussion (waiting on @jrobble)

___
*[`trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/service/TestJobConfigHasher.java` line 716 at r1](https://reviewable.io/reviews/openmpf/openmpf/1850#-O8mpfVe7BZreg8biA6S:-O8mu4no210HL8X9Hn3P:b-da101) ([raw file](https://github.com/openmpf/openmpf/blob/82297dba0c87098f7cf9722d3a9f4d3b58b969e4/trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/service/TestJobConfigHasher.java#L716)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Why this custom logic?
</blockquote></details>

Media selectors only work on the first stage of a pipeline. Previously, none of the tests called `pipelineElements.getAlgorithm(0, 0)`. Now, tests with media selectors do call it. The old tests still don't call  `pipelineElements.getAlgorithm(0, 0)`, so it needs to be lenient.


<!-- Sent from Reviewable.io -->

2024-10-10 20:12 UTC, jrobble requested changes
> Reviewed 112 of 112 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1850)* status: all files reviewed, 6 unresolved discussions (waiting on @brosenberg42)

___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/entities/persistent/MediaImpl.java` line 227 at r1](https://reviewable.io/reviews/openmpf/openmpf/1850#-O7eqrpv3vaPA2FmapXi:-O7eqrpv3vaPA2FmapXj:bpa6grp) ([raw file](https://github.com/openmpf/openmpf/blob/82297dba0c87098f7cf9722d3a9f4d3b58b969e4/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/entities/persistent/MediaImpl.java#L227)):*
> ```Java
>     private URI _mediaSelectorsOutput;
>     @Override
>     public URI getMediaSelectorsOutput() { return _mediaSelectorsOutput; }
> ```

Please update the data member to `_mediaSelectorOutputPath`. Update the getter and setter to use Path as well and other variable names throughout the code base.

TBH, reading your updates in this PR, it wasn't initially clear to me that the output was just a path. The name alone could mean it's the actual output text content. For example, here it's just a String:

```java
	@JsonProperty("mediaSelectorsOutput")
	private String mediaSelectorsOutput;
	public String getMediaSelectorsOutput() { return mediaSelectorsOutput; }
	public void setMediaSelectorsOutput(String uri) { mediaSelectorsOutput = uri; }
```

Elsewhere in the JSON output object we use "path" for the media, for markup, and for the artifacts fields.
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/entities/transients/Track.java` line 148 at r1](https://reviewable.io/reviews/openmpf/openmpf/1850#-O7eocER4DeCPYUhGp5V:-O7eocER4DeCPYUhGp5W:bwa6ppt) ([raw file](https://github.com/openmpf/openmpf/blob/82297dba0c87098f7cf9722d3a9f4d3b58b969e4/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/entities/transients/Track.java#L148)):*
> ```Java
>      * @param detections The collection of detections which correspond to the position of the object as it
>      *                   moves through the track.
>      * @param trackProperties Map containing the track level properties.
> ```

Update this comment block with new parameters. Feel free to remove.
___
*[`trunk/workflow-manager/src/main/resources/workflow-properties.json` line 528 at r1](https://reviewable.io/reviews/openmpf/openmpf/1850#-O7elvkwAqdWK6WxNTzR:-O7elvkx-bfHJ9GPUBzr:b923edg) ([raw file](https://github.com/openmpf/openmpf/blob/82297dba0c87098f7cf9722d3a9f4d3b58b969e4/trunk/workflow-manager/src/main/resources/workflow-properties.json#L528)):*
> ```JSON
>     },
>     {
>         "name": "SELECTOR_DELIMETER",
> ```

Please add a guide to openmpf.github.io that explains media selectors in general, and gives examples of how to use these two properties.

We can land that separately from this PR. Create a separate issue on the workboard for it and assign it to yourself.
___
*[`trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/service/TestJobConfigHasher.java` line 716 at r1](https://reviewable.io/reviews/openmpf/openmpf/1850#-O8mpfVe7BZreg8biA6S:-O8qclt-C3HZcXdzcsZ0:beuenmm) ([raw file](https://github.com/openmpf/openmpf/blob/82297dba0c87098f7cf9722d3a9f4d3b58b969e4/trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/service/TestJobConfigHasher.java#L716)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

Media selectors only work on the first stage of a pipeline. Previously, none of the tests called `pipelineElements.getAlgorithm(0, 0)`. Now, tests with media selectors do call it. The old tests still don't call  `pipelineElements.getAlgorithm(0, 0)`, so it needs to be lenient.
</blockquote></details>

Got it. Please leave a comment here explaining this. Just seems a bit strange to only do this for the first algorithm, but I understand that Mockito will throw an UnnecessaryStubbingException unless we restrict this to cases when it's actually used, or be lenient with it.
___
*[`trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/service/TestMediaSelectorsSegmenter.java` line 77 at r1](https://reviewable.io/reviews/openmpf/openmpf/1850#-O8mr3Ya-xY--qG1wnbQ:-O8mr3Ya-xY--qG1wnbR:bz7owmi) ([raw file](https://github.com/openmpf/openmpf/blob/82297dba0c87098f7cf9722d3a9f4d3b58b969e4/trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/service/TestMediaSelectorsSegmenter.java#L77)):*
> ```Java
>         assertThatExceptionOfType(WfmProcessingException.class)
>                 .isThrownBy(() -> _mediaSelectorsSegmenter.segmentMedia(media, context))
>                 .withMessageContaining("None of the media selectors matched content in the source document.");
> ```

Please make sure to mention in the documentation that an error will be thrown in this case. We don't want people thinking they can run the pipeline on random files.

Let's make this a configurable setting.
___
*[`trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/service/TestTiesDbBeforeJobCheckService.java` line 1200 at r1](https://reviewable.io/reviews/openmpf/openmpf/1850#-O8nEySr2W5I1DAn6nqo:-O8nEySr2W5I1DAn6nqp:b-37it8z) ([raw file](https://github.com/openmpf/openmpf/blob/82297dba0c87098f7cf9722d3a9f4d3b58b969e4/trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/service/TestTiesDbBeforeJobCheckService.java#L1200)):*
> ```Java
>         }
>         else {
>             mediaChecker.neq(m -> m.getMarkupResult());
> ```

Please add a comment to the code to explain.


<!-- Sent from Reviewable.io -->

2024-10-10 20:14 UTC, jrobble commented
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/entities/persistent/MediaImpl.java` line 227 at r1](https://reviewable.io/reviews/openmpf/openmpf/1850#-O7eqrpv3vaPA2FmapXi:-O8s39yl8GVxWOKGBnKJ:b-6br7rb) ([raw file](https://github.com/openmpf/openmpf/blob/82297dba0c87098f7cf9722d3a9f4d3b58b969e4/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/entities/persistent/MediaImpl.java#L227)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please update the data member to `_mediaSelectorOutputPath`. Update the getter and setter to use Path as well and other variable names throughout the code base.

TBH, reading your updates in this PR, it wasn't initially clear to me that the output was just a path. The name alone could mean it's the actual output text content. For example, here it's just a String:

```java
	@JsonProperty("mediaSelectorsOutput")
	private String mediaSelectorsOutput;
	public String getMediaSelectorsOutput() { return mediaSelectorsOutput; }
	public void setMediaSelectorsOutput(String uri) { mediaSelectorsOutput = uri; }
```

Elsewhere in the JSON output object we use "path" for the media, for markup, and for the artifacts fields.
</blockquote></details>

As discussed, change this to "uri" instead of "path".


<!-- Sent from Reviewable.io -->

2024-10-10 20:15 UTC, jrobble commented
*[`trunk/detection/executor/cpp/batch/JobContext.h` line 54 at r1](https://reviewable.io/reviews/openmpf/openmpf/1850#-O7_5edb8Rrj6kLWra_t:-O7_5edb8Rrj6kLWra_u:b-c4vbap) ([raw file](https://github.com/openmpf/openmpf/blob/82297dba0c87098f7cf9722d3a9f4d3b58b969e4/trunk/detection/executor/cpp/batch/JobContext.h#L54)):*
> ```objc
>     const int action_index;
> 
>     const std::optional<std::string> selected_content;
> ```

For images, videos, and audio files we don't pass any of the content in AMQ. Consider renaming this to `selected_text_content` to be clear.


<!-- Sent from Reviewable.io -->

2024-10-10 20:15 UTC, jrobble commented
*[`trunk/detection/executor/cpp/batch/Messenger.cpp` line 114 at r1](https://reviewable.io/reviews/openmpf/openmpf/1850#-O8s3af738k9KPjVuDwk:-O8s3af738k9KPjVuDwl:bpngdb8) ([raw file](https://github.com/openmpf/openmpf/blob/82297dba0c87098f7cf9722d3a9f4d3b58b969e4/trunk/detection/executor/cpp/batch/Messenger.cpp#L114)):*
> ```cpp
>     if (job_context.protobuf_metadata.selected_content) {
>         message->setStringProperty(
>                 "SelectedContent", *job_context.protobuf_metadata.selected_content);
> ```

Please update this to "SelectedTextContent".


<!-- Sent from Reviewable.io -->

2024-10-11 18:05 UTC, brosenberg42 reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1850)* status: 91 of 114 files reviewed, 8 unresolved discussions (waiting on @brosenberg42 and @jrobble)

___
*[`trunk/detection/executor/cpp/batch/JobContext.h` line 54 at r1](https://reviewable.io/reviews/openmpf/openmpf/1850#-O7_5edb8Rrj6kLWra_t:-O8v3A_F-KRcLybCFjTH:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/82297dba0c87098f7cf9722d3a9f4d3b58b969e4/trunk/detection/executor/cpp/batch/JobContext.h#L54)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

For images, videos, and audio files we don't pass any of the content in AMQ. Consider renaming this to `selected_text_content` to be clear.
</blockquote></details>

Done.
___
*[`trunk/detection/executor/cpp/batch/Messenger.cpp` line 114 at r1](https://reviewable.io/reviews/openmpf/openmpf/1850#-O8s3af738k9KPjVuDwk:-O8v4UKF7ewLDVMymaCs:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/82297dba0c87098f7cf9722d3a9f4d3b58b969e4/trunk/detection/executor/cpp/batch/Messenger.cpp#L114)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please update this to "SelectedTextContent".
</blockquote></details>

Done.
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/entities/persistent/MediaImpl.java` line 227 at r1](https://reviewable.io/reviews/openmpf/openmpf/1850#-O7eqrpv3vaPA2FmapXi:-O8v5f4F93OkbsXf2R_i:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/82297dba0c87098f7cf9722d3a9f4d3b58b969e4/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/entities/persistent/MediaImpl.java#L227)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

As discussed, change this to "uri" instead of "path".
</blockquote></details>

Done.
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/entities/transients/Track.java` line 148 at r1](https://reviewable.io/reviews/openmpf/openmpf/1850#-O7eocER4DeCPYUhGp5V:-O8v5m0XC9cNL740QL6u:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/82297dba0c87098f7cf9722d3a9f4d3b58b969e4/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/entities/transients/Track.java#L148)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Update this comment block with new parameters. Feel free to remove.
</blockquote></details>

Done.
___
*[`trunk/workflow-manager/src/main/resources/workflow-properties.json` line 528 at r1](https://reviewable.io/reviews/openmpf/openmpf/1850#-O7elvkwAqdWK6WxNTzR:-O8vE8qg0vOxHZ-gJnfv:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/82297dba0c87098f7cf9722d3a9f4d3b58b969e4/trunk/workflow-manager/src/main/resources/workflow-properties.json#L528)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please add a guide to openmpf.github.io that explains media selectors in general, and gives examples of how to use these two properties.

We can land that separately from this PR. Create a separate issue on the workboard for it and assign it to yourself.
</blockquote></details>

Done.
___
*[`trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/service/TestJobConfigHasher.java` line 716 at r1](https://reviewable.io/reviews/openmpf/openmpf/1850#-O8mpfVe7BZreg8biA6S:-O8v6zBH16qqc5CE4yyK:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/82297dba0c87098f7cf9722d3a9f4d3b58b969e4/trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/service/TestJobConfigHasher.java#L716)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Got it. Please leave a comment here explaining this. Just seems a bit strange to only do this for the first algorithm, but I understand that Mockito will throw an UnnecessaryStubbingException unless we restrict this to cases when it's actually used, or be lenient with it.
</blockquote></details>

Done.
___
*[`trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/service/TestMediaSelectorsSegmenter.java` line 77 at r1](https://reviewable.io/reviews/openmpf/openmpf/1850#-O8mr3Ya-xY--qG1wnbQ:-O8wk60V87zE2VKpQLFr:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/82297dba0c87098f7cf9722d3a9f4d3b58b969e4/trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/service/TestMediaSelectorsSegmenter.java#L77)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please make sure to mention in the documentation that an error will be thrown in this case. We don't want people thinking they can run the pipeline on random files.

Let's make this a configurable setting.
</blockquote></details>

Done.
___
*[`trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/service/TestTiesDbBeforeJobCheckService.java` line 1200 at r1](https://reviewable.io/reviews/openmpf/openmpf/1850#-O8nEySr2W5I1DAn6nqo:-O8vDobb-Jf36CilRCc9:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/82297dba0c87098f7cf9722d3a9f4d3b58b969e4/trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/service/TestTiesDbBeforeJobCheckService.java#L1200)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please add a comment to the code to explain.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-23 19:04 UTC, jrobble reviewed
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1850)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @brosenberg42)



<!-- Sent from Reviewable.io -->

2025-02-13 16:48 UTC, jrobble requested changes
> Reviewed 230 of 230 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1850)* status: all files reviewed, 2 unresolved discussions (waiting on @brosenberg42)

___
*[`trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/camel/operations/TestMediaSelectorsOutputFileProcessorImpl.java` line 447 at r6](https://reviewable.io/reviews/openmpf/openmpf/1850#-OJ-AYS13qRjPKSWihjs:-OJ-AYS13qRjPKSWihjt:bafnz45) ([raw file](https://github.com/openmpf/openmpf/blob/06d56570c87d73a2fdf1a50a959d3362075cff49/trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/camel/operations/TestMediaSelectorsOutputFileProcessorImpl.java#L447)):*
> ```Java
> 
>             var mappers = new ArrayList<UnaryOperator<String>>();
>             var notPresentString = UUID.randomUUID().toString();
> ```

How is it possible for this random UUID to ever be in the map? Please explain the motivation/purpose for checking for it in the map.
___
*[`trunk/workflow-manager/src/test/java/org/mitre/mpf/mvc/controller/TestPipelineController.java` line 67 at r1](https://reviewable.io/reviews/openmpf/openmpf/1850#-OIr-sZX7_E-YVtkJgcx:-OIr-sZX7_E-YVtkJgcy:baj07ki) ([raw file](https://github.com/openmpf/openmpf/blob/82297dba0c87098f7cf9722d3a9f4d3b58b969e4/trunk/workflow-manager/src/test/java/org/mitre/mpf/mvc/controller/TestPipelineController.java#L67)):*
> ```Java
> 
> @RunWith(SpringJUnit4ClassRunner.class)
> @RunListener.ThreadSafe
> ```

Why remove these annotations? What purpose did they serve?


<!-- Sent from Reviewable.io -->

2025-02-14 13:05 UTC, brosenberg42 reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1850)* status: 122 of 284 files reviewed, 2 unresolved discussions (waiting on @jrobble)

___
*[`trunk/workflow-manager/src/test/java/org/mitre/mpf/mvc/controller/TestPipelineController.java` line 67 at r1](https://reviewable.io/reviews/openmpf/openmpf/1850#-OIr-sZX7_E-YVtkJgcx:-OJ-Wzt7AG6MN0HULkxZ:bh27k68) ([raw file](https://github.com/openmpf/openmpf/blob/82297dba0c87098f7cf9722d3a9f4d3b58b969e4/trunk/workflow-manager/src/test/java/org/mitre/mpf/mvc/controller/TestPipelineController.java#L67)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Why remove these annotations? What purpose did they serve?
</blockquote></details>

`@ContextConfiguration(classes = PipelineController.class)` is not needed because of `TestUtil.initMockMvc`
`@RunWith(SpringJUnit4ClassRunner.class)` was never needed because just using `MockMvc` is enough to get the Spring specific behavior.
`@RunListener.ThreadSafe` never did anything because we don't run tests in parallel. It also was likely wrong because MockMvc is not necessarily thread safe.
___
*[`trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/camel/operations/TestMediaSelectorsOutputFileProcessorImpl.java` line 447 at r6](https://reviewable.io/reviews/openmpf/openmpf/1850#-OJ-AYS13qRjPKSWihjs:-OJ-Y7_YDcZQM4buYwZF:b8xfmhp) ([raw file](https://github.com/openmpf/openmpf/blob/06d56570c87d73a2fdf1a50a959d3362075cff49/trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/camel/operations/TestMediaSelectorsOutputFileProcessorImpl.java#L447)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

How is it possible for this random UUID to ever be in the map? Please explain the motivation/purpose for checking for it in the map.
</blockquote></details>

I think using a UUID and naming it `notPresentString` makes it obvious we don't expect it to be mapped.  The `assertNotMapped(mapper, notPresentString);` line explains the purpose.


<!-- Sent from Reviewable.io -->

2025-02-14 15:27 UTC, jrobble approved these changes
> Reviewed 162 of 162 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1850)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @brosenberg42)



<!-- Sent from Reviewable.io -->

2025-02-21 16:06 UTC, merged