Add ability to do feed forward processing and artifact extraction based on detection properties
openmpf/openmpf pull request #1853
Opened 2024-10-11 19:59 UTC by clnowacki

**Issues:**

- https://github.com/openmpf/openmpf/issues/1841

2025-01-15 14:13 UTC, clnowacki reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1853)* status: 11 of 13 files reviewed, 2 unresolved discussions (waiting on @jrobble)

___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/artifactextraction/ArtifactExtractionSplitterImpl.java` line 354 at r1](https://reviewable.io/reviews/openmpf/openmpf/1853#-OFiAbez-yzkaBNVtl0s:-OGeI24R8wdZitlfVlIq:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/d5c9c7ca7c3b7c4617cfe4fd1b9d01820a3583b4/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/artifactextraction/ArtifactExtractionSplitterImpl.java#L354)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Make this a debug line (like the `"Will extract frame #{} with confidence = {}"` above).
</blockquote></details>

Done.
___
*[`trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/camel/operations/detection/artifactextraction/TestArtifactExtractionSplitter.java` line 674 at r1](https://reviewable.io/reviews/openmpf/openmpf/1853#-OFiDy3n1gby4nF5wAVK:-OGeIQObB45t4Av4LAEV:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/d5c9c7ca7c3b7c4617cfe4fd1b9d01820a3583b4/trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/camel/operations/detection/artifactextraction/TestArtifactExtractionSplitter.java#L674)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Grammar: "doesn't matter"
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2025-01-23 02:16 UTC, jrobble reviewed
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1853)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @clnowacki)



<!-- Sent from Reviewable.io -->

2025-01-25 02:11 UTC, jrobble requested changes
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1853)* status: all files reviewed, 1 unresolved discussion (waiting on @clnowacki)

___
*[`trunk/workflow-manager/src/main/resources/workflow-properties.json` line 94 at r3](https://reviewable.io/reviews/openmpf/openmpf/1853#-OHO4-_-4GamjKfYOg_b:-OHO4-_-4GamjKfYOg_c:b-k159j8) ([raw file](https://github.com/openmpf/openmpf/blob/ab313db26f90272a2a4a6a88f0e4f0c7f3e0762b/trunk/workflow-manager/src/main/resources/workflow-properties.json#L94)):*
> ```JSON
>     },
>     {
>         "name": "ARTIFACT_EXTRACTION_POLICY_BEST_DETECTION_PROP_NAMES_LIST",
> ```

Please update the github.io docs with the new properties: `ARTIFACT_EXTRACTION_POLICY_BEST_DETECTION_PROP_NAMES_LIST` and `FEED_FORWARD_BEST_DETECTION_PROP_NAMES_LIST`. Create a separate issue for that.


<!-- Sent from Reviewable.io -->

2025-02-03 15:03 UTC, jrobble commented
*[`trunk/workflow-manager/src/main/resources/workflow-properties.json` line 94 at r3](https://reviewable.io/reviews/openmpf/openmpf/1853#-OHO4-_-4GamjKfYOg_b:-OIBKdKQ3z-YWSWxCs_G:b-4pb8zf) ([raw file](https://github.com/openmpf/openmpf/blob/ab313db26f90272a2a4a6a88f0e4f0c7f3e0762b/trunk/workflow-manager/src/main/resources/workflow-properties.json#L94)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please update the github.io docs with the new properties: `ARTIFACT_EXTRACTION_POLICY_BEST_DETECTION_PROP_NAMES_LIST` and `FEED_FORWARD_BEST_DETECTION_PROP_NAMES_LIST`. Create a separate issue for that.
</blockquote></details>

https://github.com/openmpf/openmpf/issues/1871


<!-- Sent from Reviewable.io -->

2025-02-03 15:14 UTC, merged